// Generated by tools/build_ways.py from tools/ways_content.py: do not edit, run it again.
package com.callbackdev.passo.core.designsystem.ways

import androidx.annotation.StringRes
import com.callbackdev.passo.core.designsystem.R
import com.callbackdev.passo.core.model.WayId

/** A way's name, as the reader knows it. */
@StringRes
fun wayNameRes(id: WayId): Int = when (id) {
    WayId.VIA_DEGLI_DEI -> R.string.way_name_via_degli_dei
    WayId.VIA_DI_FRANCESCO -> R.string.way_name_via_di_francesco
    WayId.CAMINO_FRANCES -> R.string.way_name_camino_frances
    WayId.VIA_FRANCIGENA -> R.string.way_name_via_francigena
    WayId.MILAN_DUOMO_NAVIGLI -> R.string.way_name_milan_duomo_navigli
    WayId.LONDON_PALACE_TOWER -> R.string.way_name_london_palace_tower
}

/** Where a way runs, in one line. */
@StringRes
fun wayRouteRes(id: WayId): Int = when (id) {
    WayId.VIA_DEGLI_DEI -> R.string.way_route_via_degli_dei
    WayId.VIA_DI_FRANCESCO -> R.string.way_route_via_di_francesco
    WayId.CAMINO_FRANCES -> R.string.way_route_camino_frances
    WayId.VIA_FRANCIGENA -> R.string.way_route_via_francigena
    WayId.MILAN_DUOMO_NAVIGLI -> R.string.way_route_milan_duomo_navigli
    WayId.LONDON_PALACE_TOWER -> R.string.way_route_london_palace_tower
}

/** A walk's outing, as History and Today name it; null for a way, which is not an outing. */
@StringRes
fun walkOutingRes(id: WayId): Int? = when (id) {
    WayId.MILAN_DUOMO_NAVIGLI -> R.string.way_outing_milan_duomo_navigli
    WayId.LONDON_PALACE_TOWER -> R.string.way_outing_london_palace_tower
    else -> null
}

/** A stop's name, from its key in the ways' data. */
@StringRes
fun placeNameRes(key: String): Int = when (key) {
    "acquapendente" -> R.string.way_place_acquapendente
    "altopascio" -> R.string.way_place_altopascio
    "aosta" -> R.string.way_place_aosta
    "arrone" -> R.string.way_place_arrone
    "arzua" -> R.string.way_place_arzua
    "assisi" -> R.string.way_place_assisi
    "astorga" -> R.string.way_place_astorga
    "aulla" -> R.string.way_place_aulla
    "badolo" -> R.string.way_place_badolo
    "belorado" -> R.string.way_place_belorado
    "berceto" -> R.string.way_place_berceto
    "bivigliano" -> R.string.way_place_bivigliano
    "bologna" -> R.string.way_place_bologna
    "bolsena" -> R.string.way_place_bolsena
    "burgos" -> R.string.way_place_burgos
    "camaiore" -> R.string.way_place_camaiore
    "campagnano" -> R.string.way_place_campagnano
    "carrion" -> R.string.way_place_carrion
    "cassio" -> R.string.way_place_cassio
    "castrojeriz" -> R.string.way_place_castrojeriz
    "chatillon" -> R.string.way_place_chatillon
    "citta_di_castello" -> R.string.way_place_citta_di_castello
    "cruz_de_ferro" -> R.string.way_place_cruz_de_ferro
    "echevennoz" -> R.string.way_place_echevennoz
    "el_burgo_ranero" -> R.string.way_place_el_burgo_ranero
    "estella" -> R.string.way_place_estella
    "fidenza" -> R.string.way_place_fidenza
    "fiesole" -> R.string.way_place_fiesole
    "fiorenzuola" -> R.string.way_place_fiorenzuola
    "firenze" -> R.string.way_place_firenze
    "foligno" -> R.string.way_place_foligno
    "fromista" -> R.string.way_place_fromista
    "gambassi_terme" -> R.string.way_place_gambassi_terme
    "garlasco" -> R.string.way_place_garlasco
    "gran_san_bernardo" -> R.string.way_place_gran_san_bernardo
    "gubbio" -> R.string.way_place_gubbio
    "hornillos" -> R.string.way_place_hornillos
    "hospital_de_orbigo" -> R.string.way_place_hospital_de_orbigo
    "ivrea" -> R.string.way_place_ivrea
    "la_storta" -> R.string.way_place_la_storta
    "la_verna" -> R.string.way_place_la_verna
    "leon" -> R.string.way_place_leon
    "logrono" -> R.string.way_place_logrono
    "london_abbey" -> R.string.way_place_london_abbey
    "london_buckingham" -> R.string.way_place_london_buckingham
    "london_downing" -> R.string.way_place_london_downing
    "london_eye" -> R.string.way_place_london_eye
    "london_festival_hall" -> R.string.way_place_london_festival_hall
    "london_globe" -> R.string.way_place_london_globe
    "london_horse_guards" -> R.string.way_place_london_horse_guards
    "london_millennium_bridge" -> R.string.way_place_london_millennium_bridge
    "london_monument" -> R.string.way_place_london_monument
    "london_parliament" -> R.string.way_place_london_parliament
    "london_st_james_park" -> R.string.way_place_london_st_james_park
    "london_st_pauls" -> R.string.way_place_london_st_pauls
    "london_tate" -> R.string.way_place_london_tate
    "london_tower" -> R.string.way_place_london_tower
    "london_tower_bridge" -> R.string.way_place_london_tower_bridge
    "london_trafalgar" -> R.string.way_place_london_trafalgar
    "london_westminster_bridge" -> R.string.way_place_london_westminster_bridge
    "los_arcos" -> R.string.way_place_los_arcos
    "lucca" -> R.string.way_place_lucca
    "madonna_dei_fornelli" -> R.string.way_place_madonna_dei_fornelli
    "mansilla" -> R.string.way_place_mansilla
    "massa" -> R.string.way_place_massa
    "medesano" -> R.string.way_place_medesano
    "milan_arco_della_pace" -> R.string.way_place_milan_arco_della_pace
    "milan_brera" -> R.string.way_place_milan_brera
    "milan_castello" -> R.string.way_place_milan_castello
    "milan_darsena" -> R.string.way_place_milan_darsena
    "milan_duomo" -> R.string.way_place_milan_duomo
    "milan_galleria" -> R.string.way_place_milan_galleria
    "milan_grazie" -> R.string.way_place_milan_grazie
    "milan_montenapoleone" -> R.string.way_place_milan_montenapoleone
    "milan_naviglio_grande" -> R.string.way_place_milan_naviglio_grande
    "milan_porta_ticinese" -> R.string.way_place_milan_porta_ticinese
    "milan_san_lorenzo" -> R.string.way_place_milan_san_lorenzo
    "milan_sant_ambrogio" -> R.string.way_place_milan_sant_ambrogio
    "milan_scala" -> R.string.way_place_milan_scala
    "milan_sempione" -> R.string.way_place_milan_sempione
    "monte_sacro" -> R.string.way_place_monte_sacro
    "montefiascone" -> R.string.way_place_montefiascone
    "montelibretti" -> R.string.way_place_montelibretti
    "monteriggioni" -> R.string.way_place_monteriggioni
    "monterotondo" -> R.string.way_place_monterotondo
    "monzuno" -> R.string.way_place_monzuno
    "mortara" -> R.string.way_place_mortara
    "najera" -> R.string.way_place_najera
    "o_cebreiro" -> R.string.way_place_o_cebreiro
    "o_pedrouzo" -> R.string.way_place_o_pedrouzo
    "orio_litta" -> R.string.way_place_orio_litta
    "palas_de_rei" -> R.string.way_place_palas_de_rei
    "pamplona" -> R.string.way_place_pamplona
    "passo_della_cisa" -> R.string.way_place_passo_della_cisa
    "passo_della_futa" -> R.string.way_place_passo_della_futa
    "pavia" -> R.string.way_place_pavia
    "piacenza" -> R.string.way_place_piacenza
    "piediluco" -> R.string.way_place_piediluco
    "pietralunga" -> R.string.way_place_pietralunga
    "pieve_santo_stefano" -> R.string.way_place_pieve_santo_stefano
    "poggio_bustone" -> R.string.way_place_poggio_bustone
    "poggio_san_lorenzo" -> R.string.way_place_poggio_san_lorenzo
    "ponferrada" -> R.string.way_place_ponferrada
    "pont_saint_martin" -> R.string.way_place_pont_saint_martin
    "ponte_d_arbia" -> R.string.way_place_ponte_d_arbia
    "ponticelli" -> R.string.way_place_ponticelli
    "pontremoli" -> R.string.way_place_pontremoli
    "portomarin" -> R.string.way_place_portomarin
    "puente_la_reina" -> R.string.way_place_puente_la_reina
    "rabanal" -> R.string.way_place_rabanal
    "radicofani" -> R.string.way_place_radicofani
    "rieti" -> R.string.way_place_rieti
    "robbio" -> R.string.way_place_robbio
    "roma_san_pietro" -> R.string.way_place_roma_san_pietro
    "roncesvalles" -> R.string.way_place_roncesvalles
    "saint_jean" -> R.string.way_place_saint_jean
    "san_gimignano" -> R.string.way_place_san_gimignano
    "san_juan_de_ortega" -> R.string.way_place_san_juan_de_ortega
    "san_luca" -> R.string.way_place_san_luca
    "san_miniato" -> R.string.way_place_san_miniato
    "san_piero_a_sieve" -> R.string.way_place_san_piero_a_sieve
    "san_quirico" -> R.string.way_place_san_quirico
    "sansepolcro" -> R.string.way_place_sansepolcro
    "santa_cristina" -> R.string.way_place_santa_cristina
    "santhia" -> R.string.way_place_santhia
    "santiago" -> R.string.way_place_santiago
    "santo_domingo" -> R.string.way_place_santo_domingo
    "sarria" -> R.string.way_place_sarria
    "sarzana" -> R.string.way_place_sarzana
    "siena" -> R.string.way_place_siena
    "spello" -> R.string.way_place_spello
    "spoleto" -> R.string.way_place_spoleto
    "sutri" -> R.string.way_place_sutri
    "terradillos" -> R.string.way_place_terradillos
    "trevi" -> R.string.way_place_trevi
    "triacastela" -> R.string.way_place_triacastela
    "valfabbrica" -> R.string.way_place_valfabbrica
    "vercelli" -> R.string.way_place_vercelli
    "verres" -> R.string.way_place_verres
    "vetralla" -> R.string.way_place_vetralla
    "villafranca" -> R.string.way_place_villafranca
    "viterbo" -> R.string.way_place_viterbo
    "viverone" -> R.string.way_place_viverone
    "zubiri" -> R.string.way_place_zubiri
    else -> error("No name for the stop $key")
}

/** The one sentence said of a stop, if it has one. */
@StringRes
fun placeNoteRes(key: String): Int? = when (key) {
    "aosta" -> R.string.way_note_aosta
    "assisi" -> R.string.way_note_assisi
    "astorga" -> R.string.way_note_astorga
    "bologna" -> R.string.way_note_bologna
    "bolsena" -> R.string.way_note_bolsena
    "burgos" -> R.string.way_note_burgos
    "cruz_de_ferro" -> R.string.way_note_cruz_de_ferro
    "fiesole" -> R.string.way_note_fiesole
    "firenze" -> R.string.way_note_firenze
    "gran_san_bernardo" -> R.string.way_note_gran_san_bernardo
    "gubbio" -> R.string.way_note_gubbio
    "ivrea" -> R.string.way_note_ivrea
    "la_verna" -> R.string.way_note_la_verna
    "leon" -> R.string.way_note_leon
    "london_abbey" -> R.string.way_note_london_abbey
    "london_buckingham" -> R.string.way_note_london_buckingham
    "london_downing" -> R.string.way_note_london_downing
    "london_eye" -> R.string.way_note_london_eye
    "london_festival_hall" -> R.string.way_note_london_festival_hall
    "london_globe" -> R.string.way_note_london_globe
    "london_horse_guards" -> R.string.way_note_london_horse_guards
    "london_millennium_bridge" -> R.string.way_note_london_millennium_bridge
    "london_monument" -> R.string.way_note_london_monument
    "london_parliament" -> R.string.way_note_london_parliament
    "london_st_james_park" -> R.string.way_note_london_st_james_park
    "london_st_pauls" -> R.string.way_note_london_st_pauls
    "london_tate" -> R.string.way_note_london_tate
    "london_tower" -> R.string.way_note_london_tower
    "london_tower_bridge" -> R.string.way_note_london_tower_bridge
    "london_trafalgar" -> R.string.way_note_london_trafalgar
    "london_westminster_bridge" -> R.string.way_note_london_westminster_bridge
    "lucca" -> R.string.way_note_lucca
    "madonna_dei_fornelli" -> R.string.way_note_madonna_dei_fornelli
    "milan_arco_della_pace" -> R.string.way_note_milan_arco_della_pace
    "milan_brera" -> R.string.way_note_milan_brera
    "milan_castello" -> R.string.way_note_milan_castello
    "milan_darsena" -> R.string.way_note_milan_darsena
    "milan_duomo" -> R.string.way_note_milan_duomo
    "milan_galleria" -> R.string.way_note_milan_galleria
    "milan_grazie" -> R.string.way_note_milan_grazie
    "milan_montenapoleone" -> R.string.way_note_milan_montenapoleone
    "milan_naviglio_grande" -> R.string.way_note_milan_naviglio_grande
    "milan_san_lorenzo" -> R.string.way_note_milan_san_lorenzo
    "milan_sant_ambrogio" -> R.string.way_note_milan_sant_ambrogio
    "milan_scala" -> R.string.way_note_milan_scala
    "milan_sempione" -> R.string.way_note_milan_sempione
    "monteriggioni" -> R.string.way_note_monteriggioni
    "o_cebreiro" -> R.string.way_note_o_cebreiro
    "orio_litta" -> R.string.way_note_orio_litta
    "pamplona" -> R.string.way_note_pamplona
    "passo_della_cisa" -> R.string.way_note_passo_della_cisa
    "passo_della_futa" -> R.string.way_note_passo_della_futa
    "pavia" -> R.string.way_note_pavia
    "piediluco" -> R.string.way_note_piediluco
    "poggio_bustone" -> R.string.way_note_poggio_bustone
    "ponferrada" -> R.string.way_note_ponferrada
    "puente_la_reina" -> R.string.way_note_puente_la_reina
    "radicofani" -> R.string.way_note_radicofani
    "rieti" -> R.string.way_note_rieti
    "roma_san_pietro" -> R.string.way_note_roma_san_pietro
    "roncesvalles" -> R.string.way_note_roncesvalles
    "saint_jean" -> R.string.way_note_saint_jean
    "san_gimignano" -> R.string.way_note_san_gimignano
    "san_luca" -> R.string.way_note_san_luca
    "san_piero_a_sieve" -> R.string.way_note_san_piero_a_sieve
    "sansepolcro" -> R.string.way_note_sansepolcro
    "santiago" -> R.string.way_note_santiago
    "sarria" -> R.string.way_note_sarria
    "siena" -> R.string.way_note_siena
    "spoleto" -> R.string.way_note_spoleto
    "vercelli" -> R.string.way_note_vercelli
    "viterbo" -> R.string.way_note_viterbo
    else -> null
}
