// Generated by tools/build_ways.py from tools/ways_content.py: do not edit, run it again.
//
// The land of each continent the city walks are grouped by: Natural Earth (1:50m), public
// domain. Every path is an encoded polyline (latitude and longitude at 1e-5 degrees), decoded
// by [Polyline].
package com.callbackdev.passo.core.domain.ways

import com.callbackdev.passo.core.model.Continent

internal object ContinentData {
    fun source(continent: Continent): ContinentSource = when (continent) {
        Continent.EUROPE -> europe()
        Continent.AMERICAS -> americas()
    }

    private fun europe() = ContinentSource(
        frame = GeoBox(34.50000, -11.50000, 61.50000, 31.50000),
        land = listOf(
            "wmxdJsm`iC``B_wbA~f]sbeAv{Aphe@hbg@nolAnsAd`eAr{o@fyi@p|Efk]{mKxeA{a^mnf@_bTxtz@utFvkDirO}hXsqTbxVmb" +
                "A{}mAsfMo_Kk{F{nw@",
            "qo{wEqsqpCpd@mm^czKsy\\`hJieEhcGxiP~hD}q[`iTmgRiwKqvfAfdV}irC{gGsup@xak@a}Jo_QophAipRew\\jys@fyMxoTj" +
                "cyGee]dwPq|Lr{n@o|QbbiDseu@lnCycE}qFbfIynK_tZqpKlmV{oU",
            "obxlFmi|mCfj[ykTdf_@{ttB|trAo}[fwQw`|@nd[bcIe|Ydk~@{et@dq`@wjIn`kAekTvoEwax@~m{AwPdhr@a{b@irhAleMuu]",
            "mzfxE{ajqEd{y@lxdBhoP~sEpxh@ixZtrBlocAtwi@|pv@nzM~zcArpS|rIe{PnnZnhAz_a@msNtsn@o`dAf|[fnEcqPm}X{`r@b" +
                "Lcmk@s~g@w`KvaFsaaCuvt@}|{CwkEyh[lkLncQ",
            "sa_`J{zlsBziXdhr@jqj@lnCvpOezUr}l@`bsAbbc@|wYtgJnzd@yw^ocZgzc@teb@wrv@ocEaot@ohmAcOshs@qaOisQbpNeja@",
            "sonsIuyukAxfX`rCxgLzzj@juVvrSjxNgf`@rlRqmDvcRtb~@`ygAdvF~iGpvc@k|oA`vg@qlBvwfAagWtqUwct@ruH_rV`wZy`E" +
                "_abAghd@ww\\{rAk{\\`qHaiLd}a@b^zbEadX_ve@wlUsbM~hLqk\\izcAdtIqgeAvnu@f}@",
            "ihlrI_c~_Apfw@g_a@~xc@lsE~xNzo^zUrjb@_jUntwAy{d@djXa|]kI_sQibrAzhImwi@mbIgjZ",
            "aozqFeieR|nAe}o@dpN_{Kpw{@xki@ltOfq`@ujOpit@wt]`kRrpKvgf@ukQhhXmt`AgmgB{hI{dx@tk`@peI",
            "uwoxFegxy@luiAwy`@tcl@ju^`bp@qmKzeeDnd[ldD`{MqmRj~rAnxt@|oPt|HxsOmtA`nl@uou@z~k@g{t@~uBczdA}_\\ufNri" +
                "ZoihAwkKibeAl}u@wbr@guEtaLcdZcWwvg@cnReuo@{~z@epnAvym@eqjAdsOb`KbxHohN",
            "{lgdGiszx@~}bCmvLdnpClefAuvf@h}hA{|TsnNuzJh~_@g~^kkCwa@~cVqe_@mmNwvKlbUgiJzeCuvK_jTqkMrmTuzo@qto@glW" +
                "ab~@hzByga@glz@gvHhbFspRlha@yiB",
            "}{ghFoha~Az`tA`yaAzu~@njYhxmAeie@ndi@fcb@jq\\bS_lCzv`AwfPfpt@oko@jln@sdJttUmhEzzaAk{sA|djD}sChmv@_`k" +
                "@f~f@epl@u{TilX_nc@f}[e{_@uj]ufq@aFurXbah@_f`ByqJa_r@c^w`xAgvValv@bxA{g_Ak~Y{eiAppCspYlfHdjJ",
            "wxcdJlj~QdySbSxbPrlRxveAp{vC|{Sv{G~oEmza@d`n@tdu@wnXk|mCr_FcsfA_{Di{zDvqPyjg@p_Z_}Op_i@xxm@fglArzm@~" +
                "|y@t|_A`ue@~akCusE_~qAhnNukl@ftKreCxqJltz@ho_@nuiAkeLnjrA~mNykb@loKgelBooMekh@mEskm@~gWqiwAz}_Ac`_Bp" +
                "ghDmrqAv_f@mqlBnjjAysqBbyQltVxpoAst}@y{WlgjAtnAxckA`eEyofAdudAkhmBbha@wpOrtp@ro{@x|Qwtl@a|]ynu@vp@{_" +
                "`BdxK_x~@vhZist@nrv@opPpecAxh]flW`wa@brCrjb@vqWmeGleG`xOwZvql@zgNtrf@dzFgn[f`Vpk@jtS`bzAytBygSzbRw{]" +
                "`hDwrf@oV{seBxkb@rkBfiY`~cAtuVtmOsq@vtc@jk`@nxmBw_Id{nAxpHjppBqtX`hzBnzMm_OjiMfrb@|hCjmcB`aRenLjyCbl" +
                "MouElk|@rmFrgOuwSzabA}cAjmj@bmOjcnA~skA|vt@xaAzdUk`_@rjmAtaSvdgBziXr~u@`|VdhTzhB`zSafOrwg@~nIzvc@ozN" +
                "htEciUii|@edw@osvAwkn@qt{@ugf@ytJuuHkgk@qo^{cT}gGqpbAv`Ds}hCasgBihhChlcAj~fDeqCtqs@mva@rc_A~kCvcbAsv" +
                "Pe`[ezNjtx@hTr{h@bwTl{y@ijU|}r@sfZbjQgqLmlNs__Aer{D}rr@wjm@e|KdgRsa{@|kChjT~qpB{aaAs}oAiz^eoaBevFwpt" +
                "A|}Oysk@{fYbhLchEeuRhvVup[e]q_`@gyFj}^gw^|q\\o}i@{fZc~FxySazXm^kuIexWiba@qlIeeGzbCfsH|gy@yiaAhxmA{{Q" +
                "rlCswg@o{WiaYgle@qaHagl@lb@xlcBho_@tqnAtI`ea@aeLzoVtgPjqr@ucPtuy@hr]feQq`MxsVezj@jlZaMgyUkfcBk`iAgse" +
                "@h_i@qca@a}By|KgtKdHgoj@c~T`xq@{|SwpGdmXpwW|tZ~xy@y`b@}_@wuXkaZbnf@fu~@v~j@yxCfiiAfi`@njJrbKyOf|Tqrw" +
                "@esHaza@kpa@ebAvbVihn@_rAawxAeoi@kon@gwf@~ck@jsyAwyDnnh@e_XjiS_hB|d_@}q[evmAauHppXy~e@gws@{mXwvDap[h" +
                "ol@qlP|j@gkN__j@qvVpz^orh@qtY?obwAkxc@t~p@e_`@csMqtCkm_AuxVn~Nupb@uiMuf@qmg@`hKukQilJatj@rzIqmJgxYgi" +
                "dF|}Ayfg@xhVt`J",
            "oh`oIhayj@ksCa{[{{RmiOslJwe{AvrC{pbAjbmA{ooAnxJee@prUdx_@giCqyx@d{^u{T|lJfsAubT~pc@by_@q}AbbAmdRffRb" +
                "qHndFbzi@p`c@ltd@aiFrze@v}Ly|JtzDnwc@l_oAwuf@f`~BkjUz~iApad@~re@b`o@vgRs~YrhJnbm@ofCdej@l_I~aTgsPbwM" +
                "liOjiF~aLdjeB~sS~`R`v_@tpsA{iK`scAbe\\kvJ~c]|tyAt|O`j}Aq_E`o_@r|GzvgA}re@is{@ruN`ksBymt@_}dBheSvx}Aq" +
                "mDddq@ksLhjFwsp@orzAwiAnz|AcaMspEutMyzj@zfEwheAa_]bdYa~Zmnt@o|X{wdDsxMtkg@dpV|cc@avBhijAlmOfmdAcop@e" +
                "fwAqgMg|L}}H|iLij\\cx^okTyagAuaEnaqBoxQpyTqr@fxo@qeIiuNunB`xx@coYx_Du|IcllAakIt|c@{qLuq@{gNed~@apM~B" +
                "tcB~m`Awfl@agJv|BrfNezTliG|bEjqUkvJsQgwJ}hQgjEiusA||@ieo@hkPec`@yhNs_[jcHofxAmsSzcNoi^yukAsaYw|QbdEh" +
                "b~@o`Mb`{@qtg@kojAoqXvbBwqWqdV{uFmjeB}eK`jA}q@ssQdfYiqTlp\\b}RczM_fb@cgf@puFu|Huei@{~JhpKcb@kdJp~Wox" +
                "bAnuRzfh@xsN~b@",
            "qh}hKf~zxA?qox@fh\\pox@",
            "wdheIcaec@{n@vut@zn@wut@",
            "avjdIuwd^`aKfef@aaKgef@",
            "{{ydIceo_@efIgdq@dfIfdq@",
            "swleGwasdBbpN__hBpeC~|`AuvR~`f@",
            "c_ffGwe}gBnOvpcBmuPbcz@|dP{t~C",
            "qhbgGyjmeBa`Bfrx@caEzbLksLc`DlaFahjAbaFybJ~qGzuS",
            "innkHpgiKfzHsu@vZ`ck@mqPy~AlzEslf@",
            "me_yGikkbErrHy|YaqAnnZcqPl_vAcpUfwIrsRqiX`lLy~gA",
            "cs`fJih|jCbtHt_OsnGbpMfyTptS|vBfhVuz`@trXktNlhdA__EujnA}_Uqnc@baMozMftCi_c@|u]uhR~j@~qO",
            "srjdJghnmCszJnuu@_bLe|RrwDcu_@~dRebA",
            "cmhzEi`}hDbqBt}Qg`Hp{Dczh@{Cy|`@kue@agPu~|@||fAhc[jnBb{VxaVf~V",
            "_ymwEmyzdDf~IrmF_gHhqFerZrpD}nj@ww\\phd@|zKhn\\g|M~qAnfJ",
            "}pq`Fih|cDjuAxnRyvZhbErvOuq\\xhGp~B",
            "kgd_FarncDao`@iyr@xxDqxYfuZzrmA",
            "kfs`F{l|zCxkFflPonZtoQkrWc|^`qGgfK~bc@leG",
            "q|faFehhyCz`NzoNyoGbjQ{dU}hXxsNaqG",
            "}|b}Ec`pzCjgInaHytB|wKmlUmoFzyN_jM",
            "m`xeFqcvbDxaGg`i@rzJm_BlrKn`h@wlNbpr@ccP}on@",
            "w}`dFczz}CmrSmcJiuFowr@htSpr[lsFjha@",
            "esp_Fcty|CfCjuUyy[ohq@twEqmKz|Tt`g@",
            "kfjdFw_tsCtnHvaLifM~fA_}NkzRrtSroC",
            "uy|bFkrctCn|DdbJorSjx@izIo_KhpXa[",
            "qlk_FkcwtCtqNv^hpDf~f@giPocE|bEsfLu|H{qT",
            "s|meFcepwCfcLhwDars@pdr@}pD}rP||MasKpv@}wRfj[}{E",
            "qtndFcxcyCbrK|fFg}@~dK}vXdf^`bNctq@",
            "}mghFwng~Cl`JzsQe~NnySyoT}lRcaj@fk[alDao_@d|Ja{[p_~@l}K",
            "_p`oFofe`DvqJtkB`fj@urf@iaDh{SbwNslJjdCbiNwjIlc{@{wIxiIcwUug_@lSf~QxgRrfScfOpji@qgTcqIugBq|a@uoLq`Ng" +
                "z@orb@xmIaeK",
            "u|zkF}gruCn_CpbYcpGu}Cq~IpqSy{PwxC~k`@u|c@",
            "_yvuF{vw{CfbDvaUyaOxiWsmEepVdmPk{U",
            "sf`sFshgzC~ea@dwNy{AhhQ}{LhvAhpKppKkkCl_Wmw[fY_c@ala@~qHgaIuiNc|^|`IjfA",
            "}s{vF{uevCl~E~`XkeLxmX{n[y`TpfKij\\fnUuB",
            "ac~sFsgo}CvAvxy@c}R{uo@jzR{aI",
            "izbsEuvycAvaM~c]kaZisXr~KuoC",
            "}iylEcd{aAdyEfqRobI|lY}f\\uoCyZuoa@bsLkvQ|wRpwJ",
            "maviIjv|YrvWvnf@wxAhl`@at\\k|Ogrb@sot@`~Y_}OjjO|mM",
            "ezlqIzcd^mhE|ck@cyYl}JsvP_qMzgGwx]hqi@svI",
            "cw{vIvngb@x{HdrgBejKqbX{bYm~Gq_Kpp`@mbHmZ}cH_wf@puTin]`qGohc@pq[niB",
            "a}jtIt`ld@j}l@}jMjgP~wo@{i_@qsB~tMx_g@ktTgqDo{Vaf`A",
            "}gtsI|_mc@no@v}LqzOb}Dg}Ngh^}kBzlJujIibEciM}wh@`kz@vyn@",
            "ubjpJxrjEwqPv_W}uUkbMrtEkzR`s`@~|H",
            "kvnpJtn~FjwLm`CcqB{aIjeLkfNgfDgqSjomBzfo@}iEn_Jsin@{tKo{B`fd@aiTfrb@}yHgnw@ynYlsMu`DzzVsnU{qg@zJadKp" +
                "uL~f@",
            "ufzeJzciRrkAtfUa}WnsUdZq~VfuTs{S",
            "_jmdIztrX~`Bkx[`bGfyEhlXxkw@etW`eb@urWpzAg_E{jp@vuQmbV",
            "}rohJnypNhFjbUqpJilJqr@}ke@x|KzuZ",
            "gfhgJzctQniH{wm@lsMszCwqBnsnAcpMnaG|pDjnPid^adCteEesq@rpLjf@",
            "gnfxJ|qlg@dhFrdHmnXf|h@lhFsnj@x{IgrF",
            "}{_vJrn{g@krPfzc@gmR~bHzmK_}d@vqWg`G",
            "uqgzJztzj@|{KmwVnnExhUgxEb_f@gxK|nG`Em`m@",
            "g{xzJbcng@ffYtyCq_Dnac@|w_@yoUyyZhiw@qld@f~]s~Dquh@jgPk~~@",
            "i|fhJvatOjzClwOwqOv_Hy~O`ib@_rA{_Ldi^kao@",
            "o{~zJzdbf@vaMviHkvBfsPwh\\h`Aj}Qi_\\",
            "oafcJvtyd@`aa@tyW~vQvtk@diBcp\\dtIlgC~tq@zyqB_dIdvLamTigk@upNnbf@wfHs_MeqDn{P{cSds@yaHmhMttF_xv@u{Tn" +
                "wHgif@yghBdgZiqF",
            "cm~}Ipcod@~fd@kx@x_KimyA~og@x_u@ki@nyK}c\\tyB}F~hw@glWhkVg|Ehol@yoNpvOusKgxa@izIdrE{|Fgpm@wkKiaCj`Be" +
                "sT~p[u}R",
            "oea_Jxi~j@z~I_`UnfQppPalLxz_Ae{HwtGc}Dsur@",
            "yir{Ip~fk@y~AvuXg|o@rtDfy@i_[xaq@akB",
            "s}`hIz~u{@eqKn`}@g_Dgss@lqPglH",
            "eogoJ_wfeCiyGlha@oePwt@x_Yur_@",
            "yijoJue_yB~hLoyo@`nPbwGroA|u\\j_Pvt@{`@zfw@a}_@hpJ_oBq~P`bMaf@{k@aeKec`@xxCzrFso_@",
            "ey~`Kabo`C{~Bq}[pqK_uHnzGvt^soWpb`@e@ww\\rbF~rB",
            "i_p`Jen|sBvdKhoBm|HnjRmvLotQjrBske@vzFhea@",
            "yfqvIgf{cBjcHn|QsbLx|Dclq@}cAec{@}qi@c|Co_RqepAuks@uyA{eQ|mjErolB",
            "wmynIcya{AiuN~xmAo~d@ezNfv\\qvfAp}VvwG",
            "_s|jIkqtrAxyRrJq~I`_k@d{Pl~UuqNn`a@}a|@{vHq{Jqub@lhZ}zl@ptQdaNvzNmcX",
            "aonnIs_rkA``Ix`sAuf\\yh]reR_wt@",
            "y_`nI}_jdAlmOgzhAz~WycDb{Hbg{@od[tkqAwu_@_oCeeAm`f@~vJibS",
            "glwmIkv~~@cfA`b[wgS|mZznU_qv@",
            "{~~mIual|@uyBrxp@}y^f{C~bO{ni@rpR_eK",
            "aodmI_oo`AitRn}T{oz@ui_AdenAdki@",
            "ccnsIwvv_AqChuN}sg@k}BtiU}jUxmQ~rI",
            "iockIqtzcAelHh}s@gcLwhMxgE}_\\rgOsrH",
            "kcm|I}rmbAw{@nya@}eLmkh@|j@yiPvvLv{V",
            "oqkmIgruq@kuVbjAev[ql]~j]l~Lrq@uwo@zrG|bv@`zJvvF",
            "isdwGnceFpaPh{Eetl@jea@rq[uah@",
            "}lktHzboExxRvhc@abNx|{@c~So}o@jgOaho@",
            "{j|bIiiy\\bzLziRoaF`fNkw[yra@v~Tz@",
            "mvqdGohm~@`i[kvCujHbjOhvBl|f@siLdVajHkgs@",
            "akmmFe`wr@~hR|eJmw[vtIlmHu{T",
            "qrdrFireYqyUjhrA{jS`uAt~DgvgAved@egL",
            "{hplFsgyGz~JnaFwfChu\\}lQfCk~Sk`QmzF{ci@z`O{pJvmV`za@",
            "qnyyEy}{wA`aEbjXe{HplOmvStEppWk~h@",
            "qqoqGaskyA|dCfaWkcWzem@wl[kqVdko@wum@",
            "k~dpGowoyArrGo|C}vIbza@ehN}kAnlPuoZ",
            "kirmG_ou{Aci\\`zt@_ih@`k`@vxbAwg`BjyAr`I",
            "wqakGypu{Af}AxiIi|q@n{s@`~n@if~@",
            "ktqoGqulwArqFfo@uqHf{J_}k@p|Swtr@ytBh`e@yqYnq{@m`C",
            "oi`dGy_njBjlLusYwqPrcmAjdC}nr@",
            "}vgiF{yx|BvpUqlAbqW_a_@`~LbkDo`Fdmm@c|Wd}LjrIpmRqs]}}IxZktTmzZeoGn{P_rH",
            "qzveF_xn~Bn_RcrSwuCjqObdLvtPgdd@|ze@upMy`M`gWcne@",
            "iwsjF_kg}BfbDdxX}ta@ekFolOkzRd_m@jm@",
            "_f}hFylu}BvbAxsHwq^hvO~m\\ckY",
            "outoFanpyBt}IofCuqOtbi@ytz@jkm@mjIqod@|`H{aP`sSdoNtre@ueTpjFs}V",
            "ei{{EiuukCfnGrgAiqM|sXky^yvFnyYcs[|aJjmG",
            "qjxzH_ibWtuPkrWxfCvfW{dOvep@swDczo@",
            "ednoJkajfCbdLu}m@voEn`SlkS{hHG`~RmqVdkb@snOecR",
            "}dmpJ_s|aCxaHhvAnStvYcoZpuMxwPqdk@",
            "eummJysx|B?rth@}tEe_Q|tEmtV",
            "_sqaKaqmp@c{Ah{h@{_KvmOobJsss@puFefK|hQvoE",
            "s~qcKomur@c|B`{b@ohUidvAvyDsxMxgLrlC`bFft|@",
            "iyaoJoi`^neVcScw@p~Povo@jwFbhZybX",
            "qubiJstvlB}wK}jpBldLieJndFvuf@|ib@tdXr_p@xy`Dp{f@jn|AflBbetCj`I{coBdbQ}lY`kJfbt@l~i@i`VdmIjsLjon@j_@" +
                "~[dcR|sR~bGjz{@o|Qb_m@tla@bne@ucI~aeA~~a@t`~AhwcAjaRre`@azJraf@`sCh}cDrlDlhLbvRc~Fw_Bdie@d`M~q]zc[do" +
                "c@teStjAzif@ibZjrXxx_@qfEbwfAp`O~u}AeuKdatAww`AqeP}|hBbeaB~yIw|l@usDurQcoa@rj[yhAcgf@}iKecKk}R~~E_yG" +
                "dm_@gqn@ryx@qqhBr|fAraCb|Pqnp@pdO_nFla[}{p@jeEenDvb]c{UbnRehj@bnBeuDrxb@w~wBtvRioP}nHlmAmfd@{aVvxjB}" +
                "ag@t_d@{hhA`uHtlLz~JhfTw}EpfLdn`@bym@qnEvxs@tep@ayBzxQlvLf~m@mb^jog@t^`fNrbS{bZxoFvsFtiUpwbAz~HowObj" +
                "JhfM`stBf}`FfhWdwgCmSn`yAuuW|}WyVznM|yOd}LgtDtoZ}h_@ipLu_@n{s@{|p@zfdC_sf@v_d@iqo@inFqjF_aJlzZqa~Auo" +
                "Xsrr@bqHdpr@oo[`ah@cfPgoN{`UjgBimo@uoyAl~p@lgeDhkW~kf@xVr|c@mnK~bGq~`A}qT{`\\e~k@|dIepy@ogMmqQknOgfc" +
                "A~rCjviAqjL|eSq`j@qhaAoh\\ixL}~`@svhApdHgzI|pg@hcHuxr@sud@giQszt@lcQpu}BhfMhyd@j}t@v`u@`vJxua@r_c@z{" +
                "f@hnc@pbcAmcQv~FqqdA{tRdmBmlw@oiIw{d@wbO`tmAizm@p`\\}in@ezbB`cVz}mAa~Kj`XupmAd}SumNeo}DpmEmwsAmjJche" +
                "Al{O_}d@|bSg_L}~YeHeiVefmBsgArdf@ciNheJudY_wQffKlwTbid@xwIt|Af_S{|Fd{cBcfO`dJbkYv}Sj`CvhTuoEbxy@ztKh" +
                "hzBqsOhhbA_iKrrOwvb@luBmcIsr`Am~j@vfoAuv_@aMgsBipgBzjTqojBgaOksjCjkBpbtBwfOpxgDcxPbh`@y_YwbHfr@_|h@{" +
                "a^kha@apSwfhA`~K_fa@mgJs~_B}zJ{|TvyJpskB{wf@_ji@u`BgxuB`jNe}uByhFwpVkyCn{^aaKkcAqtJaykBguFnwHtrJ|l{B" +
                "q|Fln_@vdEp`bBa~g@ecg@o_`@qizBjt@mgfBrsQ{qT|c\\anoAoq|@`zyAqlWedUo{ImbfAujOfdGsvBdng@cnIb`Di~Rmai@qv" +
                "Gy~r@peIcix@zeQvuJr_GctN}tTiv_@wqIy{gAzsl@wh~@wiN_i}@jq@w`qAq{Qx{OuaL{aI}bb@y`}ByjQlbe@epWapp@iwC~|V" +
                "rzJnel@`bLzl^dyMi~XvsMp}Tnhq@ryjDww@brXyua@jq]oh@fbf@gshAwmuAwm`A{okBcrWw{~@?kvmpCbr}hE??tcvnGgzp@_h" +
                "VeihAy}~@_}}AazR{`wBwz}B_qc@osx@_}r@shoCwe_Aqd`C}r|Cc_jBwedE_trAolGe~y@avRi`k@thDajVlw]ztJlnX_rO`c`A" +
                "wcpAbsMqxg@vwGsgy@scVoj{B~hLyhy@qiDozc@az_@etl@pqu@wyX|pEs~sDsvs@_xoB}kz@wupA}ud@_~~AlrDwxhAsj_AykeA" +
                "uwdAkqwD{yNy}cGu{b@ybiAqaA{}iBuvRqnq@]kf~Drmo@e}gBcei@kguC}mMi_c@e`T}jNcwFy~]|cOomPniO{tcAwqHkv{@eeW" +
                "rtEzmEwpk@hsf@uj|A{qZyiqDkne@ie}@}m[osiBfcEqk\\t`RrsInzMi`HoeVgzGxlH_t}@xq`@rn@d|_@ek[hkOb~FhuH_gVoy" +
                "[u`^u|Hgae@ieXgdc@uqA{_Sfwe@ueM|kiAfd_Abd`@zet@d}[~qHhfw@ciUznp@gwoAvzkA{rUhvlBnyrAxdzA~gyBvi]zaB`hg" +
                "@gnTdsc@wtx@udD_qq@hba@yz@qwBaia@}aQisJlkK_vWhyd@wyKnxJq|SrsJjuI~j]whvBv|l@_bzAdfJgo{A{dUkofBn_g@_ji" +
                "Dxxe@wzdAnlV{o`Cxel@wsb@~eaBeyYngf@}{a@?w`lYcteAhvMsjmAmbe@}qeAqq`B_de@qduAurCaxeAu~Zg}x@jvCq_zA|ny@" +
                "cloDtbw@u`Bb~Uodb@pwIyzbBbe\\ez_A|zCegqCxuRor[vgcAadf@fbCsr]ubT}xbBdg_@uwxD?_dtTkuTqpfBjuTbjn@?q~s@i" +
                "y[snXti[kfuAwfOmefAjvOsjW?`~WgnDaqgNogeBs}`A_ti\\?|yg@tarAlmr@`}t@l_^le_AfzOvmtCxtJthYmz[xmpA{tcAnnd" +
                "Aa|r@|vaCwrKbkiCvjsBdte@heDlnJkoKzk]ll\\b~hBqw_@|{yAgagAlec@ugC`lLfyFpy\\gbXdb`A}q@fcb@dpWtbTbcI`la@" +
                "gzUmrKt|A`vu@taKt{[uiFdmf@upM}pa@ezGuchAune@ihm@dz@`omDzkGbxOkj\\qgFifF{zl@ysOj|AgjZnwy@uns@lp\\aeLw" +
                "p]smp@aq@yzMhbdAe`[vfe@tqHlrRq~Wb~w@mcQyiIvLweM{`q@bpFoiBwkKbmOqj[`fj@ccP{dO_kIh|GaeYwlNqfv@eyDvjm@g" +
                "ok@x}Zwra@oyo@inM`ye@me]upF{na@pp`@{gq@smi@faOhpxC{lIxiBatzAmtOeyEexXghhAm}qAcyIoviBboY{hd@qv@whp@yi" +
                "IepVmnRjxUqcEc}ZxqCqkUjjVlgDg{Bi_kEcvEikHsmTpes@kzQgf`@shXaamDirH|r}AobX~~o@yrLfjLeuh@m`SxuL_suCa_H{" +
                "brAj{TczyAgmCc{uAonh@qtf@y~nAuudDwut@qa~DngHmhxGgxkP?|yOfyp@pdy@|flAlaFxb_@_|Gbsp@{oVjag@mddAqp^qad@" +
                "lcJsrPzw^kj@xcg@o}\\rks@j|Bv_{@ixMvdSymbAe{zBqse@_aeBewOvnDckKbiGjpFra_@eaVtmk@f~PhulCcsa@jcuAk`C`}f" +
                "@qkGl_IkwFgjh@{xK_hBgdGtqx@wbOl_^|nNio|CenZkii@j|Hpvj@gdN~n{@{uZjlR_re@p`@{al@hfb@~~v@o~\\f~t@`xFu|A" +
                "npaAm~TibE`_\\xi^`_NnnuBjwv@dgZlamArntAthYpulAb{@xsd@j|VhiDhcq@cqWjs`B|a`@nwO~mbBgni@eeHtx@rd_@zgmAb" +
                "cWw{@ezNlou@hln@pczCliO`{TlyQuiFfn[jbEbic@d|g@z~f@rftAfyFxlGvkYlqm@zos@faVmsj@zaz@wrt@hrd@s[lty@}bh@" +
                "tl~@czfDrgj@bvRtsEfja@{xSfxuBhrPpfo@|kBddrAfyv@vcn@b~c@b|}ArpqAjenBuvm@g~Hm|{@gchBn~AjbeCiy]`oQmsMfh" +
                "]ol\\xuqCpxY~y{@}rPnu|@~tj@`blAisC`l}@nyL`yBz{XynYjqWtjAjvPmqbAndb@aoXazXp`c@gkN`~n@ptDxdc@|_i@exm@`" +
                "b\\p~Bamq@vdv@yyFfpm@h_\\ij@jq]w`n@rxEjcHazKjgl@kgk@liOoyb@`dpA_vP|xGqqRczLtrQzdx@pqxAbhFxk{AkojApbg" +
                "@evp@dzb@qlQ~iMnx`@{o]}j@ciMh~_@lyCv}LniHdbOzhPgeHbdZyoN}j@iwR`sYjqr@htEjrl@`hg@updC`oYatUz`Fief@~vY" +
                "uiU~bNygv@~kYofJ|fyAz\\awdAhddB`q]|{yAbfOwsThea@}yHv{Fmxe@lgZudQtwSj__Au{[zq[wdSz{m@pkG`uHzneCol`Ady" +
                "g@xwBtje@sgVutNxra@yzr@v{r@vwA|fTb_`AlfVksDv`Kgdk@lbIc{~@|ux@|qFrkW|jp@|iK{bbAdm{@ayz@_wQi`]r_T_aXlg" +
                "n@clj@t}f@_pYeyb@w``@qtQzeCyvp@k{\\mn_@jfgAo~tE}aQthDakCuuk@aaS{fDqmJ|l|@wxf@jroAn}N~zRqzIdgdAbxPxf_" +
                "B}k_@jsZpcUjlDhpDjqVihfBzzoAemI{u@uqA{rUbwGkti@qbYci@~dCtcaA_f}@dp|A{ui@pjTs}^jcd@kg`Axd\\ccn@vrwA{z" +
                "VdyMtIuvYinq@nwVgss@idWs~~Ax_C}bi@ckYev[sJan^lkkAewy@dax@{bXh`r@_sKepAh|@raXcefAhnfCgni@b`wCucAaaa@~" +
                "ea@ykaB}xhBdg_Din\\jmbBjrClwnAkvYhrG}fp@`juAylr@xf|@epO`hK{}Ai~bAos_Ahs~A{fShyOcchA||Fiii@rkz@qyFdmm" +
                "@laaB~vbA_JvoSo{s@nel@}}gAt{Tcl[e~r@ca[rg]d|Jzz^}~Jlpq@xcYnka@|ia@l`gBaf@|wKyhN}sJpqRfni@j}f@~nHplt@" +
                "_dy@dc`@pcZyrEvrSvlT`~Dlk`Bu{[dwk@sqx@nuqAqoiDzekDidvAz}uAeqfBbr{@etyB{`@uizCjmGudf@p{YrrAh{Yjkm@|fT" +
                "~qAzzvAi}iFzgj@olgAvec@w{|AjxsAkwaBhuUo|Cnjv@`wZiqUj|r@c`bApqh@ivJvszA}v^zci@{aAp`\\jyI|bSht}@doq@hb" +
                "kAlz[~eTeyMvyJagk@rre@}tw@vuiAkvJfkNnzMy~Bdv[vgZfk`AdkkAj{L~c^zkr@db{@z`k@bP`|_AoqQ|jNgqZ`Pm|Wq_b@gg" +
                "b@cbOcnXt`DwgRagQmbHsyj@wob@kqA_dOz_Scl_AtjOsi{Bzr_AofKp_TmjBlww@e_`@xbbAq~k@bSe{e@bpb@zqLbdrAwjXypV" +
                "skOzr\\lAltr@cuqAjv{@ukIv_~AjxGx{]qe_@pwm@{{Jvsi@}_{AhokBgqZrks@ocg@xc`@koYhraAvoEfh]}j[_eDijmA`vxA_" +
                "bEvxd@wcm@gd@_l{@xbf@czsArzXirgA`pnDecSbgeB`{Mtwh@rtzApyiBdhb@repCt~}@vliBtaa@zq[|vWjvwAs~Chzz@koXhu" +
                "mAovUnzOofCfgo@afNprAf|Lz{bAuwShh~A}cUjo`@jzDfuZvfgAti~BvkdAzci@zfo@ajH|}y@{ci@|iE`lZvjQbcBjtNccPl}Y" +
                "g}@`pa@xnn@xwy@bpfCj~a@~qk@j_k@t_lE`vm@bd}@`sR{ma@baTzrx@lxtEhhsD|hxA}yVjgz@qknAzhuAvalC~{iBpkx@zbZu" +
                "dQjyHtsRtyBpuaBp_a@|e|@jevB|{zA~aEb{MqvO`xr@nvU~j`AmpGbseAd{H~av@}kHhmlAdlFdhhB|ih@l_{@lZj_r@dhNbcm@" +
                "llw@b_d@_aBrcO`_NbuB`jHty^sv^zapAunm@~fc@eg`@tiGwzF|nUa}PxnDmac@sde@t^|iSj_NfuMw_WnxQoxm@drkAepOiaC|" +
                "uN`tTh{DjjdBfw^hoaAuqU`ctCrkPzcmAyylAwzb@o~y@mjCwbk@l_Pe~j@m~Mwir@xkNvjC}ph@oiQ`oXztL~|oA_wg@|fFkrPu" +
                "uk@cap@ehOmsNqr[dcKzw^`kt@hmb@lwG|cj@_mEr|UogLbb@{jhBcoS{{f@mfk@y|nBis{@i_[rxEck_Bgvc@{d`AazCyo{Apn[" +
                "{_Z_yHy|KbyX{ma@iqTkc@hwR}|]pv@s~_@yie@gdArkWmuWewOukJ~_Ocg`@uBnaH|gj@q~f@}tSm_B~iUay^~xd@_oe@_dJoi^" +
                "omz@jnBksg@mtNmq{@aiG{xS_mZxo@eac@gblBxxCy~d@dk[ien@d}Fagf@mxPmdlFlxk@uoaGogSakrDj{[_elB{dO}h`@`uWca" +
                "hBoiBgpbAadQeheAypWcs[qpaE}vm@kkXo|_@qnMpyMd_Rb`QwahDia_@ns\\yvp@~aw@alYlcQkzZmhzAfin@eco@tcnAy_JfvA" +
                "nyD{xa@oknB|jU_qFtao@sd_@v}kAwkcAfwz@yu`@{jManWpxa@e|JanHiuHesV`gJstv@_oQjnl@pfEfwhAcoE`i\\qqLdgDemP" +
                "s~R}}IvtWjqArfi@sdPqgFisCdqI|wChpa@ahQj`e@geBztv@uuWdgxApzAzhoAwo[dsU_xLt~o@mnXqfcAmmVdko@ctAkq`AynK" +
                "ls\\`[zu~@uoa@pGosNu_d@ebP}f{AsQqebAg_Swon@gmDg{m@lxHkqk@pqp@av{@uwTkao@lSesfAjhKixM_nUocRf_LgyN}hCq" +
                "pvAyz\\j|c@molAbmBmew@p~k@iyd@xkGpUgwsBxax@wmVlxP_m}Dqr\\kjpBkvJzcw@c_e@geJmf^i{rAslYc|yBgsPwq^_~^sf" +
                "c@cc~A~qAuje@ewc@qpXslcCyz~@ol~DzrFckxA}fEi}aAqaJt{i@lrEbac@iuGp{l@{}Oj}YmxIyrx@vkZqrlAebBa}XkgWjrs@" +
                "iyAova@qbf@j`m@k{U}mNaoiAsexAymzBczv@~lEghVyeIwy`@_pYi`y@ks`@e|`@{_ZspfB_tEogrCrfUut\\jxG}vk@ugQtb[}" +
                "lu@_|\\ajGgqqA|g@ofiAtw[iy]hxMdmJj{Ew_Qc}`@}~X~|Pm_^vmV{N{pjAonE{iQwtP~uBmqqBt{p@sdiAp}Gmxe@w{Gpy\\i" +
                "qq@fj}@ibLxe`A}mMfqMc{q@oRqeIdtW|oBpmYy`SqR_tLyiz@eyLq`@oop@dut@e{aApjTsdCm|Q}gr@zoI}mb@tn}AaviAyuLo" +
                "w]jxNuezAohGbbHa~jA`sKeeViwm@qgi@mnJw}a@d_QcgX{p{@qlJqfEte[bkDn~Urxw@~bj@rzJphz@anPraf@seR{aBkqq@oi`" +
                "A_iK}d~ColnAogfBo`Fy}x@elV_pcAzba@hh_@leU_aQhbg@dpAptn@dpk@h}hAprA~oR}og@sF}mdAliNutNlz[xrLnmIzbShcG" +
                "j{h@}xM`{TnjKfcTb|bAjoYxjCrpu@t{NolVjks@fnsAnhk@irNzhk@`mi@fuFmxl@`ud@wgJ~dD{q[xySyjX|aQoh@fgT~g^ybB" +
                "qtt@xoN{mLuvDi|[|yVingAahKo`v@lgRs}H`lRp{InuSpse@jwKaqGjvKkmiBeff@gnlAymC_p|@ely@ksyAb_JsowA~`XyeVpu" +
                "Zuuy@elAa}t@`vcAqdk@ps^}szB}{b@z{Cc|IzpzBgno@xcRvce@}iqAbl@{iYmlfAm~~Immr@_}gAciGor~@e_Y{ohAkwSi{_Ds" +
                "Mgmm@`_]_ctAb_Ia{FcwTb~eAjh|@wql@h~Joq_@cfB{mnBoko@ofwA}bw@sqU_{DqmqAaq\\}bv@umy@um`A}{h@{tRp}r@jfOv" +
                "{fAvitArfMgdx@y_Dqzy@}odBkqH__eAzja@sw_Dl}Dwpc@axFe{d@yqu@{oz@odTkpo@qss@}|\\wh`DtdXwjQ``t@ej~A~ul@o" +
                "k\\|dVykeAciFgjv@udn@udwA_igBryNgjnBcmk@uhDdpd@poU|jj@aoQjybAscy@jmq@{bXwn`@wOdra@qpXj~LajNyeOuje@x_" +
                "CqxQa`rBquNdyDerRgy~@_nHcunEqnFeaNcpNrgAzrOg|xEldSuhcAtbFugrDuhZcn`@cmk@dd@hkPo_u@mt]mzb@~`C}xrAwk`@" +
                "_af@rsWqn}DeiOcxHsom@tdwA`Whj~B}{b@jerAie_@fr\\jnH{pXeiVynDm}Kf|YjwShc`AnvSr_kCkjN`fq@`oXf~aC}ih@uwE" +
                "`df@pld@flBnx`@ueLpqo@n|XgrNhmMlgu@myKxyRldZrw`B|qN`nkB`dQ`g]bzEtx~Dxf`@fkuAu_AzeJsde@ayl@m~Mz{f@{uT" +
                "bbOvw\\~r^nnDjaw@_}Wb|By}Lkw[cjIfdNckRceMg~B`{~@alSpymAoiPlqHziK|nd@ouSnqf@enqAtlEijj@moYqtf@vi@?_lJ" +
                "seLn`LovFg`Ted~@zdj@}qMrdXkew@gaPeuYzua@_wt@rgHs|q@_haAigOccB{d@_ta@ef_@rtSed@cncAgqReyqAy{W||MwZcaS" +
                "sbK|iDvqAgoNir]efY{|Eqvj@yydAwqcD{eQopI}aoA_v~B?n|wPfzNkpWzhOdtI`kf@bfvAnq{@n}p@pbg@p~kBjcIzyw@bw[nl" +
                "d@s|Gh|i@dpOdo@akI`lZlym@nn}@izBnoi@~|HggG~oDjip@dlUrxMpbL`pi@~m@g}c@jdQnrFpxStfx@}jOdvw@|u\\soQx_Kb" +
                "}LhoJefYjf\\djkAofJzbm@`|G|eEl_Xc{HtzRi~f@z_L`cW~qy@xnYnob@gwPqyFnps@da\\dyKl{iDknVvuJogT`qAqpl@haQk" +
                "hLotImpx@xob@ckg@tc]{clAftR|hCtiMgcp@ddp@kvf@|wLn{BbsrA`o`E",
        ),
    )

    private fun americas() = ContinentSource(
        frame = GeoBox(-56.00000, -126.00000, 56.00000, -33.00000),
        land = listOf(
            "|o}eKn`a`Jy_QcpfApvq@ehq@tpM`md@h{LohVbPbqrDk}Wa|d@ebXftpA}oe@q{^o}TqruAbzo@pzA",
            "~s|wHvdefJjrIi{qA`c^lfOnxPojm@cx]elAysAow`Ajuz@anO`jk@fbdDty^__Es|NdaiB`j]}}WbkKhtyA_w{@`pFszm@ozbBa" +
                "dpAg{g@",
            "bu~hIvvmaFtfc@kvvC|`cBgbfBvdSf`w@}~eB`j{Cov_An~{E`gJepqD",
            "z~pgGtzgaMciUf|vBynwGwncAztRgkbBr|x@ynS~kt@jjHliVje}@jocAy|cAr}nAry`A",
            "|cbyH|s}nJyuEozeE|ytC`gqFyyYlnwAmvv@melCmqJfebAmlMm{`As{u@pc~@riS}bv@",
            "`e~jH`cqeMlvfD~cV|\\rz_@uwv@||Uy~y@uq]durAtyaAm|Jtn}A}`y@usn@ukYbq^eiP_oiAqzVvfWy_pA_i|@rqEmkcA|kiA_" +
                "tL",
            "nbipGhbn|L_c@jgoAeyqAswYj|]wm}Ax_t@~}g@",
            "{ssjH~oexJarXjgqFqh`Cb~xGhmb@su|H`lqAwkjEf`d@ccB",
            "qqlwGjr}sJiqFuzm@xuu@fzd@ikHcv}@_mi@adu@tjAjgt@ogdA}_tAds\\upsAz}d@ifFnbhAv_dDunWhvvCmuwAg`G_}bDkrrD" +
                "zfn@gv]vd`Blx^pq~@pgvB",
            "{}soBfcqvMvtz@u`qDrpm@cdZiwJdn|Blpq@nucAiv^z~lBig{Aj}kB{t`@kkwA~sKwovB",
            "woqoBv{rrK~kKuw`B~nnAlxaA}zB~mnFmsaB_nFjrIw_hE",
            "gvtqItzl~Wzfv@rwg@qpf@|uq@pgc@l~eAuzuBwic@_dWendAx`zAatw@",
            "awzvIdcfnXdxBq|eA~{bDgfhElm@fqxAvtr@_|~Bde}AzyGgmtBlfuEogL{d^k|d@tpMsde@ji}BwnYwttAgrGlz`BybhAsma@",
            "_o|zIxa_mXzgMiggApnp@sfFm{\\bfgAdl`Aqj`@hnGtt~@i}kBjv_Bxd@uwvB",
            "km`}IbhxvX|szBwdcAlaaBj}Jkcz@xiy@ug^_~Qu{ZxivAccg@yqX}jj@vzp@hzm@pxdAc|s@h`Agrp@}`hAnvb@cp|A",
            "mu~aJtv_uXnmBc~tAxscBkopAwfnAxp}An_aCwvlAf{{@jyeB_yNdva@qebAotWildDrdvApt_@gkp@",
            "oynbJxyl{Xlhp@c{UuyXgas@|fTspkA`ue@vbBtnH|yfAxsGsfeA`on@agH{dc@nqzBpco@h}WseDxvi@}seBhn_Caeo@mdo@poV" +
                "{xa@}m[svoA",
            "mxbbIv{roWdgqAyhG|uk@p_`@yo{AbdLtnPb~\\g{|@hqv@{nw@go\\bmaAa||A",
            "ywjiI~gthXts`@yq~A|gz@n~fA{mEe|bAegcAkgIg|SmdzA`cjDbcbAezGbxnCsxF_w|@_v]lxoA{f`Bxkp@g}\\wtHpcEmvkA",
            "gwtcItcdcXtkt@_gVrgG|y`Afxa@m{cBxbW|lYlaw@unvAjzYblNq~yBfhwDcei@kdCs~Y|umA{iJu{yC",
            "k|rzGncndKneHec|Izui@rbaBz`k@~_@cmP~y~A_xo@ooGbq]x{l@ixLborA_doAz{pCkdqAo`lAh{v@plQb|z@y_u@",
            "wadyF`aqyLqqM}muBpknAdd{F``BzrbD_{u@wnxAwql@ez|Ftr_@x_m@",
            "jsm`I~ddeLziDaksBfqjAat_AaeDxhd@ldg@peJj{Ge}~@~dpCaihDbn}AewmEzf[akmEhem@z`x@f}U|bjEabsAdy{_@kv_@yxR" +
                "azS_{bE|hf@g~}A}spAryjBeek@|[gdq@su`AbeeAgr\\xtB`zo@`yaAmnjAgdGm}`Bb{r@e}rAc}Zwbs@{j}@fdwDedj@ry^qoc" +
                "Bw}rCf|Fn__Deqg@hio@wmr@ek_Asgd@lvo@boLgzuAok_AsjtA`la@}u_A",
            "_`klC`{nrNd|t@m~hKds|AsjiBx}FoarBhfnBk_lEeoMegZdpk@a~cAl`Erjj@dfX_cUmrSac]doq@_dl@bzi@_p~EfvUuyWxuu@" +
                "vcXlnKmmcD~c}AkjmCrds@z_{Dd~GvpzNiyjBokvBmcm@bqWeaVhelDa_x@`chAyghBvgm@fn@x~yBgchBdi{ErvHtmjB}}d@rg" +
                "\\|}]~hRqjSljmBu~`@~qk@chTcwfAsia@|aX_hBbsnDbazA~h|BniIxwdBvik@|lX|nUlt|C}bo@c~bBunz@dyEmaw@gx|@ka`B" +
                "ucnL",
            "kuatHdfjgWje~@e_nI~sxCsf~Bzwz@s`bDfduCaajCjzXlow@qr_An}{Fmb\\bct@qaoAu~~@fwe@xkUruNdxlB{z]dfaAcjQw~b" +
                "@cdKj`{@y}\\sdBglBbwvBco`@oh@m~N{snAmog@lm~Damq@xmYb_Af}vBi_}@beGr|F{{pAkza@w_CxoOturByvx@njn@~_]_pv" +
                "E",
            "o{jwBjqdvLwpd@}ibE~gn@exaEbxgA_ni@djDi_bBpa]vkkAnrh@{jvDxrfAiq~@tb~@va_As|j@ltqBpp_@fmuI|o{BphoA_yrB" +
                "rgxB_hBrd{Grvf@fhgAyqcAvhoBwfl@{cMzad@kcwHw{c@mmuAanvAduyAgdgAcaTeoi@~jfCq`\\fYcqVejeB~hg@ybsD",
            "nwk@bb|mH~hL{kpFfltEtbuA~kClfaAdoc@~}JidPbgt@hlu@phy@_MpehCo~iB|fp@}wYsub@mme@rxi@wuzBcl\\wp]}qlA|_U" +
                "k_xB",
            "_cahK~ed{Ad_aE`auT_c\\htlHcuXjxx@m_VosNshY~cfCt{T~~lHyld@hvP{mKgdG|qGyhcBskaAumlCiaC`cdB",
            "rnkpJ`g`vGtlh@qgiByaUrctC{iRa{i@",
            "pbttJ|nuoImz[zgj@`tGazjCjeSdq_B",
            "rqq`Kdi|qIfbEsrgAb~[jBwtBhkfGsk^a{}D",
            "ld{xJb|z`JbeT}daAn~c@~liGsdy@aggE",
            "~bahK`kl}JoujAuyf@ppWwvkA|cr@p|m@",
            "v__`KveduIwoEvfkBvoEwfkB",
            "jwy|Jfy_qJ~uIomvClnXdpgAs~KzocDqpPrkPsfU_~cAjqOe`a@",
            "vbshH`b{kMera@fnZmtcB_sPy~H_a`@hwtBunl@boZlucA",
            "vk_bIzm_eMdhsA{fsFehsAzfsF",
            "~jenIrzlhL||FadrFjge@li]pmRiq_AzwjAqwl@_ud@z{~Ceyg@`oCipLzaz@~cXfp_@f_a@yya@_~Dnbl@{}x@x|mB}yr@asQhf" +
                "F_mb@",
            "fkaiHxgliM`beAlkgBeaUm~\\atj@psQyjCq`|A",
            "|rqgHn|bfMlvEpndAcctBji~@ima@}~pA~yoC_yq@",
            "hw}lIhg~hKpv@{hnC~sa@~o_D{yMxlVupT}sg@",
            "fsleIfya|Lbs~@kekCn`}@n_{B{pJxaVwgf@s`e@fsV|gvA_cq@fgSgyb@jvfB_pK{bsD",
            "hfsoIpplxKncL`k`Eu}m@|dl@{QugmE`la@ih_@",
            "xk{mInphpLv~F}boBn_g@_kVevb@|pwEahK_apA",
            "p`~wHnfafMb`cAltmCcubAqmY_J{esB",
            "pm~qHjcbiMlfHr_lAcw_Ak|VjdRw_wAhjc@n|a@",
            "r_czHlztgMnl`Ai{v@zi|@jx]qw~A`goAy~]cdv@",
            "`hxhInmvrLxlNo~fAver@juVchM~g|Camp@|cr@ay^ixh@t{[ojuB",
            "xx}mG|l`aMlje@zas@f_cCeyo@dmJpwbA_icCzhdBeoq@mtdBato@k~Rjtp@iuq@",
            "zb{uGpfqdMssD|rhAcu~AqaiAvidBrM",
            "ggr_Hdr{xJlyCusZp~Cj`m@}gd@miOcoh@ojfB`~cAfhdB",
            "wsrgE|q|gBdrTae`BbrQfn~@ieg@xu`@",
            "q}elDliubBtxgAbe~@s|_Atho@kdm@qtwChhe@vdh@",
            "skijFlnphDwwc@`}fBvwc@a}fB",
            "wj~qJzmkyGxHpeeB_~^yeqBdt^f_K",
            "u`imHjwwtV_kk@d|_B~jk@e|_B",
            "qyavEzualMtrBdo[mcJu_]yx~AklEpifBz|F",
            "i`seD`keqQi}dBsfx@h}dBrfx@",
            "cgt~CzsapQ{piEp`i@zpiEq`i@",
            "cf_sCvo~xMjtbB}kOsrAvqe@ogzAxsk@gxDsyaA",
            "glb}CfcjvMepVpta@swgBmc_@msv@zbt@wfJdrsAZs`oAv{gAaizAjgyBnb^",
            "kcj`Cz`v|Ltsh@p{YfUv{cBe`i@yz]wHo|_B",
            "asqfCbo|cMa`dB}tdA``dB|tdA",
            "g_qzCdnyrM|vbA{~dBn|~AfkGuz_@fk\\k|y@id^_a{@rcxBkyJ}vX",
            "spvjC~gxgMu|s@zwiA}faB|aQrdvCyz{A",
            "_qurCntsjMz{Jr`e@}vWglQmvqAv`}@nq~AcupA",
            "ktxuC`joyMrsn@pGdka@bpy@{laAzfkA{bDsrd@icjBqrNft_BkypA",
            "cyneDhnlhNwvnBjzo@vvnBkzo@",
            "_ftbC`j|vNxmXpulA}u\\`xj@jFy`h@gmcAdmBvfIc`u@ff}@{y\\",
            "qocbDlsa~MblFalnBded@lk_Dc{c@ngn@f|Sosc@ms[krz@",
            "qjz|@tlksJlvKlrmDi}e@kmnAsk`AqbC{kUrw`@sfUaznB{r@ql^zzhCnmQ",
            "y_}bAnqudKrpn@tiLwjQlt}A{d\\c_kB",
            "eq`nIbt|iXnKkzn@rxb@vbd@wcsB`mxBr}nAmumB",
            "ap}yI~yxpXx~d@cap@|aeBxgh@j|Hhzm@gbiAspSotiAbow@kf@o_jA",
            "szmuIdejeXfm_@x_C|Tv_m@gnq@bp_Auuy@}i}@v`kAwfs@",
            "ojocIr`pwW_ohAftaCbaTi{nBzls@}wQ",
            "d`wGfpj{HcdxCo}v@gcTg`x@hy|AnjC`noAfskB",
            "_ks@|nqnH|{w@z|a@}~KvnqAkxc@m`LsbFekgB",
            "keZfzwrHhu[jnB}bK|cb@{j\\gsAaljAslm@pewAplI",
            "e|C`ralPnxvCeh{Ajgs@fv_Ay~]ddfAs}y@kchAkrlBf}{AaoCcl~@",
            "qgipDrusqT_vdBlhsA|}s@sejA`wo@yaH",
            "saytC~d}jTusn@zwm@}z_BoyYrooCk}R",
            "_cahK`illKlvS|izAn{r@idoAd@g~~A`{T~jVb}g@asjAreDll\\hepAcfHfsBjj\\cjdB~}eBzx`Be_WluaAsmlAqaAdx~Anxz@" +
                "irIo{|A~zxEzrNded@ukm@h~m@bce@nhGiv`CvphFpi|@mgY_vz@npnCdjChopAdufBkjuCjd{DwaeLzrx@|jN`|Gfse@otoA|fo" +
                "Mc_~Ajt|Dyxl@jddHicVge^dtItjmAyjcA`~|B_a_@clvB{y[~qpD}r^gpX~}KbfaAeroBptyDtu^bmwSuu^tzbE",
            "_cahKnblwOjhkA||tCytXzenGh|b@cic@cgCx_|@jaa@af]pkUdrZrfThj_CcrmBtjrPx`v@itYz{`@i_qGztYhe{@oyZgvxBlwp" +
                "@sgiD~aZmpq@b|m@knAzvq@~pqCy~AzdqDvik@_brAh|GjfwBdq_@lhi@hih@}zm@ike@thcCfg\\aqy@zit@tacCfca@cus@nyv" +
                "@pitBrgjD~osBjwSbhp@xhoF~dDzze@n_`@d|cAc|aCrwpAhyG_ytAoyg@fdAumwDhnqGeupCrxlAhjfAqaz@ezmLvboAyzwI`{y" +
                "CgoeGjaqA_u_Jpfp@oqxAnts@jw[shg@cmz@itDst_Fteo@kjgHrtp@w}`@rbnB|~f@lkrA_fv@fuxCbi\\`ysB{dfCnug@|rk@h" +
                "zBmseAx|gBqojDtlu@qg[hnr@ltnAsy]{_qChrdB{qrCuvqAtakAyhuAk{lAfqrA{`tAi`y@{p`@{bu@h{o@sa~AsegBkooGnk~B" +
                "qpbA{jSkvaC|{jCm~wBsiyJkvhCe}dEuweAmai@as_DjdDstoB|b}@uosD`f|HkggC_jrCaxx@wvEv|Q{shAasSlrYa|`Aqhe@o|" +
                "Kf}x@cgJi~Xc}u@nsk@sqUwva@_~Qjbw@u}_@}hf@}`AvqrBg~nCwgaCszt@~_bBw|vA`{T}tw@essC~bq@}xnHv}KorZ~sLjiUg" +
                "{X}rvAvje@_liCeydAyctDracAgzeExnv@dpOfv@mpiBvp\\_jc@hdQ|ia@azD}xoBtsa@vei@jzu@cisAhsPgi~E~lh@}_w@s|b" +
                "@}o~Ahyd@cgRxdeAxtbAhkoAscNjuHzr~DfcTqzrDfmn@{d]lb`An_StpFo~`AnvsAnsc@m{Ojip@lbe@phgAsb[_l{Glm^o||@j" +
                "qq@ms\\jw}@ryWr|q@vsdC}c\\ioyBstsAitkAt_d@w|X|r]lha@e{r@mc{@fwoAqdNylj@_fToyoBexjFvheAaieAaakAf}Fexm" +
                "@ay_Ca|\\zx|@kzRwhw@wi]bkKbbOmitAuq\\lbgAeim@jaDhc@ucnAeyYf`[asqA_fdAngK_b}@l|Q}qNnb^nccAucI_v}Ax`~@" +
                "kdJm{Ncg`@fp{@svz@rzXjce@fhc@oqfBpmZ~qkBsyA{clCxff@pqEfae@qvnAx{aAzo`Cqc[afwDvuxA|kaC}eZqlvCfin@m`fB" +
                "bqy@hy@z}Vl`fBpjLceoBhw`@z~Iljm@cv|Bdl_AxkFsrVfzzE`zt@ajsCf_Sxqf@jhKsrcBniXvew@j|Am`cA~_j@`qO|eh@aow" +
                "Eniz@_`\\ldqAv}qAquo@usfDfbYst}@hueAjbmAmkjA{|oBxreAes|AmhFyu~Cjsv@g~kBdvhBl~nFnklAxdwIvn_@osx@hcj@n" +
                "wk@q_jC_sfI_cUkzjCsqTh`hAfrF{qmD`mgA{{u@rfb@|~jArxZaqd@qay@ku|Cvtx@y_lBzu`Do{^lgR|}dBhtLc~oBnsNvxr@b" +
                "|f@geaA|`nCzo}Ffw^xtjH~ejElrqHzk\\df`Iare@bn`EfpPnhaVnri@h`vAz_}BzcsAlp\\|upDn|aEtznGyaq@jqeG|iv@qc`" +
                "FjmsArdXrjwDjuwFrhm@l~uDhecAhsvCxa{Anx_Bxmg@nwbDbic@{saAzsaAbqnCwgqAmw_F_gqByylAumxBoytFufmAaylGgquD" +
                "wwkEsv_CkxoFk}{BmfqOvfbAykuF~qUmjIeyExpz@nh\\ugs@nis@baSdomAdzpDuv_@piaC`o_@p{vCjwTu~eDjan@shn@apa@y" +
                "guBjyVghy@txxB~fwBt{F{e~Ahw`@voMpn}BscfAtpM{dyB~e[~lZx{^o`dA`~g@{ayDo}i@cezCnox@mduBz{XekLvoMx}a@lsM" +
                "a{rAlzuBzluNbuf@`c@{e_@bdkAbnQx|v@rfi@_`A`k~CppjFmwx@fx|Bum_AzcL}~qAqn~@dnKfnj@graDox_I~k|@_a|@w{d@s" +
                "gGez[cslCx~@~}dH{}|AqalBktT|b}@fe{@fn[`dpAd_wEshQb_k@cvRagOny}@~uoAqjMhxdCzvaAo|Y~quAd|oEqaWd}kAbso@" +
                "`_OowNdqu@eel@srHtbqBboyAv~i@rayDjxvD~~}Bbnf@uei@z`x@xrsA~}Rmc{@jb{Asz{@qmLw`rA}fp@~~ShjmA}h^f|ZbkiC" +
                "ygb@|qG~_k@nhzA{`q@}zBauHxcn@dipAl|XfiQrxpGdggB~nnEsi`BmjBpo`A_jGhijAhy`At`Xs_x@hqvBz_Tauc@lcB|biEnr" +
                "`De|f@cdDqibA~nyB}ny@s~Rgzd@e|bAzpf@|ekA`kz@fkTbelEmogBl|wFp|mD{s{Ckvt@cmBdld@ogkAbp@yoMfhnA_}^aBe|C" +
                "cho@qoOji~@c}Zgx`@c|Irv^s{`@sde@ekT`sRqj}@czeAtdn@bfgCdznD_ma@e|_@lrt@p~vAg}~@ms}@~amDs`}Amnf@|e_Bri" +
                "v@dgaBy}kExgh@jqk@ol}AfywBt`sBmi|Ch{h@afGxhOded@ghl@xiz@plwAct{Ae_u@j~{Dpo]wapBp{t@g}b@u`Buk~AvqtEuz" +
                "yA}`cDzooA~tiBauWko_@r__Axpr@`koAkwh@b`a@``t@km@inAwe_Crsu@huAets@ozk@ryUeqQ|o~At`pAwy`@ndhDbeq@a}eB" +
                "nuu@x~r@}a_@lzw@`hXurQ|~EyedBfr[{hB|zm@vgfDg~WbtUf{f@_jEzrqBh`jBwwk@~}Chfq@jvJltc@xv`Dd~qB~zsArmzAjy" +
                "`Cjj]bmfC`kPmf^nmYvoSsk^|qj@`kl@{cT|y`A~ypAfxqCdxbAxkcGwdh@fl~FutlCviqBgcL{oxBxh\\`wa@b|OkroAdg[bqhA" +
                "unP`hrHcmgCzg}D~{M|{tBj~dAt|PlfyBuo`@r~Cb{Gqee@yumBd|qAqu\\zmcAm~aBrpn@_oe@gmXxjYjeh@o~nAocDhvPv`u@a" +
                "yyBn|qAuq`A{i|@gn[f~l@lir@|zCm|Wjtb@kljEiod@}plFz_oGlvqAz}wFsguAfudAie_@sbMnlUhqc@ujk@|r`Cyh@iq_Aa`P" +
                "raY~_]viwDacl@qwf@`cl@zjv@ddTrqlCq{J_ci@}qmApdj@l~~@vfWknH`juChto@jmdCsxTzepCzxYryNdvTslm@}{ZyotAhd_" +
                "@zdNteS{yb@}wZobl@jbk@i`Hxff@jqfApipAkvhCfkc@vhZh{Evaj@}ph@~aL{~aAnyjCvimAgpC_~^prfAr~_@hpo@c{]nhhB_" +
                "tD_fZibo@xcR}at@`z|B~ou@~xfAgkj@vtqDhoIjb~Bevp@v|Azuw@jqHvqz@bwhD}}^mql@R~ep@mnf@abFzhHtzu@rx_AahY|r" +
                "mCbo{D`q\\zliAq|Zwsj@k_NfzyBtbp@mwi@bc|@fsnCb|]ehOla\\|~dAhp_@i{ZpzaA|j\\yfXli_Av~i@}iv@fxqCywHraxA}" +
                "qx@lg_Ix_fBfywIhcd@phdBymQhxhB{svAx}w@vnQkmx@y_DwyxAvigAbx~FwymBjndDesmCvblEcsgBxeVwfoC~hgB}_lC_jbBe" +
                "hiKs|FggzA|qc@iwJz`MmciAox_@cpq@kyr@|o^iiyAyegCitbIkljAwjlBcmoJ`|V{mlFgwWd~UurB{d`A~h`@{ch@zipAkt@te" +
                "jG`jiD~nIkjr@xbl@`ul@lrKcx]n~eE|wcAainBvza@nw|Ap_}@n|Xcqr@nevHbqk@j}oCxkpBjuWuww@ijc@}y@|to@wkyAc}g@" +
                "wyrAx}[mezCiaCepjBaan@wmgAfuEmsdEnt_@{bjC|ijAc|}Ap_Fjl}@pgb@kj`A_Jsgr@iq[v~[raXocu@ffo@}ih@hw_@f`q@x" +
                "w}Akck@|ltBpwz@vdbGljB}yy@bbOrfh@pl^dh|AmlMn{^`_\\vwi@era@lxaAtei@di_EowdBfslG}yvFyjCkcy@_xb@biU|e|@" +
                "occAtxAuf}AojxCeeaHv|JoyyA`pzAahyFh~|Eo}jEkl|BxcYguyCqmmDepOkwjAclrC{tR`aKbd`@_~{Bo|xAmw~@axmAnaUwmc" +
                "BreYvic@|~QcpUsokBgkq@z{Cs_aDmk}EocnIfjR}n`A~lw@akWr`|Ata_DlfqDeyeAdlcDrgdBt|tCej_Bc~TgzhAooiBozc@er" +
                "`DtfuAodsAmyCsokBq`kGv{Gcbx@qse@lmArgHhhhA}`r@bjQ__x@_ev@digCivgAdlHq}{Cd{s@mzrAtoaCyoq@}fZotpJlchAs" +
                "flA`tc@sclCmssAs{oGkvXlrmBstS{kwMp|g@~}hEpen@ink@hsl@buIyd[_dd@ropAa|k@}nd@uon@`dbAgsaAylr@ev[dggBmp" +
                "zCnosClywA~PlpgAbpc@{m|@ejg@g~|EtckDmygGj`oAeh`AxruDxee@o|xAgkq@~vKsmsAtsuB}mrClz}ByzGwryA}mh@tix@il" +
                "pEufr@_qLxbIco~Gd|Re~y@xtvA~zRitqA}h{@jwdAacxDzh}A}{uBpm`@~sEnmIu`s@vhfAywIejv@ega@`eoBwda@awo@erS`m" +
                "i@u{~@hv}JovaBvmz@}{p@xc`@__aBl``BakJttvDfffDnb{@|afBhpyFzhgCt{b@|mdCnyEw}jC_x}B_rlEv}_Do_g@hqp@s_w@" +
                "ulv@uxsElusDx`~@uroCgbrA_wrAmz`BbtWego@}vXcbU{v`A~oRaunA}j`ArpDw_gCkeZm_C|nmC}xyJloeA_hX}~o@{jp@dqu@" +
                "{_rAh}z@gdU~ph@~ti@d`TejQiag@mik@bqe@anIh|bDpsaAignCgq_BfaaAq_FktsAwu}CtphB}brJsvIe}fHvdfDwxaHfkhF_c" +
                "}Fbpp@atiI|}iJwo}Bd~wDzCz|tFvzaBdcxAdljBttzC~bbB`u`ApjhBhokBluhAobWprGrodDhj_AnjpC|rjBn}Tzrq@m~_Afod" +
                "@xm_@|k^vzzC|km@np{Lqwg@tr_Gb}}@bueBopHtbjBz_`Bnu`Gf{XdldIfwcF`tsC||Gpt{@tvhCvn{Bjx`Ab|Bn{qDyfn@~ge@" +
                "p}r@tsLrpKx~rG|ti@keLfffBlvmD}j@ndbBbbuA`zmDhc{CvbzEvjiAxuh@ue[n_f@bk`@dkM{nMr|p@xsk@aq_Arfo@vtr@|zq" +
                "AvbO|btDk|d@pklGl}n@h{xCrywDbdqJdqdFvgfDjiyE}pv@buC{_dAcoyC_wiE_yeC{dc@arB~mU|byAee`Azit@vi_AynZrsjA" +
                "bqWlnzBvseCzbxChg]rm|DjoeBtkjH|cgHder@zhnCau]vpuCfpXhzdBcuwAls}Df{C~q_CwasCn}uBczgBkqMk~h@w{s@cy_B`e" +
                "Tnf~Aq{Dnv\\bop@vxjBf~VhlfBcf]bdSh~XtsjAkhn@vrcCkixEd`hBf_g@`mlAwmy@v_QmaeAbanB`|@nh{Ezb_DvkcAlnzB`y" +
                "kBhz{Pmtd@~wmFvpuAcwF`oXycn@du_Df_cAtj|A_k]hfi@f`\\|os@frnFsfdAxvyGzg|FafOjx_AipmBon}@i`yB`tpB}xa@`f" +
                "c@~opAqyfAtnwAdz\\zh}Albz@gg~BjwtBnguDxfiClqAzpiA~riAzsbAgv@clG`ujBpcx@lvqCbizClp_C|ekA_eQh~lB{nmC~m" +
                "\\_isDrkoAehN~mq@pzvAtiU{apApkdEpnbIluhExlvAvmVl`bAiwcAtcoA~wb@gd@pcLhb}@~f]u|kBpyj@xadBfc}BrzpAmvEy" +
                "w]nbkB_{ZbhFponAfbQst`Bv_zBksnBwyRlndDn_mBbpnH|jdEpef@riSz}y@g`p@bfjDgbv@nqm@wtU}_{Ap|o@_j\\uep@i}Hi" +
                "ze@iewAaqj@iaKny}@~flErc_Ab|s@_mi@vkaBg~|Aon~@ys]qqlFksLdpiFzchBtcoAwgm@dbeBkdcA_ydB`q\\v|lDokgBp|o@" +
                "zeXmasA}pv@q_jEd}o@axj@~q]v}Z}wRufd@ghjB|vBogp@zhyBplbAkanBzfn@dirDykeAvocC{fKccs@gtcAv{@kvf@h}iDgpi" +
                "Aptu@gwB{znAuxy@{`G~woBctbDs`vAsu\\xh`Ale~@_mi@|xi@ckR_fo@ey|@htcCmzi@axx@v|BughAygh@jjfAs_b@}mE~_@g" +
                "wwAabb@xkq@}ynAuc^`u|Ap|v@spRzj[}d|Cq~CkqVsy_A_dAh{yA{xyAbpT~t[achFex~A`m~@df|@zybByas@fqrAmwTivdBei" +
                "^tacAulo@ui~@s_lAxh]eeHlffCgvk@cgCjmc@|rkB~`m@gnTcxk@d|t@_qiBcvwCyrv@~wZe`TgopDmzeAgef@nhGcyXb}uBfae" +
                "@np^pzgAojKuarA{zaAakl@jirCdoTcgaCmop@szpAdcZwkDwszCoyh@pybB_pYqyFohbB_qlCmw]idBshs@rltB}{gBems@mc{@" +
                "foNcov@ib}@migAvqPuc^ifi@uep@vrZjnXqneAwpnAb_PmaMbl~@a`oAixaBnld@vwj@eja@hdoAd~r@`mw@el@zsiAa__CpwaA" +
                "gr`F}qx@s~`@w{q@uhmBs|b@}sjC|jx@gecFtwZi_a@eevAeysHgsrBur~A}cmA{xtD}cj@iccBmbaAo{kBhjNeatA_xw@cxkKhc" +
                "q@oa~DsxkAiglC~vf@}cjBa_`AuaoKamhBwvzOatp@is{@lgf@wmnAmbr@gwgG{tn@{n{Q|ot@awjCzn}DcyjAlce@etnJbtxTo_" +
                "wCf`aDsnuC`muAka_Bez\\w__GzmtDaplAjeLmjhApsoAoshOro{Ei}gJlwoFgbjCd`_FojqAuxq@qq{DxxwAi_tAulSoocEqljF" +
                "kw}B{}x@g}bBr|Tf~|AphOa`e@pyNx|cA~hu@gadB|lcCyvp@unf@{bfDduZck_BghvAbzE{x`@qgp@l`f@ugeB{dtAw|yBjfGgi" +
                "qA{cgF}opAbqWq}j@}kl@lsMmei@{ypBn{AggeAi~vCwwhFw{nCl|B|mc@ah_@tyA`fU`tNkjs@rv^{kbBywl@cg~Cpmo@enn@eu" +
                "v@smlA~~i@u{lA}sRwbaHzrlEyn~@_su@dkp@mniAg`fAdeaAiu@npy@rj\\naAovoBfoiBijMn~}ArdoAzi{@fpiAjkiCjljCmm" +
                "vAztu@p}aDawcClsi@dqt@j}f@k_cBduxAs_c@j|xDvap@x_f@u}rBfknAohGr|b@dwy@}xa@moMvd|@izaC`yX}spAf~cDat_Al" +
                "`Yw|aAjudBbgqAqecAvwi@jfd@auy@v~iB_bkA`|j@iabAqkc@eer@fxn@yhd@mx^unaJlmvJmhZmbOnfQqco@sumAzk\\_`Hzn~" +
                "@b_l@tzg@s_Uvi`Ct`Re|`@e`kChe_K{lP~lnDcd_MdihQl|r@sygA{ylAxrnD~hZpoVxgL_gj@`}kBlgmImo|@r}qFo|mBlwcEw" +
                "_aC|ivKohsCbdpEclfAbmhHggaBx}zAu||AtkgEyeaCndiBq~nA|qc@axd@}|nAqzk@v}o@is{@cnt@uqgAipD}b`Bt_uAg{{Bvz" +
                "Z_{sFbk~EujrB~~`DbzTqlm@{eX{~AypWjxtAqczA|j_AryAcxk@w~zAvunCxfJtdn@clp@_xZzqRxqpAk_mAjuV__j@{i{@g|u@" +
                "hd^y`yCltiFuwhBrdIkaS|orBijaBxblBa{fHjumEcx|CltgAckjAgmKqp_@vsoBckh@ppY|yHzckAoykAtdxCtusI{hz@nhqIgq" +
                "vI~ysBcvYzaz@eanAv_dD}bzAv`Rg{^ajy@`vQlr`@{`k@jgrD_iu@fbsDecuBzweBojD`an@k_x@gtn@klSnygDwmcD~p}@xrM`" +
                "|r@|ubBaziCxrdAmfpFr}lIacnCyOue|Bb`{@icgAzt|Bu{eAbkY||j@`nuAeeeEpmoG_wYwifCfpe@idl@mpq@hke@c`_Bsmi@_" +
                "wsD`rlD}`nAhznCmskE`zjAsqsC~dtBs{v@oaGie_BrkuAm|xDx}mAsirAxvvBagC`m_A_lt@luQg{lBnt`Le}hB~xAaakFl}lF_" +
                "rdBitL{qdAzvqBmm`AzjSa{p@cnIhm}@ighAqifBlrn@unHwayCujPbphD~d}@z~Wwt^~f|Awrg@muP{xiC`{yCiqhDtvXoisBtg" +
                "eBuqsE{qv@qigGhjzA{sjDgjkAutlNkc^`zKmcuCmqW|leDqiiAmzb@yqf@dsj@_sRots@`t@l{x@omuGzmnBhln@}exJxaq@iyV" +
                "jreB`u|AocmB_{tB`kyBtxGinGd}o@hre@n{e@g`@kfmA{kk@wjt@wy{B{yTyatAdcqA{pJwj_@qcq@bmHwgjAbe~Beap@w}|@tv" +
                "IjtlAku`A{lPxgv@d_bAyyYjrpAcjf@nsG`f\\oga@wnQ_zl@izIr_x@aitAvb@|kiAdar@ef_@jolBc`yA|edA_swAeme@z_eAh" +
                "ze@jgBpppAat\\~hKpub@d|RgcElnwAirP~}cAm{U_ciBp~CbevBez]mhZyzi@~zZd~c@nohBwkv@x`~BqfxAsiw@_sQkfmCuWjl" +
                "}Bb{k@jm_Aoee@nob@mcdB{wIag_@{xdArux@{klCcplAdw|AudjA{gc@nprB~i`D|iyAnis@kjgA`{p@gmjAuopArqb@ru_Ac~i" +
                "Bcsi@tqOp{{@ao|@|d^wvkA|i}Bmk`@e||@pj[|}Hzqv@e~}Dgtu@d`qCypd@xePcvTcfl@~fBhmrAnfrBb`uB}g{A`uuCa_oAs_" +
                "x@q{QaopAlpHxnxAoxm@vqbAuljEezhDk}Qxxl@hbaBfnp@mhaDeqCphrBtfAhgjBhm`BaoJdj|@yjcA~ue@ei^{oy@kl|BzbiAq" +
                "~WipQ`ih@jwqC`~}@fl^u`Bh~`@wzb@hhPylnA}_fAwbH_cx@swh@rdzBw`{Bbo|BgvUzf|BeyzAzub@lzMazfBebs@ntpAqvGkq" +
                "aA`pExbfBqok@|h{@mbvAsc]nuv@nz_Ascj@nxmByq{DdwqB`li@taZxxyDunoAuc]xt|C}hqAvl[_|Muii@mi\\~e~@jev@rxM{" +
                "|p@~rvChx[nbJffqAuyaErwg@bsiBaasDtpsJsqeA~wtFoj`@qyq@s{p@sCj|aA{`k@yxg@_{Ks}Amml@yra@|quAn{y@j``Egod" +
                "@~``Ec~h@vAxz[|`r@}}FlorLkhxY?",
            "me}`I`|vkNmbz@hk~Fmm]{noDzpxAm{mA",
            "_rkbKlhizMvgm@}dbAfhVt_oAil{@rasBucHk|_C",
            "wvf_K`vnsNd~y@tbUrkuAbeoDjuHbldCayr@nuh@es|A{tgB}rHqvkG",
            "gx|{JdeodNxak@akt@vwhBpnlAc}`@vnsBwneBqqn@ulLu_|A",
            "_cahKnlbrNhyk@kwSbb]h|i@qjMotmE|fw@szmBny}@defCwfk@vfuG__j@`kPa`l@jikCxtdD~tyGt_d@fksCclpB|nhArpSh`r" +
                "GqjFjgBios@kcr@_}l@qxcCskr@rvS",
            "{mlvInbx`NfliAhzm@k{~@nh@v{`Adc|@xgLdts@{x}@c~i@hmi@~oyAmxyBohjB|feA~bNgbqAopr@zh`Aax`A",
            "ade}JvetbMqlQrgyBplQsgyB",
            "cs|aK|a_sM}}d@veeCshQccl@pgw@saxA",
            "coy|J|{sjKz|L_gnAdzNd{pAsdI|gVmrRc|X",
            "wxtnJd|m_LmlM~dYkho@ick@b~Tab~@tvg@j`pA",
            "qpw|JruhlLoo~@bnkDzjZizvCrcc@yrS",
            "{ppuJzrujKqjv@|atBknAon|BloLmmVnik@~y^",
            "gvpyHbxnqI|sg@fxnBdsx@kcl@zhgE~auD~~kAppPm}`Bip|Bxca@gpBykGuq_C`bfAzm{B}}Hyxs@zri@fni@`mNqepCilYmiUl" +
                "vrAtcWknvAqeeDzse@gpIxo@a{`Drfb@m~Gl`dA~xqBbyXizwA~cr@runA_bn@{gsEjnl@|bTrsiAninCl^}dl@vmk@~_k@hbZuj" +
                "d@uwyAsn|CnjtBviz@ggq@gtjAb~i@wcX~phDvgpAzgGbqdBq`bBfn@d{r@hqoBwjlBki~@w|pArzaAt`xAxzx@a~ZywAzs^|viA" +
                "rr|AftxAloF~i{Akf\\~oXap}Bkr|E|UprpB`ge@h~g@_jFpsjBknP_yq@{hk@kx@vsp@h}qDuk_@bfpHf{QdgsDsny@zyN_}qBq" +
                "kdEkbFbqbDsuc@ws~@l~[knWg~}A_b|@lyQauoAsen@i`Amt]bql@wdS}lqAwdh@ziYqz~F}zlDo{kBuidE~eEyumB",
            "_cahK~peuFzxa@zruAo}Mlb{Cfp_@gc{DrknAcdLjhh@ri`BvgwAvfaAiu[jsxC`dm@gnhB|}l@trt@phBduhEns\\e`yChepAb|" +
                "_@zux@ogh@lhZjx{AhpRcnm@d_eDnegAvrn@`{~@__MhrjDh~f@uriC~i_AarP|~Xroe@q_Rd_{Bxq_@_`y@vlG|po@q|S~{aBip" +
                "cAsyc@pdq@v}jAgkc@hrtCse`@wfAy}w@}ivB~{i@ryxBoj`@dbaC}k^trQghuAgat@znmAnccExeHtc~Fesk@sdoAuj@viwBstb" +
                "@zcGwqPzm_Bc`|@ttfAqsy@`yPk_d@gvjB|yNdhzCkvl@mvL}}m@`qtC{qo@e_Cs_~@awaBhnj@`rsBse_DfuqE{`fArjN_tg@si" +
                "zFv{U|hyFkbTzi_@gae@}ro@xkb@bqyAykb@l__@",
            "hoxaK`z_{I~mq@whc@}mZ~uvAvgt@jf~Dh_{A~dxCxjJ}lo@v}SnhN?xrxM_x~@astA{zdBqadK}q~@cp`Hbs[gagA",
            "}~}bA~ed{AvoSfzVebiApgq@}mj@ybiAiwPznmAw`o@{nmA~wb@|kcDyo\\qeCkfUbtnAkfc@{hOg~l@vohB_wYmxaAmuBzn~@at" +
                "zC{lBzk]iy`Amxe@yp_E|nUnzdEowjB`w~@onYca\\jbFd|`@}h{B~nhAujUhxfAar_@}zjAot}CsqoBorcLuphBczxEhub@o`eA" +
                "nzy@yl\\kzg@|uFngZmlrCcxl@wrfDb_aCxwk@|nj@ovjEox_@ysfCwvnB{bsFkvxA{~bCwb{C",
        ),
    )
}
