// Generated by tools/build_ways.py from tools/ways_content.py: do not edit, run it again.
//
// The ways' lines: © OpenStreetMap contributors, under the Open Database License 1.0
// (https://opendatacommons.org/licenses/odbl/1-0/); this derived data is available under the
// same licence. Land, lakes, rivers and borders: Natural Earth, public domain.
//
// Every path is an encoded polyline (latitude and longitude at 1e-5 degrees; the line also
// carries the metres along the way at each point), decoded by [Polyline].
package com.callbackdev.passo.core.domain.ways

import com.callbackdev.passo.core.model.WayId

internal object WayData {
    fun source(id: WayId): WaySource = when (id) {
        WayId.VIA_DEGLI_DEI -> viaDegliDei()
        WayId.VIA_DI_FRANCESCO -> viaDiFrancesco()
        WayId.CAMINO_FRANCES -> caminoFrances()
        WayId.VIA_FRANCIGENA -> viaFrancigena()
    }

    private fun viaDegliDei() = WaySource(
        id = WayId.VIA_DEGLI_DEI,
        lengthMeters = 123182,
        stops = listOf(
            WayStop("bologna", 0, 44.49129, 11.34174, stage = true),
            WayStop("san_luca", 4358, 44.47943, 11.29799, stage = false),
            WayStop("badolo", 22053, 44.36674, 11.29072, stage = true),
            WayStop("monzuno", 39221, 44.27867, 11.27051, stage = true),
            WayStop("madonna_dei_fornelli", 49372, 44.20274, 11.25992, stage = true),
            WayStop("passo_della_futa", 65288, 44.09180, 11.28267, stage = true),
            WayStop("san_piero_a_sieve", 86855, 43.96289, 11.32404, stage = true),
            WayStop("bivigliano", 101612, 43.90104, 11.32675, stage = true),
            WayStop("fiesole", 117002, 43.80635, 11.29324, stage = true),
            WayStop("firenze", 123182, 43.76960, 11.25580, stage = true),
        ),
        frame = GeoBox(43.71186, 11.17270, 44.54906, 11.42885),
        line = "qupnG{dfdA??jKiIhD~J{JdApTkP}A~YaU`A~g@s_@xG|h@{a@mF|NgNc@bSaO`CtImIrElDuGbFxVmS`K~O_RjQgD}SjNnQq" +
            "UdC`LkJlAa@wBwAtH_IrBxGgGhCjAeDtJSeLrEbIgJyC`MeLtBtOoM|DsI}J?xPkMaN`AkPe@~HeGfKHyL`GaC{HvUp@kXxn@sRcw@|C" +
            "gGaH`De@_EfLrAaOFxCyCzHvE_LFbBoAzGlGkKf_@bCqd@fYuFy]pAzBoC~FyAmHzG|CkJrUwDqYdLzAoNfNa@qPpPnC}RvJcBoLzN`A" +
            "}PdFw@cGOkEaDbB_@sBdGx@eHvGfGyJbEJ{EbTfJgXnCzGuGhDfBqEvEtLmLp[|Wod@mAvGsFhMj@}N~F{JiLpRjBmU`EzHoIdCh@}C~" +
            "O}KsTjH}MyNbNiHmQpK{@kMtDhB{EfAlEsElFfFgIbGZqHtEzLoLpBXeC|E{DmH`BlBoCk@pBsBtAl@iBMhA_AzGzBmIvOyKgTxD|CmG" +
            "lLWcN_@}IcIhDMgE|PpGkTtFRuG}A}VqRlDeDuFWeIqG|JyJuOcB_O{LpBkSyOdKmBiMzDmEiGrAsHmGtHJ}I`LzEuN~GEaIxDnO{MlG" +
            "dCiIzIeG}LjFaIuJfBmJ{HbXqCg[jCb@eDo@lJmHlClF_GnJiEoMdKW{LhIdFaLxIuY_XbGmGiJx@lHyFmBjHsGh@pH_GkAtJuHlCzBi" +
            "EhEuOiO`I{IkMpCUeDtJ}KyPhBbBuEx@oAgB[kPwNoEcCcGaNk@iPJwC_C|FgEoIoBa@mC_AgNyKmF{B{GhDV_EjDoBuEjFlEaI~Ez@a" +
            "Gx@bM}JzKlK{Pn@pIwG~KjLcQ`Et@gFfGwCiIlAdCkCfZjNs`@bRtRyYv@pBwBQ`J}GhGpRkQiDvWySvFvBkHzA~DiEfJgFgMrAVaBtK" +
            "eVgWxBc@kCnKvB{M`HqCeJzCvDiFdBhRaO~BoJkJjBhG{F`JjCgLdP{@oRdC{C}E`JzAaLvGiBmI~L`CgOdOgEeR~A{BsClENkFvC}Cw" +
            "FdDPkFtHgFuKlAbGsFjCxCgEkArFkFhEfHeIdFtC{GtJD_LdNcF_QlAaPuMsAsDsDbHu@kJhErJyJzATuBL`DcD`FQ{FnClB}DuA`TmP" +
            "bDx@aE~EdKuKFzHgG|HjAsJlB~BaD`NmFcQzRvGoV~FkAeHfDmCaFz@uF{EvFqA}GtD`QuOtIvIgNo@nSsO~FtBsHpFuEqI~OvFoS~@q" +
            "@{A~CdFaGrMkEiQHgAkAxH~C_LjEuEeHlAlK_J|JpFyM~FpPwOrGaA{IbEpFcHvHfEiK~ImA{K~G{EoJxLhC}NrNRwPbFhCsGrM}@yOz" +
            "AjAyBdEeBmFdH^kInKgFoNpHa@{I~GXeIxM~F}PvZqBi^jX~Ei\\`Ny@yOfLyE{NnIuNiP|HgCwJbBaDyD|CUqDdW`Sq^bHWmIfCyByD" +
            "dOe@cQ~BeDqEhCjBqDN}ByBfD~EwGCeAw@fGS_IhJeG}MbG~EyIzDvI{IjHsCkJnBtMgLdGKgH`NbFyPpJfIoNrK_BsMhFfGaJ~A}GqG" +
            "xDaAwEdTbMoYhIwFiLvHTaJ|@eEsDpGsBkIrFwKoLvKkBoMhNsIiRnRiGeVrKg@gMbAcEmDjFKmGrRtHoVvGqFaKxB|@{CpNyBsP|DdC" +
            "mFjTbBeWp@pG}FjEqDoGD}BgBjGcM}MzD_AyER{BmBpI_GmLxBMkCvEgIeJNcJgHpGeLcONwH{FdCaL{JlBvA}Cz@zFyEzIlCyKbAaAc" +
            "BeCuFwGj@}E_E`SyHgWxAsFgF~FmCwHn_@zFid@Z`GcFlLlC_OtHfLgNpNzEkQvI}@eKlJbA{KdYwG_]VjCoCf\\qCs`@lIfDoKfBvGg" +
            "GzI`BqKfAcBeCnI}@kK`ElCyFrPkDaThFyJqKzHuD}JrC{FgGQ_CmBtBqFkFc@qCcCjCgDcFImHsFfGwHkKaAgGwFzGaGcKdFcMeMrDc" +
            "BcFhDuPoNdHkL}MnBaPuMbIiOkPpFq[wWCyKyIxGme@w_@nIqFqLvEwKcLXeLgJmEwOkP`CqHaIiAmKuJbBmFeFxEqEyHCgG}EbEmHmI" +
            "fIsAkKlAvDmDdIjEqKtDYmErHcIsL|B|CcElGj@sHfA_A_Bz@wJcIGyJsHtCeB{Df@}BsBlIB_K|GrEmJtPhBsSxDdEeGEhCqB~BhA}C" +
            "fAzHaHlCv@gDd@~CmC`DIqEhGjDgIaAtEyEuAZiBz@pCmCw@`JaHj@hEoDvJqG_NlH}I{L~BEwCzEzDiH~D_@wExOrDkRjDwM{L`FaAe" +
            "HaA_HkG|DkIcJfMiIgRXtBeCjA}@aBi@mJyHnFcGiJsBiDmEpBwK_J`I_FwKbBoDyDlOeHeSpEjFaI~Y`@k^lHtH}LbK|B}LlGiB_IjG" +
            "|I_LjYzEg]nC`C_EfB`KkI}EfEeIi@bEeDn@xCiC|HhFqKnPtSsXlKCgMrNlJyRhIh@sJfXhUu`@|EqDaHzQy@eTdGuHeKfQcCuS~TgI" +
            "}XjK}@{LjYvBq\\dOa@gQnj@cIep@`T|AwVtFwIcKbJ}GqM~MMuOlBmHoGdDdGyGfEd@eFvAkAqBM~GgFrCe@yDx@~KkK`Fl@}FbAmEc" +
            "EhOhE{RZbIkGpFhYiV}ChTgQdG`AmH`FjQwOnC`EaFGlEqD|MhF}Q`E|J{JuAp@sBrBPqChCnTeQyGlFiKCbFwDrDj@mF{A|G}F^pLeJ" +
            "nCvF_GV`[wUzBzH_HhExDsGn@pM{JbTvA}VpTmCiW`I{F{K~@yLiJs@oGgF~AqBqCtFpIyKpMd@mOzC_D}EtEtCoGlEgB_Go@uLoJ~Ma" +
            "FkR`DwOcNeMgYiYyA_MsJqCwCkE~B}IcIgE_C_GvKtA}M|LtLeR~ApOgMdBpBuCtCuAsDtB_IiH`IkCyJ`@}CiCpLiCyNfFmNcNkAiEw" +
            "Df@uMoKkEwJeKrLsHmPbBsIkHI}F}EhEwIiJGwFcFtFdBeH|Bq@}CtKnGcPxBeB_DxEH{FzGvDcJKjJkHlAmEeE`JjIgN|CqAeEpBzDi" +
            "EzCyCwEtD`AsEhBkHqG`Du@{DbBsDwDvLbB}NhA_DyC`KwH}NhBkGuFMqEmDjBiBwCtE}PeO`IgGwLtOs_@o_@tP}KiUnFbBiHpEmH}I" +
            "vTfGcXMkJgHhAhDgD`K~HeOjGVkHfOkIcSrFm@sGx[~Kua@jNiHyQdKyNuQzMsCiPjImHsMvCDkDdHsR_RjIUsJ|FsDcI~G}NqOgBuEm" +
            "EMaHiFbBaEsEbOnCoQfEdDkGvTi@sWfCzEsFxD?oEnKfKkPrj@cA_p@`KcDkM~JxEwMrF\\}GnDnDuFtIl@aK~Gi@kIbOyFgRlCTeD`L" +
            "jSeU~JnHqN~GnY_W`LfMoQbIdBuJpAlFyEt@cA{AtJrHsNnDf@sE`DxMcLbDxBsEnShe@ue@tM`IqQnA`JkHdOdLsTtHtKyMhEdTuQM`" +
            "MkJ~DgB{F`FbEiHbC`G}F\\~CeCgBzFiFcA|OcMaBv@_CdL|IcPr@nEqDgBvSiPyC~DiFkEfAmFcCnFiGjExFyHRjMwJ`EsCgHT`HkFe" +
            "ArCwCxFEwGzJtC_Md\\pb@qj@ZrBeBeApAkBcJmAaLg@pCcCrAlE_EvFbG{IlI|BaKhO|LkThJLwKpEfBuFpKhMgQjE~NwM`pBpoAilC",
        land = listOf(
            "q`bpGubeiAhsnF?isnF?hsnF??tzlIisnF?",
        ),
        lakes = emptyList(),
        rivers = listOf(
            "g{bjGa|phAzs@nwAlpBdg@pfCeJfzAwi@rvIe_C~oEsc@d_CrzBni@?dh@g|Ep~@g|Db`BieD``BkfB",
        ),
        borders = emptyList(),
        locatorFrame = GeoBox(36.30000, 6.30000, 47.40000, 18.80000),
        locatorLand = listOf(
            "uwoxFegxy@luiAwy`@tcl@ju^`bp@qmKzeeDnd[ldD`{MyaNpkj@|zBvlUufG`dQnxt@|oPt|HxsOmtA`nl@uou@z~k@g{t@~uBq" +
                "{m@idIcdDo{BdfB_qLs_Tcl@akJ`cIszBpePoihAwkKcrg@|`Veo\\n{^wbr@guEtaLcdZcWwvg@cnReuo@{~z@epnAjyIetI|`I" +
                "as`@l}X}g^dsOb`KbxHohN",
            "{lgdGiszx@tt[pbDduSy`MbrqAexC~vf@fg\\hio@reDzkx@pvc@uvf@h}hA{|TsnNuzJh~_@g~^kkCwa@~cVqe_@mmNwvKlbUgi" +
                "JzeCuvK_jTqkMrmTgod@sx[mjJ}zR_oIauk@g|L_lQhzByga@glz@gvHhbFspRlha@yiB",
            "}{ghFoha~Az`tA`yaAzu~@njYdeWglBzsP_cUvzE|}Ina]{vVndi@fcb@jq\\bS_lCzv`AwfPfpt@oko@jln@sdJttU|Qjkm@k{E" +
                "nnSiabAtdzBayPf_o@}sChmv@}tMddUaj\\`yPepl@u{TilX_nc@f}[e{_@srHiq[ucH{o@krJocSaFurXbah@_f`ByqJa_r@~rC" +
                "slm@crDcsi@gvValv@bxA{g_Ak~Y{eiAppCspYlfHdjJ",
            "cimwFgiatAoRfxLwjI}TbkCgwPbrE|sC",
            "mbj_FmwphA{pCprT{fKmm@fiCa{MnnKahD",
            "swleGwasdBjhEqouAvfHmnQcbAbdh@thEzwWsmFhc]ahKt|G",
            "c_ffGwe}gBnOvpcBmuPbcz@w_Byh[v_BahYrqFeaGhrHy_`B",
            "qhbgGyjmeBa`Bfrx@caEzbLksLc`DlaFahjAbaFybJ~qGzuS",
            "mvqdGohm~@`i[kvCujHbjOhvBl|f@siLdVajAoel@__F{`F",
            "akmmFe`wr@~hR|eJstLjyJyaNsc@lmHu{T",
            "_rnyFwjqq@r|GdoEwSdeHshW}jUt}BcrC`aKtgJ",
            "k||kGcy}{Ah{Es`Bc}K~jWgqKj}I`sQwg_@",
            "qqoqGaskyA|dCfaWksLrmM_oIfw^wl[kqVdko@wum@",
            "k~dpGowoyArrGo|C}vIbza@ehN}kAvS}lKvwOwaN",
            "kirmG_ou{A~dDv`Dcoa@hxo@_ih@`k`@vxbAwg`BjyAr`I",
            "wqakGypu{AxxCqoAqz@jzKi|q@n{s@`~n@if~@",
            "mskkGefy|AnoMkzK_~JzbXewH`pFteFqxR",
            "ktqoGqulwArqFfo@uqHf{J_}k@p|SkjVwkDcjWvqIg~ByzGh`e@yqYnq{@m`C",
            "oi`dGy_njBjlLusYwqPrcmAjdC}nr@",
            "_yh`H_{vqB~}vbA??~khkAwupC}lDcwFy~]|cOomPniO{tcAwqHkv{@eeWrtEzmEwpk@~rJsfa@xiVg|b@ntCyeV{qZyiqDkne@i" +
                "e}@}m[osiBfcEqk\\t`RrsInzMi`Hi`Hg|KedM~`C~Pyjh@xzGehTxq`@rn@d|_@ek[hkOb~FhuH_gV_sJstSoePakIu|Hgae@ie" +
                "Xgdc@uqA{_Sfwe@ueM`rXtc^zxo@p_`@hjMnl]tjVthX?yqqq@_arc@?_aOhs_@_sKepAh|@raXcefAhnfCmwF|sm@yua@dkhBuc" +
                "Aaaa@~ea@ykaBykeA~`sBclb@dek@in\\jmbBjrClwnAkvYhrG}fp@`juAylr@xf|@epO`hKegEio^hhB_nc@os_Ahs~A{fShyO_" +
                "vr@weAclTtcIiii@rkz@qyFdmm@fxa@h|Mdh~@tys@_JvoSo{s@nel@}}gAt{Tcl[e~r@ca[rg]p@fuLrzJrdQ}~Jlpq@xcYnka@" +
                "|ia@l`gBaf@|wKg`N_iSqG`tGpqRfni@j}f@~nHrkf@oq_@|_MoqXd~VduJ~cHjmNyrEvrSvlT`~Dlk`Bu{[dwk@sqx@rjModi@l" +
                "|l@wyjAllUios@fjkAi~m@rz~A_eg@lwb@us`@zswAendCtcVobz@{`@uizCjmGudf@r`OexC|yIxkFh{Yjkm@|fT~qAb~Mu{T`v" +
                "f@kihBtd`@gvjBzgj@olgAvec@w{|A`pv@w{gAhg\\szXhuUo|Cnjv@`wZiqUj|r@c`bApqh@ivJvszAwnJ~}YegSzdN{aAp`\\j" +
                "yI|bSht}@doq@reu@xgZt{Trq@~eTeyMvyJagk@rre@}tw@vuiAkvJfkNnzMy~Bdv[`xH|ge@tnPhbZltOvgJvuz@rrA~c^zkr@d" +
                "b{@z`k@bP`|_AoqQ|jNgqZ`Pe~OadJg}FozVggb@cbOcnXt`DihJgkHm~FyzGmbHsyj@wob@kqA_dOz_Scl_AtjOsi{Bzr_AofKp" +
                "_TmjBlww@e_`@xbbA_xLbgCogLmcJa}PloF_k^tbTeoFllMzqLbdrAwjXypVskOzr\\lAltr@yiJwS}uq@huc@ksSxtWrTj{a@ia" +
                "Jjc{@jxGx{]qe_@pwm@{{Jvsi@}_{AhokBgqZrks@ocg@xc`@koYhraAvoEfh]}eDllF}xFu|NajNfiBgwf@j|k@{xKthYexX~nQ" +
                "_bEvxd@wcm@gd@cu_@vhM{uZ`yWczsArzX{cMtlZozN~z|@}qi@jfuAecSbgeB`{Mtwh@rtzApyiBdhb@repCt~}@vliBtaa@zq[" +
                "|cKzws@ws_Y?",
        ),
        locatorLine = "qupnG{dfdAdxAnaJtgY}tBvg_@d|HrqNqvBx|DovJlaRdYx~B|lGnvOmkKvhQvaQ",
    )

    private fun viaDiFrancesco() = WaySource(
        id = WayId.VIA_DI_FRANCESCO,
        lengthMeters = 434435,
        stops = listOf(
            WayStop("la_verna", 0, 43.70713, 11.93340, stage = true),
            WayStop("pieve_santo_stefano", 14503, 43.66994, 12.04023, stage = true),
            WayStop("sansepolcro", 48587, 43.57210, 12.13906, stage = true),
            WayStop("citta_di_castello", 80766, 43.45728, 12.24036, stage = true),
            WayStop("pietralunga", 109753, 43.44214, 12.43505, stage = true),
            WayStop("gubbio", 136254, 43.35058, 12.57645, stage = true),
            WayStop("valfabbrica", 174202, 43.15884, 12.60123, stage = true),
            WayStop("assisi", 188538, 43.06947, 12.61694, stage = true),
            WayStop("spello", 200498, 42.98949, 12.67199, stage = true),
            WayStop("foligno", 206837, 42.95611, 12.70342, stage = true),
            WayStop("trevi", 219480, 42.87659, 12.74795, stage = true),
            WayStop("spoleto", 247292, 42.73454, 12.73862, stage = true),
            WayStop("arrone", 278051, 42.58393, 12.76811, stage = true),
            WayStop("piediluco", 290865, 42.53570, 12.75455, stage = true),
            WayStop("poggio_bustone", 311416, 42.50322, 12.88627, stage = true),
            WayStop("rieti", 329164, 42.40463, 12.85677, stage = true),
            WayStop("poggio_san_lorenzo", 351303, 42.25213, 12.84378, stage = true),
            WayStop("ponticelli", 373033, 42.17688, 12.80072, stage = true),
            WayStop("montelibretti", 384264, 42.13306, 12.73181, stage = true),
            WayStop("monterotondo", 401169, 42.05031, 12.62239, stage = true),
            WayStop("monte_sacro", 418601, 41.93977, 12.53591, stage = true),
            WayStop("roma_san_pietro", 434435, 41.90224, 12.45748, stage = true),
        ),
        frame = GeoBox(41.75655, 11.73479, 43.86916, 13.10390),
        line = "qpwiGwvygA?iKwh@qg@{^oQ{f@}FeyA}nAwHl@kLaGyNqOx@uc@c]gFqQyPl@ySePiSkJwYmFgMqMtJmu@mq@rY}e@ak@`IHy" +
            "Jb^whA{eAfNaR{UvA_OgLha@cr@_y@wCmRgP|FkOsPnc@cJck@t}@ya@qlAxFrWqUnH~GsLt_@ib@_o@`NdEiQtB_[cVhPod@{f@~SgI" +
            "eXg@cK}IaMbDiOwH{FoLhCoCaFwK_DuP`N}]g`@kF{BkHaF{RgQ_@ye@sa@}CgFaJzCiXkT{M{TyXhSoVub@a@sk@yd@pCuJ}I_L_RqT" +
            "oVi@iZyC_K{JdEub@m^oJnAaMic@ev@a}@jDui@id@`NoXc[q@aZaX~EeBwGoAyFqIbZih@sn@`[e@cb@vFqOsPmD}XoUtDmK_Nb@e`@" +
            "k\\vf@aFqm@k@{MsKlIT_KlEkT{TfEpC}HhXoXad@jE|BeHfKqQeTnLtB}NhFx]{Yw@yXmT|Oq`@wa@dLuMiR|G~FcMzK}EsN~YkZkd@" +
            "uCiJ_K~f@us@ybAlCg[g[lE~OySjKGyMuDxJcLn[mFeb@rOqPyVXiHyFlFpDwHrTsXw_@hOuEoSfHyYqWc@{N}KjF|AqHhRe\\y`@`Jp" +
            "GwMNdS_PpJwB_MlLdTsXzMgReZqBgN_LfOdBuSrClIcI|]xBwd@rBxF{GW{MiK`IuNqRdJbb@sc@eFdTy_@lJ`Z{[`Dzp@ei@uCxHuIh" +
            "PrNgV~iArE}sA~MjJ_RpSdd@ye@r@~^{XpEfOgNiJnOqQnF|H}Jg[zz@_z@ra@toAqkAdVbPu\\hL|R{TtSal@uj@hRLsV`P`TcYda@n" +
            "Rmh@rgAx}@e_BfW}X}a@r|@hn@gnAnDmGiH`RbN{ZvTeQq\\hPo@cShEwMaO~`@jBye@nEj[cZjUqs@gs@lLsMkRjEcUoRqBqE_F|DLc" +
            "GqCiO_OhP}IsTbI{ZoY|d@{Nck@xBeYyW~Pq@{T{Aoi@gb@tE~B_HzDsHgIpEg\\_Y`JnFqNrSaYya@qKwn@wh@aPwNkVmCi\\yYpb@o" +
            "M{l@VgL_KdGxDuJlGuHuLkAsHiGj`@oVuj@mCkSkRpC_FmGaf@s_@ws@tDue@we@mHw@yNgKa[a[lJ{XkWnWj`@gh@`LyN{S_AzUcSjO" +
            "bF{TtCnJsK|Gwh@wj@dMoDsPdHeQ{QbQrBqUlCcE_FoGuMcPxAuo@ci@~LiUwWhHeA{IdCoQiOnZkb@ui@rJmg@}f@gCsToQsJ{ByMsI" +
            "nGcMh@sPiPwGsEeJyPjAmU{FyTkTdh@e`@gt@iDyWkU|y@oG{aA|i@}e@kz@}@gi@_b@al@avAawAsL{FkQe[slB}~AgZ_d@aj@tP_Q{" +
            "X}Ge@sKrBuEuGuF]aHrD}AmF_G?eHpEiCeIqYcj@cn@hAwGkHgIaQqQjMyVqYsIuRmSlMoM{SwJaJeP~Bkf@ga@nd@ym@ex@wDAkHzAg" +
            "FaFb^mCkc@aMa_@o^lAgKkIvGs@aI~DpGgIbD}DsGxKdMyQtCsJeJfJwCqLyB}O{NvEaWaVlNcGiSmNoS{XdOsMwTda@~Hcf@tc@t_@i" +
            "q@|K_b@m`@kJwMmRPcKyHzMwQoVZiT{PxIaAwK?cLqKnF{GoJyEaSuQ{KwBcNuLyOgWlDsG}HoJyZ}ZhEwOcOyLoAaQxMiHaTqPiFcTp" +
            "CiJuK}QwDaUkJoSoT_YaPe`@uUkfAkbAnC}I}IyNsL}STyQkOg_@_Gwd@zJcTmYlKwC{N|AgX}SiCm@}CdGgA{KiJ}y@sq@fCqYkWgOg" +
            "r@{l@hJkBsLpFlKeNnDyDiGxFnDiIzWwCq^zImVmXzWmIc]yBcLaLxJgEgMvCrHwH~EUaGgBgt@yn@wFqVcV}BpCuFoIaL_OjDl@}EuD" +
            "sGuHxDucAoz@wPiO}]sHbPkTz@mTiRjIyV}ZsAcUqQhXwC_]z[dWcf@~A_KoJdIvB}KRxL{JfWdEs]~EvHeJsEvJ{MhF|DsH~@xYqUzM" +
            "nJwSjKiCwMrOnTyX|CcLyLxRaIcWhc@`N{j@lWwO}]|Jae@wb@`OgO_VvDvDaI|OcMgUpYod@ik@mBaK}JnTqb@_e@`b@gb@sp@jFvGa" +
            "MrEoO}Oda@q`@on@|ToJyYjQ}TeZrF}ScRrGxHoKri@ar@a~@vCcMsK{Go}@yr@lBif@u_@gFqV}T^gl@_e@nNcS_WkFmEwH|A_OmLwF" +
            "qGaJ~_@kp@}x@hPtIiTdHdOsPzfEvKc~EdMSyNhc@gTal@jKzAaMlDoJqJhEhKwK`BkF}G|[hBu`@~]xMwc@vc@gNcj@vQbU_[jp@jX_" +
            "{@rI`YaYpHuF_MvMm^u^hUeFyXxIwJ{NnUpQ_`@`d@_Awi@O{SyQbHuDwJo@kLiJ|KUsNsB_FuGdGmDcMlc@vn@ay@nf@w~@ydAyCBcE" +
            "b@_IkGdP{@_T`BxGwGjKyOuT{E`c@w_@tLsOgU`@fEsDlI?aKYtHaG~EvFoI`V@{YnQgJgVuDj_@o]nFmGmJpOvSg^``@zJef@~HoHmN" +
            "cDmy@cr@pD_K}KbFzE_IYnKqKxM~C}PcG|b@w`@`ExJmL`MyMmTdY{Fu^xNeTkYhHbMkS_B|PuPyDzBqFn@|VgUdYeKq`@jLiQqTGcQk" +
            "NxIwCwKG`LiJ~@}EoEbHhB_JdLpi@eg@pHoDyJNmN_L`F]kGlEvJuK}E|MmPbZk@w^e@cu@gq@vNvAcQjF_J{LiBs^kYsBqFgFuLHmQe" +
            "Nyk@ai@mNrJsYjAmK{ImAaFkE{@pF{EY_IkGhSsd@ie@fHt@uIf`@zd@_r@d\\`Ci`@jIrJiNpUfAqZxLlKmQvTos@mq@`MmIaRhb@mq" +
            "@ix@|\\kW_g@jF`MaNdSLkWbElIiJfViJw]hw@rHseAjPbTu[pNy_@ka@bAgT_Q|R_@wVxEvFgIlGwDsIpI|IyMlGeCeI|JbGeNhGkHg" +
            "KWcIyGvLc@}OhDpLcLli@`Buq@|H~E}K|LiJiS`LxBoNjIoEeLxYzZgg@j]bEma@vOyF_StLpBsOoUw_@eg@~g@xUuq@jLh`@}`@hRkq" +
            "@mn@j[i\\cg@rEq^c[zNqGiR`Mce@mb@|Wm_@cf@`CyMeLnj@{Qos@|b@{i@su@l`Awo@osAjWc[ub@{@~IkInMvDmPUrJ_IxH_QwRjO" +
            "bTgZvUyAyZtJaOaSf\\vAy`@|h@oYyr@t^cGyc@tJwK}OnHa[uYj\\jBcd@`[mFyb@kHeHqNm@ab@m\\`Rc|AunAtp@dRyx@jX~V_b@b" +
            "EiJ}JzLlFcPfq@y}@gkAzl@c^sy@xnCc|Bw`ETo\\mX`MaJwQpHg\\u]|Ecw@an@jTrAoWpI`J_NvEcHsIbWcEkZ~GxG_LzIs@oKjK`M" +
            "oQje@fL{l@rP}NwVhKy@eN`EoVqTtGgGkLhT}EsWxQfL_Y~O_CcScKia@g^zC_CiEb[|Lqa@`ReBeUfFfEoIfFuNiOla@zVgl@bG_WyU" +
            "h]qEma@pWrJk\\vQc^aa@fHfE}JnJsb@cc@xOoF{SbDmLiLjLdBuSdMcIiQbc@hDqh@bF_JoKvI~DoPy@vLwMfEa@qFnAuU_RwIcVeVx" +
            "YmBc`@lMyq@sl@vIxAuK|HoHuLqBiX}UpDs[cXbQdKiWdSyKaYl]hL}e@`Na`@wb@xc@jPwl@UgHoGf[rYaf@vDgg@ia@~C`LuKvHyAs" +
            "K|DzEwGzD~IgJ{@jKwLjq@`Zy|@vHoG}MlDmRkPnCqk@ad@dWi]cd@tw@qDsgAtM}NyTnMUgO_@dP{NwR~Xcb@|LrJwQ_FtDkIdL|WuY" +
            "jKAmMnNlTuWLdj@ac@`IiNePlI\\iM~GfRqSnKyCkP`_@xEyd@r@tZcVfGbLgMrCt[kWbg@v|AmzAfAtSwPh\\fXse@nHsFsLtF|FgJR" +
            "mGuG|JjD{MhGzQkQtI}@aKrIlKcO~IiDgLzBpFsF~J{MeRiEaJyJ~GkMeSxMvEaRdIaDkMnW{Rct@iE_J_R~FuN_RnL`JaQpGy@wHfG_" +
            "FgJx@}JcIbRuOuXgJwPoVlJuL_RsC}XcV`c@ci@wt@j\\_Qoc@Xi_@}_@bT{HkZbVbAmZvCpFcHpEqEgHoD?yEhBgEyH~KgCsN~I|LkW" +
            "pByHkHdQ{FuWt@iOsLvMyRyXfGbGyJtCyG_HrNmA}QyJaBcNvOeCaRcTaAwXtAgGkGaJm]ua@gEjKiMpA|OsN_HiEmLw@`EsD`@sQk\\" +
            "aDcA{EbTuw@_v@kCat@gl@tKuc@o`@zc@}Hoi@~T_Tk^~EuNmNzTl@{Wfs@oVg~@|ZjAm`@f]lMwc@rL{BsNrg@nHgp@zFbI_LStSkPl" +
            "KpSqU`@pX{ThM|NeTpIfa@i^l\\~d@cm@pb@hWgl@bQbAkS`[dRgc@hFaCiHpA|O_OpPl\\k^`i@v]qu@`ZfCy]nHpVwUhQnQq\\dl@d" +
            "G{s@`UhZib@nHQuKrE~MyM|QmLkXdJpGwMdO~RuXl@hR}NeHzMkOxChLoKiCtFaGpMvoA{cAde@|Kal@xIwHmM~Xxd@{i@vNjA}PxEf[" +
            "m[fb@r_@gq@hElR}PnL\\gZzHrXaXbI_FmLdLbBgOt\\iS}d@nOws@gn@lb@ag@sr@l@yXyTkMqUiX_PwI}SqNA_RhCyXsVyGw]{ZdJs" +
            "HuPfQ|LqVbOf@iQzHgbBkyAxHaH{MiDgMgNqHbFaMzEw_Ayv@pV{eAw_AvMKuOpWmYeb@EeNoMkGdIyLoA}DiFvDkW_T`YgT{a@`Kia@" +
            "c_@_A{XwTkMiSsVmLge@kd@rKcl@ah@iDqs@wl@oIyIkNi@uZkX_d@yc@gs@{KfB_O{CoEsFdD}WaVuJaiAybAfb@jbAifAqAeQaOlXy" +
            "@w_@~CgHqHrHhQiSnLgXeZwA{VkScOsZi]cNuHaUne@nGwl@d_@~d@wq@fH{K{MrCsOuMyB{HsHdEyJgK~e@st@u}@nKcDwMv@kN{KoF" +
            "uRiQfLpQiTm@aH_IjFbDoHWiRcQ`UzYqc@bQnFgT|\\qKkb@dR|EaWbNkPeUpZyD{^rVcW_b@pNdGiSfJqMuQnPc@mTbFw[w[}CeJuJn" +
            "KgMgb@`PnL{UIrO}LdRrYu^vTcBaXzLpHmPz[ln@gs@tCln@ag@`CiAcD|LdXs[nn@dPux@s@_UoRjBrNmMzFoG}K|FlFsKbFmBsHq@f" +
            "LsKjN~PiVtYoTkc@hIr[kZj`@uCih@pO`O{UzY~Ey]xDt{@as@bfAoAsoArAiXkUzPXgSdCqOiQb`@kHif@tH~JaOba@vHif@x@dQ{Oz" +
            "KpA{MttAeL}`BlOkNqXbh@{Amm@`o@fWmy@tE~XcX|ItGuMbXuF{[sBiIqHpI}CsK~WiGw\\~PbEmT@oJiI|}@qOggA`UwM_[dpAcRg{" +
            "Ajg@_V_q@~f@jDkm@hBtHiIdTo@uWdY~`@yi@eCpJyInUyUc_@tMvAmPlUhRg]i@xGiGbJu@{KpTrLuYxYxYoe@jZmCya@xO}R}ZtGq_" +
            "@_\\~Tbd@wf@tOdGySxQbn@cl@{HsCwKt@lGgFhS|KiXxKfUmVZuGaG~CbEwFJgEcDwDwHyI|JhDeMXwKqJhDhFqGxYfAw]eAuPeNvDs" +
            "E_HeFsFiIbDsHwKxBrGmIrSoDkYePui@mi@f`@rLsl@jf@sbA}hADjE}ErDwIaJxFj@eHbQ_\\yb@rTIcZz}@miAo`Bbh@w`@ov@vX`j" +
            "AoeAzFzAoS`EyVgVjF~HuMj@xOoMxOzLiVqG`LsOyBn\\mXdSlBwU`CpFmG|Hfu@qp@}CxRqQlChM{Kd]`Bie@tHzSwT~NwDeRyAzHgH" +
            "nJmN}QjPvOwW_@p{@eu@e\\|pA}nA~Mn]y]n\\`Mib@bPzUoZoDjJeKnEfKwKsEhe@yd@kKhMoRnB|SyP|TfVk_@b[x{@s|@vAdHyGqM" +
            "bQyVdJhMgSeBjFqF~`@zYcm@xPxm@yk@mAhNmLpD|SuRzDpA{EqClRaP_EdBeFbB|OkNiGvMoOTln@wg@cKPwMjXnr@sr@zF`k@uf@lR" +
            "_DoUpp@nV_|@xEcHaJ~W_Bi[nb@w^_o@tIVwKd`@cXol@pKrZ}YrAfWaUbZz@{^qF`YaXxOph@of@pSzToa@qB~]m[qIpUeUbKlDiMpI" +
            "fRsShW`Eo[vQtY}]vG`c@a_@vY|g@qm@jqAdz@ugBzRlI}V|EwDgIrEzm@qf@`YuDw]nq@~c@i`AndBnn@ewBdMd]ia@oFddAu|@vHdF" +
            "cLlPbe@kd@lVtJy_@uOpVcm@~`@jToi@oHpIoNfGfEoIzf@Fml@np@no@weAoLdk@gk@f_@xEic@le@`]wp@XhIyGcLfV{WdBxX_UfY_" +
            "He]|_@tFme@pFcMuOjJvBqLdu@ps@{iA|d@hTem@dNuBiPrLkYs[tWx\\wd@bJpf@{b@j~@tiBwpBjcCvp@uyCljAnq@a}AhSlFoVrOq" +
            "DqTjHvWoV}Nr]__@bG~EaJtIwBsKdBdH}GaIpOwP^`JkHcRnCcUqT|l@ml@i@bH{HhIbKiNpI_AgMLwIiKfIzOuSjFCsGeZbq@ss@y@b" +
            "ReOxe@|Mmn@hUb~@o{@nLdSmXs@p[qXqHpGuLlE~g@_d@ol@`Uow@t]jc@mq@t\\nGoa@jS}N}YvSgq@op@fh@yBsm@~r@aUo|@bHzDq" +
            "JfFtQoPzAdlAq_A",
        land = listOf(
            "qfwmG_ytwAlu{Q?mu{Q??p{nLxpAsk@jqBggBlaG{q@diF_sBvmDecCjiD}hDptDi~FbhDu`CzyC}gE~bCybF`p@{fDzyIadJhgC" +
                "swDt}CwsH|cAi}Gh^cjHzr@_vB|oCssF`yBa`L|pB_rBb~d@mwz@phIkyUrc@azB|v@q|@piAmdHdhAkfDuY_|@_fBwcCjEghAlw" +
                "@q]fz@yiCvlEgaDhm@q{@bT_vBlw@kmBbrA}v@dbBhn@jgs@u~ZbiDc|BvtGs`AtuAwiAl}HmgE~|EmuAtnOygBlyg@knNlgLy~E" +
                "rfEu`C`kMqbKnaDyjAbcXkj[tdGwlKv{EcaMb|ByaEd_ImcGfkMmsRj`_E??l~yEqzDblOqD`pFviAbyNzb@jnBnqAxdD?|uXs|K" +
                "fsH}oHzzIayBf|DwwAhcEo]t_Ci`@hdQ{tEltLao@rxCnm@dgAzaAxk@ugAbbBgrOjlMm|Ox`RyvNhrV{d@xdDa|@t`Buw@j~Gay" +
                "Ab`BalBzr@aqJ|v@oeIh`FitC|lCq`K~eTao@lw@yoA|Uql@`c@aS~oDsTp|@{kCrwDu`Bx~EdHdaNdMhkAchEzoBepBtaBkq@lu" +
                "A}tAzo@ifChgCa_GlvAigOvpIciDptCkqLrgVs`AfvHkiDxkLuf@`xCim@?ug@`yB_AhhCti@gm@g@ptDs}BjmMmGxdErSvcBpp@" +
                "dj@|_BjT|cBpzAjpAfNaRnx@?`}@`Rzu@{nBxdCgk@lmDwfAxjAs`Bho@kdAc@wrAekA{TyuAfn@_sDmEyjCegB{_BqsCwu@m|F|" +
                "Hu}CdaCknBhn@jd@dyD_vAhnAeyE~rBkc@ffBayBhRq{A`wCmaCpiHwgGdaBa|@jmBmnCprDuaCphIi|Fld^a{AquCucBoz@mdGs" +
                "CcmBgjA}rAn\\i~@~y@wj@znAosChpL_z@tpHsFvrHbaAdsGvxAym@fz@~mDc~A~uBwtHhhC{_Be|CuqB_yA{yIihCyiAhTwcC?w" +
                "eC{U{oAgl@ajBjr@obClWy~FrHm_Cn\\iuZtxPk~MveNmgA~kEmaB|w@_kDzq@uecD?",
            "_godGavv~@xlBhkAfhA~AfhAsd@hhBvh@rdA~{@pm@lrAha@|oB|e@qvB~eBijBvsBsa@rqAr}Auw@n[q@zmBeZfiAkiDxiB{|Ax" +
                "cD?joApgCteA{s@~[spM?y@{mBxyAn\\xb@saAXazAoMyl@oy@iTa|AopCw~CcbA{bAyo@g[ylAvNq{@|f@}v@xuBilA",
            "{suaG_boaArfAcmBbhCquArnAaMz|@w~@piAteByg@zxA}rDxgFmkAt|@_r@{yAelAlBq`@yk@ba@ioA",
            "eenaGyn|}@jo@wi@hhBxOuD|X",
            "yp}`Ge{wbAdLqc@bs@gKwMlYzDrc@ffBmXia@feAet@jWks@wNyRubA",
        ),
        lakes = listOf(
            "sbgcG{fbhAhzBulC~l@?flAng@puFaJxgBt{@jt@heCaJtlCit@lcC}nEbtHssA`cAa|B{KsvBouAeaA{rBccAi}HrsAogE",
        ),
        rivers = listOf(
            "g{bjGa|phAzs@nwAlpBdg@pfCeJzqL}iD~oEsc@d_CrzBni@?dh@g|Ep~@g|Db`BieDdnCqwCzxCmt@f\\a}A`lAqvCldAecAd|D" +
                "{nBtqAbEim@ti@v_KowAfwAuf@lqB{}GfLs`BveCnZ~uAowA`wBcpFr~M}cHrnBebBtnCmqA`~@ayBbbAfMtaBtdAd_C?nvAu~B|" +
                "u@`_@d{Eh_Ffk@q`@zo@?jpAfkAti@}tApzA~uAzr@zT|dA}U~[zoAlw@xm@vi@wi@|~BntAju@cb@x|@`B~cBviAre@?hkAwl@t" +
                "eAzUjlBznB``AwcCfj@ip@baAcb@`a@veBtGlqBre@?dt@iq@pnAyfCfwAa^nKb~Avn@|oBvjErnH~^lrApl@vzErtEh_G?dxEzo" +
                "Ba_@jmByo@lsAscAp`@axAts@o]vzFui@brAtKj{BmtA_BylAb{I}t@|~Bu~Bkq@}qBbe@_tCzvDk{HfbCatCrpA?qCscAbr@opC" +
                "re@?jq@tbAltAn{@h_@uaBi_@mqBre@?hzAvgApwBsFbmBwgAh}@c{Bti@ntA||B_sBv\\m|IbnCmtAyn@}v@ioAo\\?ym@fkAbC" +
                "vh@mUhCgk@kd@q`Ax`FmkDvvBpA{_BjqBngAr`@`bEuf@xRbd@xjBmpCtpB}s@vfBdI`vBvi@zbA`aAvpD~gFpNdbCn|@zlB`_@b" +
                "Ebe@ghA|e@?zG|nC~fAr~AxiBre@tqB{TzqAlpA`{Adi@x`EpC~y@r`A`B~qCze@?bUmt@de@}Zhq@n@`{@bd@lx@o|@fhApEbpG" +
                "pxAvYlgGlbCtFlf@`b@jGtg@sd@blIdHtdApaAtbAgl@fhB``@pxAhgC`vCdbBee@~w@vfAv{@v}E",
        ),
        borders = listOf(
            "ajmkGo|dkAbz@}j@hgB_SzjB|KrbBxkAre@s@bgClnB~Rx`E",
            "kt{jGaszjAwdAtyDedCdvAgtCs}@qtB{_D}hAqfE_UgsD",
            "ojw~Fmf_kAhFU",
            "ecw~Fcg_kAiFT",
        ),
        locatorFrame = GeoBox(36.30000, 6.30000, 47.40000, 18.80000),
        locatorLand = listOf(
            "uwoxFegxy@luiAwy`@tcl@ju^`bp@qmKzeeDnd[ldD`{MyaNpkj@|zBvlUufG`dQnxt@|oPt|HxsOmtA`nl@uou@z~k@g{t@~uBq" +
                "{m@idIcdDo{BdfB_qLs_Tcl@akJ`cIszBpePoihAwkKcrg@|`Veo\\n{^wbr@guEtaLcdZcWwvg@cnReuo@{~z@epnAjyIetI|`I" +
                "as`@l}X}g^dsOb`KbxHohN",
            "{lgdGiszx@tt[pbDduSy`MbrqAexC~vf@fg\\hio@reDzkx@pvc@uvf@h}hA{|TsnNuzJh~_@g~^kkCwa@~cVqe_@mmNwvKlbUgi" +
                "JzeCuvK_jTqkMrmTgod@sx[mjJ}zR_oIauk@g|L_lQhzByga@glz@gvHhbFspRlha@yiB",
            "}{ghFoha~Az`tA`yaAzu~@njYdeWglBzsP_cUvzE|}Ina]{vVndi@fcb@jq\\bS_lCzv`AwfPfpt@oko@jln@sdJttU|Qjkm@k{E" +
                "nnSiabAtdzBayPf_o@}sChmv@}tMddUaj\\`yPepl@u{TilX_nc@f}[e{_@srHiq[ucH{o@krJocSaFurXbah@_f`ByqJa_r@~rC" +
                "slm@crDcsi@gvValv@bxA{g_Ak~Y{eiAppCspYlfHdjJ",
            "cimwFgiatAoRfxLwjI}TbkCgwPbrE|sC",
            "mbj_FmwphA{pCprT{fKmm@fiCa{MnnKahD",
            "swleGwasdBjhEqouAvfHmnQcbAbdh@thEzwWsmFhc]ahKt|G",
            "c_ffGwe}gBnOvpcBmuPbcz@w_Byh[v_BahYrqFeaGhrHy_`B",
            "qhbgGyjmeBa`Bfrx@caEzbLksLc`DlaFahjAbaFybJ~qGzuS",
            "mvqdGohm~@`i[kvCujHbjOhvBl|f@siLdVajAoel@__F{`F",
            "akmmFe`wr@~hR|eJstLjyJyaNsc@lmHu{T",
            "_rnyFwjqq@r|GdoEwSdeHshW}jUt}BcrC`aKtgJ",
            "k||kGcy}{Ah{Es`Bc}K~jWgqKj}I`sQwg_@",
            "qqoqGaskyA|dCfaWksLrmM_oIfw^wl[kqVdko@wum@",
            "k~dpGowoyArrGo|C}vIbza@ehN}kAvS}lKvwOwaN",
            "kirmG_ou{A~dDv`Dcoa@hxo@_ih@`k`@vxbAwg`BjyAr`I",
            "wqakGypu{AxxCqoAqz@jzKi|q@n{s@`~n@if~@",
            "mskkGefy|AnoMkzK_~JzbXewH`pFteFqxR",
            "ktqoGqulwArqFfo@uqHf{J_}k@p|SkjVwkDcjWvqIg~ByzGh`e@yqYnq{@m`C",
            "oi`dGy_njBjlLusYwqPrcmAjdC}nr@",
            "_yh`H_{vqB~}vbA??~khkAwupC}lDcwFy~]|cOomPniO{tcAwqHkv{@eeWrtEzmEwpk@~rJsfa@xiVg|b@ntCyeV{qZyiqDkne@i" +
                "e}@}m[osiBfcEqk\\t`RrsInzMi`Hi`Hg|KedM~`C~Pyjh@xzGehTxq`@rn@d|_@ek[hkOb~FhuH_gV_sJstSoePakIu|Hgae@ie" +
                "Xgdc@uqA{_Sfwe@ueM`rXtc^zxo@p_`@hjMnl]tjVthX?yqqq@_arc@?_aOhs_@_sKepAh|@raXcefAhnfCmwF|sm@yua@dkhBuc" +
                "Aaaa@~ea@ykaBykeA~`sBclb@dek@in\\jmbBjrClwnAkvYhrG}fp@`juAylr@xf|@epO`hKegEio^hhB_nc@os_Ahs~A{fShyO_" +
                "vr@weAclTtcIiii@rkz@qyFdmm@fxa@h|Mdh~@tys@_JvoSo{s@nel@}}gAt{Tcl[e~r@ca[rg]p@fuLrzJrdQ}~Jlpq@xcYnka@" +
                "|ia@l`gBaf@|wKg`N_iSqG`tGpqRfni@j}f@~nHrkf@oq_@|_MoqXd~VduJ~cHjmNyrEvrSvlT`~Dlk`Bu{[dwk@sqx@rjModi@l" +
                "|l@wyjAllUios@fjkAi~m@rz~A_eg@lwb@us`@zswAendCtcVobz@{`@uizCjmGudf@r`OexC|yIxkFh{Yjkm@|fT~qAb~Mu{T`v" +
                "f@kihBtd`@gvjBzgj@olgAvec@w{|A`pv@w{gAhg\\szXhuUo|Cnjv@`wZiqUj|r@c`bApqh@ivJvszAwnJ~}YegSzdN{aAp`\\j" +
                "yI|bSht}@doq@reu@xgZt{Trq@~eTeyMvyJagk@rre@}tw@vuiAkvJfkNnzMy~Bdv[`xH|ge@tnPhbZltOvgJvuz@rrA~c^zkr@d" +
                "b{@z`k@bP`|_AoqQ|jNgqZ`Pe~OadJg}FozVggb@cbOcnXt`DihJgkHm~FyzGmbHsyj@wob@kqA_dOz_Scl_AtjOsi{Bzr_AofKp" +
                "_TmjBlww@e_`@xbbA_xLbgCogLmcJa}PloF_k^tbTeoFllMzqLbdrAwjXypVskOzr\\lAltr@yiJwS}uq@huc@ksSxtWrTj{a@ia" +
                "Jjc{@jxGx{]qe_@pwm@{{Jvsi@}_{AhokBgqZrks@ocg@xc`@koYhraAvoEfh]}eDllF}xFu|NajNfiBgwf@j|k@{xKthYexX~nQ" +
                "_bEvxd@wcm@gd@cu_@vhM{uZ`yWczsArzX{cMtlZozN~z|@}qi@jfuAecSbgeB`{Mtwh@rtzApyiBdhb@repCt~}@vliBtaa@zq[" +
                "|cKzws@ws_Y?",
        ),
        locatorLine = "qpwiGwvygA_yA}_IphIq~IaxAasM~vH}xJzzFa~AxaJ|kOnbIygDzoHa|VulCybKjnFa{JisA}lVhfFfxAbrHg|Q`j" +
            "t@qyC`n[_rY~s\\ulJdeG|iKn`Mm_QlkU|zT~wAwv\\~`LmtEvgItoHtx^lvAb{GacHpiHtw^bjj@tcd@i@xuL~tEpu@",
    )

    private fun caminoFrances() = WaySource(
        id = WayId.CAMINO_FRANCES,
        lengthMeters = 767753,
        stops = listOf(
            WayStop("saint_jean", 0, 43.16234, -1.23723, stage = true),
            WayStop("roncesvalles", 24043, 43.00891, -1.31920, stage = true),
            WayStop("zubiri", 45472, 42.92984, -1.50285, stage = true),
            WayStop("pamplona", 65950, 42.81811, -1.64424, stage = true),
            WayStop("puente_la_reina", 90138, 42.67213, -1.81452, stage = true),
            WayStop("estella", 111880, 42.66940, -2.02936, stage = true),
            WayStop("los_arcos", 133080, 42.56951, -2.19182, stage = true),
            WayStop("logrono", 161038, 42.46762, -2.44672, stage = true),
            WayStop("najera", 189737, 42.41653, -2.73422, stage = true),
            WayStop("santo_domingo", 210778, 42.44091, -2.95384, stage = true),
            WayStop("belorado", 233172, 42.42124, -3.19024, stage = true),
            WayStop("san_juan_de_ortega", 256774, 42.37579, -3.43598, stage = true),
            WayStop("burgos", 283072, 42.34099, -3.70476, stage = true),
            WayStop("hornillos", 303540, 42.33830, -3.92530, stage = true),
            WayStop("castrojeriz", 323302, 42.28800, -4.13864, stage = true),
            WayStop("fromista", 348167, 42.26621, -4.40610, stage = true),
            WayStop("carrion", 366978, 42.33741, -4.60271, stage = true),
            WayStop("terradillos", 396235, 42.36091, -4.92172, stage = true),
            WayStop("el_burgo_ranero", 424434, 42.42255, -5.22069, stage = true),
            WayStop("mansilla", 443332, 42.49876, -5.41678, stage = true),
            WayStop("leon", 462068, 42.59876, -5.56746, stage = true),
            WayStop("hospital_de_orbigo", 494613, 42.46362, -5.88192, stage = true),
            WayStop("astorga", 510829, 42.45754, -6.05677, stage = true),
            WayStop("rabanal", 530659, 42.48234, -6.28468, stage = true),
            WayStop("cruz_de_ferro", 538007, 42.48893, -6.36132, stage = false),
            WayStop("ponferrada", 563386, 42.54617, -6.59097, stage = true),
            WayStop("villafranca", 586527, 42.60676, -6.81082, stage = true),
            WayStop("o_cebreiro", 614355, 42.70757, -7.04267, stage = true),
            WayStop("triacastela", 635306, 42.75597, -7.23947, stage = true),
            WayStop("sarria", 653124, 42.77744, -7.41486, stage = true),
            WayStop("portomarin", 675315, 42.80648, -7.61704, stage = true),
            WayStop("palas_de_rei", 700197, 42.87305, -7.86857, stage = true),
            WayStop("arzua", 729121, 42.92625, -8.16304, stage = true),
            WayStop("o_pedrouzo", 748477, 42.90719, -8.36404, stage = true),
            WayStop("santiago", 767753, 42.88106, -8.54472, stage = true),
        ),
        frame = GeoBox(41.82871, -9.12932, 43.59190, -0.65261),
        line = "scmfGtspF?~hAxa@gwAbmBc[gfCvRlUu\\}BhTmRhl@wBes@tj@}j@wrA|_Al@yoAneBrh@oxBltBlyCu{EzzAyRyoBx`@nMs" +
            "g@~^}Tui@by@xeDw{CjkB`p@i{CvX|o@yr@db@~Eck@xL|_@k_@{J|e@uf@j`@zDaf@nSrg@_h@fd@jLko@db@vj@ou@aFnoCwzB|_Ap" +
            "}@}{A`Rty@gz@cYnu@{|@xObbAe|@pi@vm@y`A|bA|fGgsFwGfUqUrb@~Uis@nT~x@qx@tsAts@urByEvyAkoAxK`c@q`@nhDzsCk~Fp" +
            "Xzq@uw@]zf@ad@r{@z~@e~Ar`Aj~BylC|mAbj@udBhjA|HozAfv@`w@_sAzIxf@mh@jkAxa@iaB~OfmAaeAdpAz}AixBbGncCizBjf@r" +
            "bAosAha@pAwk@jcBddCqhDffAls@{cBjcCr_Eo`FjpB`tAisC`y@heCsjCtbArLmnAxyA`hA_zBxk@_@}x@t|Bf~BcrDj^b{CeqCxk@v" +
            "pAy|Ajp@x{CwmCyZpYgf@{`@`~DihDyj@nlBwzBkCzqEqyDeNh`@ma@|iAz}AuwBp\\tkAqjA`EdoCi{Bx`@~l@sy@_Svv@us@vHp`@s" +
            "c@}T`_@}d@tCza@{\\sk@v_@e{@dA|^wYdoCzrB{eEsBhp@yj@ho@nhBepBbBldAo_Al\\~Y_o@l_@xcBaeBzn@oK}v@jh@pdAiiAh|@" +
            "vRehAhr@vtDaiDl@jbAyw@zRjAgU|@t}BgkBvuBldBkaDp[{Ckb@nf@~lG{aFGdfCouBn`@vn@_v@zj@zPmz@uGt[_]l}@vxC}zCbLfg" +
            "BwrBnsAdlAowBxt@b~C_uC`OtwC_kC|rAbkAu~B~a@lBog@xKlbBgvAtx@|fD_{C`cBxiA{kCr`@prBcrBfStAoZrpAlnFkkFZ`q@wq@" +
            "vL`\\q[pr@pQ_oAaUpm@am@bBd`@oZ~Ut`C_oBlSvz@gv@dRxGkXmBzl@}j@pYbw@av@pbAvaA{}AcLr`Ay}@f]bxA}oAgAt_Fy{DnKr" +
            "e@ie@aZlqCc}BzItwAwiAm`@ntDqfDn[ffC{_C{h@f_H}tF_v@bpDk_DoVnS{a@}DvaAiv@dGdjBa|Axa@nhAkgArRpdB}uAnfAzzB_j" +
            "C_`@fzAyxA}|BjnDmkEkQbzBkhBkv@`sDahDqQlyDk{C`YpmAckA_Lpk@{k@foAl|Cq~CzGlwCueChbAh_BetBkF`k@if@yXvZgd@`@|" +
            "aB{pAf}A`iHanGk`@npActAh|@vkFovEqIxbByrArs@r}AqaBgIdnC{{BlM|x@ms@dOt{@ct@dc@nGwi@rn@dn@mbAhMp~AwvAfcAthA" +
            "}cBxs@hjBmkB@fgAc{@eo@~`DgpCqVl|CqcCna@`uIucHhOji@_g@}`A~fIgaH`g@xpCqcC|i@`Tax@j`@yIeg@nRxd@}e@iOx{D__Ds" +
            "Nzu@ip@}VnRic@z[~fA{hAoIh[q[zP`_CerBnr@lqDcdDfv@hkBwoB`HvbB}{ArQtYi^uNpp@ul@jNrVe\\wS`dDqsCgr@fdDqyC~@zq" +
            "AahAaK|MuRlc@llBszBgHjzBajBzw@~eAg}AyNfkIauGbMftDqvCv\\h}CwiCnk@t_Bq~AjMbxEgwD`iA~eFmpEnIv{@wr@uHttA}hAx" +
            "]~sCabCjOdk@}g@~{A|pBmsCmD~sDcwCb[ji@gq@wM|f@gd@gBxxCqaCv]puBikBtYrmHw_G|XpdAa`Ac{@`u@esAJx]_YdjBvmKy`Jh" +
            "bAhgCciCgWzXeb@l\\nrAwlAU`eBcsAsp@jcCohClGjfAk|@gVxjFkkEo^rmA{hAe}CblFggGkoA|}DusD_aAnvEgaEo{AzuDiuD{@dm" +
            "@mf@_NrCqPk^rnIo}Gf_BhdUqqQR|~FgrEobAjcCscCks@|qDsaDotArZefB}T|r@oq@li@h{EyiEsJpjAk`AfJxpCe_Cg_@|[em@lW~" +
            "oBagByBfyAglAuSzzA_pAgf@`Nu}@cD~aDqlCjOhdAabAyqAtyEmmEgN`mFkfEy]`kCkwBxIllA{_Ac{CfaJmsIcbCzoGilGkxAhnCcy" +
            "Cg`Ad}CusCwi@xzCsgCxCz{@kq@}TvN_\\{O`kBk~A_]jj@{u@ajCrwJe~ImxGd|E_xJwKdo@kj@myBjoDuiEq`AndIseHkf@|gBidBe" +
            "wAnxAe`CcXoK{e@cNhV{b@db@dhFqvE~mClrHecIbRnB_Y{KtRwTnCpoAobAtWlhAmaA`jBrtEcwEzeFtkIy}JpoHn_Q}lQ|I`jC}rB|" +
            "m@nqAyvAhx@fwGsqFuJjwEaqDm^nr@yx@iGfxAyiAsGh}FsvErR|f@cbAge@bkAm_B}OxxDa{Cdi@lwFmsEk@r_DucC_x@naLueJ{tAj" +
            "dF{uE_`@``Fc_Ewr@pfDwaDjJpf@me@qQdbBsyAxPx\\yc@oJbVoWrQzk@ak@qGhbAsx@lNhq@un@u^voCwgCvQdPe[dGttAolAuTdbA" +
            "m}@tBlq@gi@c_@fd@mp@kBt}@cy@s}CrwCogFup@|~Bg_C}Cr`Aa~@oXt@e_@L|b@ga@maAdmBo{Bg@hwA{jAbk@`xAi{AbUdoCabCod" +
            "@rk@u`Ak_@kM_l@oJv`@eb@_n@{Hkz@_S_c@eh@ooAp_By}Bye@rnDo{CtKjrD_vCgeAbpBa}BclA|iFyxEgBr{AolAmb@nuBoiB~H~}" +
            "AioAdQ`^}_@mTbcC_uBbBhnBu|AebAve@mzAvSn]yi@sRzCkVwUfr@ss@}[dB{a@jKni@qh@oa@hy@c_AedA`z@w{AoNtiAceAme@f`@" +
            "is@iY|wAepAae@~b@et@rLhi@qk@mYp~@i}@vE~TgTyYnpAwlA}WdEs\\dH~gDyvC}s@fkAgwAvMl`B{}Agc@blB{jBmaA|qAe|BkuBn" +
            "sA_`DkJ|}BytBjl@hcAanA_IbmAgiA~Wdb@wh@_I~yAylAm_@vx@_|@wEjs@ql@oXxTek@fAjf@ob@qz@xeCiiCwvA~_CgrCqWrsA}kA" +
            "mk@f]{x@wAn_Aoz@n[dVoe@sl@~{CmcDgr@jhAezAdBlxAakAoy@ne@skA_e@bcA}hA|e@nwByqBkV~Rmb@|KznA_dAmJjiAoiAi_@hK" +
            "oj@nLjXa_@iXplDy`DzIffDalC}TzbBivAvIjuCa`CmUrlAqwAnu@ntBorCyE`VmT~]zj@gw@}S|Vc^wDrkAggA_]|`@om@dNzp@{k@u" +
            "t@hZmaAf@ffA{|@vVh_AobAoSlrA_mAg]zPgh@hJp|@wu@oIbyA}rAvM|x@cu@wq@hhBmlBya@xmFmwEkZtg@cn@cb@e@sp@hJpq@}aA" +
            "eOfmBiiBqZfT{c@uEjmBmzAshBvnFeoFeZvvBekBcs@dpAqcBwTzdCyrB}Vd\\}b@{QrkA{aAmnAnzAwwBsD~f@aa@um@hjAgpAdDjuB" +
            "wkBaRj_Agy@dUvmEgpDuJtf@gi@hXxeBqkBc|@voDghD~Fxy@}p@wPfvCofCclCzdGsvGu]h[al@m`@raBu|AlSjz@{v@kg@hgDozCzL" +
            "|c@gb@gCx_CeoBsNheAydA{b@df@ox@ci@xeEazDH|l@}e@jLvIkRgLxGySlEr{A{lAfVlaAg{@_G|~@eu@n]bkAapAcUn[yg@gO~sC_" +
            "bCxdAh}DmuDev@z~E}jEln@baCmzBtTf~BcuB{QtlBakB~d@zrBgnB|^ng@qu@bUbyAgzA}Kz{D}oDmOje@ce@c`@uC_d@h@hq@qh@j" +
            "\\~Hke@ps@znCkjCnKcOoWdi@ha@saADjmFszEr\\xgBc_BoAn_CylBtKhp@cl@~SzK{YvCh{@mt@",
        land = listOf(
            "{gp_Hq{`G|yuv@?a{dQ?v`Cl`Sr~GfwGspAhbEhDbrGjd@neGl|CzvKvqO~`UzwIxtIlnOneTpuD~wBt~ByxIaa@yiBs|AxiBbEy" +
                "gBriI}rMdYkfEdaCbGfaCpxAbcA~{@~xAxpK~sB|kDvnJfsH|pBdzDfhAl}JarDnqCw\\clHxjA{kCu`BomEanG{bFaBjzHb_Cfb" +
                "O`sCxaFltSrcKhxHboHf_Dtg@b}Bv`D|dSjrLhmFnbIdfFbtE~mFxrJjbQlzJrkCzjDpwC||HzoRxnLblOjgP`{X|cS|_IfyA`jH" +
                "dnH~cHfuC~{EhbE|mIrnBv_Q_}@f|KywB`kZqwOf`BxeDrsIw_BflTelLdyKodIp`LexQrzByqVfuBqkGtjDybEnm@~xAvmDmdH_" +
                "Lq|@tmDwi@`o@vi@z`Aj}HnjFjeEbUhdDpgCf}ElaBx|@vwAqm@{Vz|B``A~tMjnAfoDveBvhA~hG``@znAb_BhnAvyRdyKfv_@d" +
                "gKp_KzsEpn@v\\raHtpCpwAeIv|EfwF|v@lzPi{AfhAlfArc@pyMhnGdjG?vfxp@o}FajBws`@d`CmvFt`DsyHjeJasCjbFkt@vm" +
                "DqlAs~Afm@mmCn~CmfF`gC{cLjpA}HsF{bGndCspRsnAaxHkc@t|I{iDxiMy`FdeB}uE{~AcaBhuCu|CkUuKdaBheEpyBp^j{Bre" +
                "@?hN{iCnyA{_AhuCzq@kb@bqGm}CxjMjl@rqHp~FlwGx\\kp@ptBraJ`y@r}QbuBztIye@b|DwuBxAwxEo_GylN_f@cgUpmLgp@i" +
                "qBeo@mmPtiCchFe_Cre@gxAo_KklEebEqqH}iNauJ|kDc~Ayk@rF~oCynKr|Cg{R}iLwbCmxEcpA}~NodCcaFkhDs|Ch_Gp|Lpm@" +
                "jzOjt@bqApeO|eLrzObyIj`GjaGveBlf@pyM}r@~rC`xAv}B|_Tk]nuKvpDpcFarEveO{Td~O}fFoj@suKrnAm}FieGyxN{kEadR" +
                "~uAcrHawAwdVa_MoqLe_AioLv|C}sFrnGjl@i_JuzHw~PwH__ChuA_mC_y@_hA}|CxtC_cI{dHorC{eHkiK{yGgbFQ_tKqsBkxuA" +
                "cwf@ayAa|AxvBgoDjGoyFqm@?k~BxaEq{@djKct@xiBq_FxiAmrMalGojfAm}Tce@ks@fmD?evEsuE|g@u}BafDle@uYa|@jdA_y" +
                "AaRy|@yvCe_C_vBryC}bAwOehAstJszBabEz_BbcLgm@pqDy}Eh~Aq|FgmFwcCn{@lzDrp@lVvl@}qAh_@d~BfwA`qQxwCl|IjcF" +
                "cpaAcuQocZ|cAc|BcnB}h@|hFqrPd`I}qAo]kvK`kA_zKztFi_G~IcpE}aAiuf@zzIceAqTowAsjOk{CoeHziDlcYw{@naEajE~v" +
                "Bk_Uwa@}aO{zTmfFyiApmGvuGfhA|hFt{CzeEoZxfByug@hkBkkBiRmj@ecA_[{iJox@qm@ip@~[sqAnpCotAy`EunCy~@ykS}gb" +
                "@q{GgNfiAzhDrcFrzCtzDpjRtv@bdAzUvbOsmH_xAdaBs}Bin@cc@wwGzTw\\snBzUs~Fs~GwxGqmFiqKgyAil@tIdtFtiEtiKtg" +
                "@tlIyQljEucAntCy~Fd_CotAhtImqBw`D}v@w|EfgAu~B~y@`Abf@jqAlt@mmC{Ek{CwmEeHyo@gkAuwE~kAsgEuL_{EygHcjOmu" +
                "G`dElnC~dBfaEq`@vtBccF`~EfoEhlBlt@o}@doC~fCrb@nhA{r@pxAs`As`@`_@fvA~uB~lEpnAowAxyAxhHtmDbcAd_Cf_EqlA" +
                "r{AuyEvj@uoBliFavCa_@y}FigDmbHeu@gbDgtCclBslGceFq~FeYytC}lCkrAucBfPcs@v`CzmC|XheChoFhAzbRngBsSlqB|nC" +
                "vLjdEmt@jqA}bHxeCkUigCyhB{oAggAzq@ymAdlE{gDpm@mgAudAieCyQ}x@poEukC|mDdmCOhDfxAcrAtYkFx|@lfAb|Bn|E`sD" +
                "o|EfuBaePi_GqyAfcCgsCfm@{c@afCkhDgkAa{AgqCghAo\\xjAulDyjAekDs~BobCef@gpE_m@?ru@jzIsu@sEviArfEkGnwAcl" +
                "Bvx@yoEahHynA{gE~iAoiFwi@akHeuA}}CyqDm_BhiAe`Dus@ukIw{@yjBw]nlEsjCp|AebAtzCsjJwz]xrDwtG~uBy`Qo_EssRr" +
                "cActEmqByfImmCk{Bmw@u|DwiAknAcaAauIdnCqmAvxAiiCueA{nA_lEqD{oAox@jzB_lK`aE_gB~dD_oEj}Aik@ecBio@__Kxk@" +
                "g_D}tEej@zyBmXrrLqsCn{FccAusBueAe`T_tBy~@fxAriPqm@}sAui@|sArpAhiAjd@pzBdH|rGg`I_fBbUwfA{sAspAurAvcB}" +
                "`CtZfO}aIucAqrDayN}l[fhBgjAyRemC?ltAmtAmtAefApwBsaAnPa`EozAss@igNykAooDiaFmtGhRelD`zGsuEze@?{e@tbC`l" +
                "B~gAdcBia@rc@p_Asc@lbApxAltAdKqxHgm@gx@sgCtqBsf@gsCrf@kyCgxA~i@}eAwvAyxBymFepBm|JukEciDtaCsjBheDtiDv" +
                "sBmXoZoeBgkAwOev@scEjmH}mDlaBhQ{vDswDjTyjA{iBolElf@m_IxyGg`Wj|NmhK`iBagH|~BpxA|ZmrA_jAggGvy@mlJuI}|J" +
                "yn@gfBvx@_zE|f@wiApzBeHjdFdmCjkBmw@gcNcmGey@yeJqOcy`@ddAkbLieCawI|Vk}HllDqbPym@weHs~Ble@~wAw`Iym@}bS" +
                "kiD}|Pd_CovGre@gdNse@s_Bpb@uaBgtBi|G?ytUuw@q_@{~AdcA{_A{lA}sAfi@u[cqGqeCweAxlAkmHt~NqpQwwAojApfCqwBr" +
                "e@gcIse@sif@zc@u|D|uAqRvmD|zDti@_j@mtAkbG}qBu`BzDwbJxlHmyVjR}yOn]wtCznAsaAsb@ajAb`BssLcpAktEjhCalSdk" +
                "EazRpzAghk@vtBqdDk}AoaCmWwoDxuB{kImcBk{BjW}aH_{@kgWuaBukDgyAejKqOikL_xAueB~wAybEwi@u~BmtA|sAuqB}vEqo" +
                "@c`Hrb@sp@mnBopJvYsxDtsAgmDnxAznGpzBzdEpxA}~Bre@pm@qDs|B{gDcrF~wAuiD{pAeKm~B`mA|e@qeD}e@qm@om@pm@q^a" +
                "|FweB{hE{lBc~MlGu{CpjB|JpCqjBrzBqqE`lAqlMb|BaQzI|qBuw@|nCfqCzdE~Ok{Bl`Bm`CmqB_wAnhAsbA{a@cpG|~BccWfx" +
                "AelJnrCaqEj`AyzGtIovBcoA}mCj~Gk{NkxI~bCy~FomPmtAdi@_x@{aGeJceRsbA{nF|mD{lI`cJavCspFuqAyb@wfBbaGqua@v" +
                "dCgvBppEi}QhkAgdOmeAkgPhkBigCxRqkAui@qkBltAqiBogBysD{vCqjSozAcuEvAa{AhfCkgDqm@wvAwwAnbCsrAy}FesFikMf" +
                "uBq~EspAw`Di`A{hPquC}oCgtBs_G{|HuwEu|OosOqwtAkpXwgv@krKuof@cuE_aI`}@{jDidDcqKaxCylBszBh~@kzOsV_{Ek_A" +
                "s}Bc~AaA}rBryC?mtAixAh|@q{HfwMk~@`cEh}Lv~JloN`fDyj_Bu{Jg|]{bGuak@avCipKsmHyB{eDtgFlVd|C{jCrdFsaLr|Bs" +
                "gJzpQysVhvD_nDv{D}gApo^{oFtiJarEhdEssEfdHcnNbuQ}`Cxl@msAatIduAsgDgz@qfCdfAgdDj}G~^waJpeCk|GscEl|C_uC" +
                "`gOqyBp}EyaD|pBgdr@fmKuhKfoEsjIfhG}hFl`HucMvtZeoC`m@coAbuFoiFtmIurBlxKqbEnwGx`@vzEa_@boBwbOiiBgxAo~K" +
                "xBayBvzK__P|mC}tLqsPt~Y}xJvcD}jD{sFku@}sFkhCiQqwCxwB}sAu_CwbCljD_mEnwAdcA_kF{r@}qA}nC{cA{mB~|EixGboA" +
                "_xAzfEylAajAu`BfzEalAiAgQzmHm_BjaAklCe_DqvBp`@kqAkcA{xDimLsnAsq@__Erq@_eCxfCwKvvGr_BzfFjdEaFa_@`gDm{" +
                "EfhFgZvaDm|Dh`LdhAzjIyDt}C}aHvgB}pBvbBudAznCwhAjtVqlA{s@cbAtdBeh@dlIm~BppEcbAh~Fy~FdnDliFom@rDltAgbO" +
                "zdE{kBoZg\\dcBqaF~sBi`EvgGu~Ch~@amA|aHiiHpmFgyFzzImmD~jL}wEneAkqF}F}nCuiEowAjc@qfD{iIqmLy~Fow@{lBkwE" +
                "rpAciC`cDeoCzvJ_vAtoUsrAx}E_tBi~Euh@gzF}cFug@g_E|rAq_FggA}Ra}q@~DlvBfm@?d_Ci_Gxa@}bGvmDixIrFgpIq{An}" +
                "JapHrjM?t~aAbj@rbEvbCngGy_@njFamCfgE?xkLfs@jNgs@p}H",
            "g{uxGvgyF{cAxtIsoGv{Qvm@l}I}Yz~AurGfaIi~@sgJxOuoBfy@ikAvhAld@qm@`tE~bCykBmtAmoNti@??~wApm@?xa@wfBteA" +
                "ctRfaDwgG~rBogAze@jiD",
            "{yw}GrulLvmDixInhHgMmh@ffBqzGf~E_jAt}Cvz@jhD{_BdbBqnF|_Bc}A~hBoLocJtcAcpFjrFN",
            "mpdlFq{`GpBzmAqmAxm@}XfhBtYhhBxlAth@{hDrmGkpB|ZkqFc_BqjA|w@ce@{r@in@{nMmxKzq@_dBmkD",
            "ollwGddmFnv@`^fvB}sFpjBuw@hlLlrBlbBpzAcb@jmBybKfpEibJvqNehFpmFywBwh@shJ`oEz~AkuKfzFa|K}XwbDb~@ovAfpE" +
                "yRfxAedA",
            "mgf|GtngMlfA{rFdmC{uDue@bkCiCfsNuqB|fAgw@qo@H_lF",
            "siflF`zdv@iQsc@tf@iCx|Ati@x`EjeEgKtg@sgEeqBc_Bs}B",
            "_|{iFf~~t@lXymAlu@v_@{nA`m@",
            "udilFvf_v@|`Co{@fYlvAin@~x@{kB}sA",
            "qkolFjm_v@l{C~vAi`Eoz@zc@o[",
            "_opoFtx`y@caAcVtH}g@lw@`_A",
            "wd`tFjj}t@~bByjG~k@bfE_pCt}B?_y@",
        ),
        lakes = listOf(
            "cw_rFxyz^~l@k_AvfAx|Ar~ApzHor@d~HqvB`oF~eBxfFkQfaAcnAqtAog@ng@tBrsAlxB|{AcgCbfLqOh~Dxc@diDjmBhnBeH|o" +
                "Ar~AlyGmuAtuUv_C~iHii@tuGw_CptA{@~sC{jHr_Use@urAdk@yoEtbDenFvwCmlPzKo~a@weJeo^i^geLuiBkvA{n@`zAyn@??" +
                "qbCssAotA`xEeiD|dAjoC`fBwfAp`GixKre@krD}}B_jH",
            "g|owFte{Na`@i|CveJbtM`jDfj@~oFdwErvB|JdoByjCp`BjmBbnF|rBzn@|zAw{@ptAybIerCa|BzpA}kDmjAmwKewJcfGgiI",
            "qgxnFzr`^_fBunDg`Jo~EjQsaCjeHpdDxfFl_FiwAxjC",
            "gounF`g|]|dAzKdv@fpGrhFdiIf`JviBmuAniAkbB\\{iQijEluA_gGaqBk~DhwAyjC",
            "yofoFtct]otJjfDx_CecKa_DwdEjiEeyT~l@?kmBvlMnDv~FdyFgcPteEs|@vsF}kDtwCesHdoBu~AaqBxgKmjAlaBoqIzcE{dA~" +
                "nAii@ltEgoBbpB_fBd|Gn}@raC`qBev@kQraC",
            "q{xuFtvfNfSm|Dhi@|}BaUtkC{uC|aIbnAh`TbqGxjCznE_mErsAx@y|AflA|gG`J}kDfdGi}Hxz@aUd~HwpEqcHup@uzIerCqbC" +
                "jt@iyPc`@c~Cd`EklF",
        ),
        rivers = listOf(
            "mvpeG~shYq}@m}NlqBm_I}Vk_HnwAqbJ|}Hi_FnsNxkApwC}ZljD}`HvMs}AudFiwOuZ{oGxQsoGfiAg{EztEiyHi_AydCoy@{Tg" +
                "rC`]ev@xmA_eBavCqqE_^ct@{fD|u@aaKvxAazBnqDoy@lwE}_Oh`E}xElYicDc`AmiQ`nAamGkG{{Hfx@miEw\\kiCz|B}xKwfB" +
                "m}IpmAmgEzyUq`d@luEsb@~n@sd@cg@}tAlx@kUb}AnwAfhAsb@uFghMj{Bti@?exEbiCxAdh@kpGhuDgoJ_|@mmCha@_}@r~AuI" +
                "owAg_D`Bg~EyzAtKqmA{kCzlBa}@d`CyqKdeBckOkWgvMbrG{|MhA}lUnwAgdCdtA~wA|`B}uAzd@{kN|eLovMz~BokFliDue@?}" +
                "mDbcGe~NdgEi`Qb_I}uLrzHeKd}CweBlgFuoIrmGyyRvhSumVfeCmaH`dDctEbnAwnJfuC}rArS_dIdtAwk@ue@wgBb`GseJh~@o" +
                "nEleFmbHpm@m~BltA~h@dtA_i@ltAcwKldGsnG~nE{pLbwCy}RtyDqbJfxAc|BtnDmdB~wAgfGhcD~[n]khExlFcb@|tF}eGrqGc" +
                "bAfMwhX|rByfZprCyyM",
            "a`}zFxiJzd@khKovGs~@vz@gzFieD}kDq`@asE}u@edAc{Hwi@efAehAw]w`Oh`AkgE|lD}gFhl@}eFfeBezDnaEikA~fGtzClnC" +
                "gJzc@_oQsnAuqGlbBa{M|zJ}rA`wByuI~fA}w@byJyjAloBtGxhCbaBltM~}Vd|C~rBv~Js`Anz@geBxbPiq@~xGapEdxDabKim@" +
                "wmJnbCutSyBqsDyxBiwH",
            "utjvFd|tOorCgcDotHdLegMyrJ}iDibEslCudG",
            "eqfrFn_rc@psJoud@ue@s`Mhm@saLilAmzKczCulIym@uqTrFofG`~@yaEh{AyjBfsBqaLoNgbCotBw{F",
            "i`pvF|fcI}bAmoBuaCeg@edMei@k`SvqIqxBb|CanAbsEagCfxSyxGn|J`rDhiNdi@lsXb~AvqIo@vlLf{@puOziCttFxfD`sD|e" +
                "@~oEltAfcCdItuQdh@||D",
            "mujvFrvtO`m@bvEf_EviAjiD|mClqMlpBx|AbyCldAjbG|eGxn@joAroGjuElrBxlFdpHdtGlhE|jJ~mQjtExiBd_CjmNhyClyJl" +
                "t@tnIcoAdyDvhArvEeZ|qY~eBfoUlqNhsVdbBjoMd|IdeXdeBftIwfB|nC{aAdfWfcCpvCtdA~eImoBtwDd_Cb_CbpAkpAfsBf}D" +
                "kdE|gRkc@vyFcdFbqFgnExmLskBhpLmhF~nOd_CnmFhBdiJjf@t_Cf}D`uDl{Ir}MxrK~cIr_Ab{BhSloNs~BpkH~]p`L",
            "eqfrFn_rc@ti@tbCui@vi@ti@ti@wOxbDb~HftTjeKnos@cEtvFe_DfiRswDfcIzr@vfe@rjCxqJtjJpwNxzBzg]",
            "uieqFjdmj@x_@h}Qa_AhfCxR~bJdfAdpHir@vwj@vmFveMs`A~`Jfz@deBtrF~oDrc@byBjaGfxGxbKrmT?bvOdtAxkNetAbaMhy" +
                "BztJmv@fb[joA~~Jtv@|mChkHlpCjvDnoDdnNvdYfzFhhDntCv~Db_G~sA|bShnL",
            "iie_Gbf~PtnCotBvxAmjP~rBqmAj_B{sEcVgmLfyAu_BlcAwtTneBmZz~BkgObfD{iDa_@}fFfeTfNboAedAuf@kkCbxCuxEneCw" +
                "j@vx@qyBlbCd_C|e@e_CfeB|XjaApzApjBriOny@vyAdxKvuG|uA~lE~M`nFgiAtsS}uAjiCvk@`}L_sCnrD}e@pwBp|FjkNtHhu" +
                "J}u@jeEo~CzUyo@p}@ndBpxMwjFz_HoZnpCqaFzrLvObrRmqCxvHoy@bhJ}}C|vLzcArtEa{BbiImWlwLcnBt`Cli@dxEct@|xJ{" +
                "iDjdQjWpkHxfCnuA|zJffNdX|pB}e@xgN{aBtwFsQbnSkqA|aHvpCtkWxBzjNfhB`mFz`Gja_@ya@jzTtmIvkLp}@|dFnzArz[t}" +
                "ChwHj~@h_L|fFj{NseK`aLwgGpxMxyBjnMvL|_IqPzoAmrBp~@jpAzbFue@bmHdVljQldAjlHzdF`}Fq_FrxD|cBxjBvuGb|BiiB" +
                "riU{zCdsGm|IhuHynFfuIuI~uAp}@|pB|kPhdPpbEjTptInmF|IrbEniA`fDzzB??d_CxoFxbEdrGjtKpvClfL`RpfOpiMzwJ~|E" +
                "rlHnvH~z@xuIbkIuKljPbr@fbCwZtnJssEjfPugFnrCc|Cef@{}A`qE_nDmtAlwEbfJmh@pfItg@lgS{r@`pEouHrgJ~lEp|XbHl" +
                "iP",
            "sejzF|jum@`hC|}Hfi@x~Eg[x`FcvDvsHfKr{BtaHv{QrgElyVsS``XbnG~`b@iB|mCguBziCdoC~wAirD~rNe_DbaBkhDj~Fcb@" +
                "|_O",
            "ovpnF~qb\\{aF|tLskIbsE{iCljEcyDfjLbGx~FhjHtg@`fClrAdwFrnGltF`yMvfB~zAprKtdA",
            "w_~nFzaiRgk@~_VtpAzkNxb@~uApiGd{DrmH~wYj~A~nPtvAjrFtnHjaLx|A`fJtzDtoHbbAh~Fx\\xbPxlAzcFfaDxeDboMqyB|" +
                "aCpPx~EjaSsuE~|D_wAx`Gjc@pnEidIngSrnAldSknBoz@ysChsKepIfjLltAntAuwEraAkcGvfNc{Bwi@odIl`HagCtxEuu@f}E",
            "qg_nF`zr^tvEt}Hf~DftNfxGduGnnEtmUvJjeP",
            "wccmFli|`@mV~{JegAroGi^x}Wfz@x~L`aE~mPpkHfhM~h@z`Gm~BnlLle@b~FfhHjjD`gH|cG|u@b}By{@rrFm{OjkOqp@~iFli" +
                "K|fQ|e@vgNfxAbtEclC|dRcrFtcNho@jmMnuBreKa_@~xAlYdaBtqBrmBjvIfkRvvAreKvpD`rDjlIbvPpvCltA`cJ|u@|oBeKb_" +
                "Ce_Ch_KneHxbK|mDryCc`AfsI`bJt~HteAf{@v`ElqMrCljEr`At}CvyGndIpsCtg@zoAoBzqM`mB|dB",
            "miksFx}pMzp@h~FddBb`F~oI|vFhpFrcAjwCrlGjxDvjAlcGrDtkJxwIz`Mui@|`IitItfFuh@tyKdbCxjGgjArjIlpBtlIowAhj" +
                "Cnm@d{DzgJjq@poEzTr{NyPlqB{_H|}IboB|lDfk@|za@tgFfgY",
            "}iwpGq{`GdnAppDgj@nkFd_CltAeYlqBdpBv|Dio@r}Bue@im@ui@hm@xkAzmBcoAp|A~l@h}EexE~wMnmDptC?ttG}jDvtHdg@p" +
                "wBqcEt}CxxCr`BwOryBopCbyCde@ffB`sDgL|w@rqF}oB|oiAvi@~iFkpA|lDmtAr_MltAwi@n~ElcHh_@nsB}sAd_[",
            "wztpGkaE{lCf}D",
            "shypGcC`lB|eRpwBruEaPxkB}iEreKinFnZsFnvB|dAlv@e_DtbB{q@naCb~A`iBaAhlBmmDntAgjApuD{DptP{mHfvG",
            "}lygFne~OkpA{b@_eCvk@ghArzC{q@ptO`{AfwFlvFbfE",
            "oxdeGzr~]npChoFtyEf_EpzApa@toCwgBpnEeg@|fLxkA~uNtqGzmGhbF`bQl{UziCh|FzeEd{PnqDxwHznGxbEdbItdA|kIs_An" +
                "cDgdCniXnfG~dYpwCfeHbtEviS`yZhbPz|GfgBg@j{CwoCb|AyShmGdaNzsKpiHz|BduGvcCbbA~yF{UblCxlAh{@nfGjpAbaA",
            "cihcGaqsDcvD~\\orCxiB{oAb{NgbD`fIu_BphI{pAzlBc{CqBs_MsuEckCbc@q{FzcG_fCz`FcjObrGuqBh_FqhCdeAoqBaxBcz" +
                "CweOr~@q`Ks`@i~Ez`@gmLmHcqFa{AqmF{vJihOkaG}yUygOiuVw{Kq_KcvMolE",
            "ks~iGq{`Gsn@vgA_}Dp}@mkEtuFa_LttFsmHh_GesFxkAk~B|pBunBtqG_|KtqHubBj{HeK~mEluAlaH}[xaFosBxqJeuFjyIenC" +
                "lvL}KlxJ}eAfcDm|Hj~GyvCv{\\aDriJ}s@jgDwfCdfAohGiRywHf}DmiD?c_CjbGkTd{DwmJbxOs~BzpA?lmD_xAd_CsjBhQhBx" +
                "}FweCddAew@rlH",
            "kh_oGzkDe_CltAdrB|vc@q`@v_EazA`uCsbSxaPadDpbKc_Gn~Kk{BbzByzGp|A_rCx}FmuAeMefFseE",
            "{gp_Hqyx@~eEbsOdg@jfPznB~fHswDlwK",
            "mak_Hs}@a}@diKkgBrhF",
            "{gp_Hb|tGzbCbjFdzEfyF?zbGnrBl_HnOdiKmtAxfO",
        ),
        borders = listOf(
            "wgfgG~gtIekDrs@ilAxlAy~@frDqwGuP",
            "im}fGhtyHu|@tmDidFnd@omAjlF",
            "y~hgGzugI`vAbqK",
            "yj`gG|k}G}bBrcGwl@n}H",
            "o|dgG`ooHnh@h|An`D|sAdc@~qC",
            "qcseGrcmGug@fcImy@fiCudFz~DcmI}bKs}LabDucFzVofCprDS|iA",
            "}eagGjayGbZpiC",
            "wpneG`r_FspEpaLsbB|~M_lDtdCkcDotDmZblC",
            "yrcfGzq~F|e@dkCbxApjB``Hly@lsAht@tXfiB",
            "cibeG`tgDg]`qNcx@~mFkxD|dH{h@`_Iy{AlkE",
            "q`oeGpgxExNniF",
            "yiudGxtkCekBz~CciB_^o}EdtBii@hfD",
            "}hdeGdrxCx~@z`N",
            "iwedGd{tB{iItvGgmDzcK",
            "mpudGvwiCrE`|@",
            "yuldG}rvCiwAtqL",
            "cnodGg`iC~q@fzHh~EbO`nDzvApeAcdAhsBzjB~{AmbDfbEec@rwAhgC",
            "gfcdGfug@uMlfDgsBfiAmjFnxM",
            "stndGl`~@nzBh}B",
            "iicdG}{rDe{B|{EaxDrqP",
            "q~ldGklzCvGlxB",
            "cyjdGv~aAug@fu@",
            "yaldG~tcAbpFnbM~Iz}D",
            "ueddGjwwAcsBdpIgBf~C",
            "a}gdGxggBvsC~IhgAroE",
            "_`adGlcnBivChqB",
            "iwedGvuqB?ldB",
            "q}scG{`bFg_AhoDwoGnkDehAlmBow@jvSoaBbkE",
            "wredGcrxDlhAduD",
            "e}ocGhrFceErsNmsAnXs|DvwEqwErU",
            "}medGxo^tfAldH",
            "ivlcGext@ocGlfFqcBloL",
            "k_xcGi``@jrFf{`@",
            "_lpcG|YxMjwE",
            "akocG_}nAcQ~{Bo|Arm@ukBxkD",
            "kgvcGqddA`]jpB~gGd}G~Hx{A",
            "{kucGq{`GmB~hW",
            "ioucGqqhFvp@toE",
            "c~ocG_m}Ac_@tfB",
            "g~pcGiezAdr@hgJ",
            "_yocGqu|B}Tp|E",
            "}npcG_xuBxO~iW",
            "soujFd_kk@{~Bf_CepBpKacJqv@uvCgtAslIyuPmpDqrDmp@m_H",
            "_gv_Grz~p@um@nnAiqJ|@ezCtoB",
            "}l~kFjtjj@wmD{oHoyDgWqyBpuAenFqqGg{LepHwcBjpA}iBgj@kyBjf@coBpvAwwCnsFeb@`bD",
            "irvmFtzbj@nMvcDp|Ab`Fwp@~yDqeB~gAkxDwpAovBpkAi{ClzM{`BdvAm_G`f@kqBisAyxLxxMinG|_@meM}qBi}@dm@gu@peGy" +
                "lB~bF{}DjpBitAfrEm|I`rKwxO`bGvp@cdi@wfAgoH_SecJr_AufCvEwaEeuB}q^aeC_gAsqCfVq{E}}B_pDfl@isB_}AihAoiEo" +
                "tDi|Cc}IeNyvAeaBcuGkp@mkE_hC{hQbzMq`A`eCeb@fpFodKxiDyrGyiDcmDw|JgL_kJ_|@_rBi|Dap@}dF_kJouColBevCfqEy" +
                "sD~oCyjEnc@cdMwuG{jBra@mlEp|DelB|K}tKcaFqpTjzCcdOoN{WaeBwmA{XuqA`^gjBbtEs`K~yDmsIfxIymA|KsfEkzA_r@mb" +
                "CdYu_K}LqiDg_AgtAwtGkvFiwHwz@{|EulH_iM}wJkRsfOovCyeLorGitKgoFkcE?q~Ba{B?siAsfD}IcbEmtIumF_cEiT_iM{jM" +
                "eiJj}K_hChwGcsAfpH{oA~oQrqCzfGic@poF_cB|tAetKfiCa}WkkIw_BjaIetJ{XezBlkFndChrAfp@dsE|L`|L_i@~yDkfG`cF" +
                "kXz}DjyDjf@xcAfsCsArrP{nCdfHfwCdoJe{GbkQpsC`tIzcKqKhkCn`CfqEzgS~S`qLr`Fn|HebHreDylAjaHdzCdaBtq@r}Atg" +
                "@brJmi@vcByy@zBocEq_ByIfoIcwCl{J|bAtnDzmAjmRtnBh}AIreEm|Ilz@nb@`zBr`GpuBnSnpHnfHhvIj{@twGyW`yOusFyNu" +
                "qB~mGqnBveAmsBkHszJqkHg{GcnMszD}oAa|Avq@{iB`vEtbApnIum@nnAiqJ|@ezCtoBhcBhzDxm@`lGlpD``IhsBjd]frDn~Lb" +
                "T|pIlyBp_DrdE~pBv_E|rN",
            "}lygFf_pi@azHkaCkz@jgBtg@xcKxrAzkAfoA`uHi@~}AekB|pCkzN|zFo|BduDq}C||Aa|SdtScgCzeGgoCeuCkyCf`AecKmmDa" +
                "_KofH",
        ),
        locatorFrame = GeoBox(35.80000, -9.70000, 44.00000, 3.60000),
        locatorLand = listOf(
            "aozqFeieRvoEwuQy_Cmf]lcBmjIvkKqoApw{@xki@ltOfq`@ujOpit@wt]`kR{vAt~KnhN`hYukQhhXk_G}Fatx@iegB{hI{dx@t" +
                "k`@peI",
            "mc`kFcivHtEbwc@q~Qa~DzwQax]",
            "{hplFsgyGz~JnaFwfChu\\kzC|pEqqLulEes@goGejRcpHmzF{ci@z`O{pJvmV`za@",
            "_wpkG_c~T~p`q@??p`sx@usDwui@avRi`k@thDajVt_HztJj`J??uu_\\{iKghl@prGcq^wtAwoZifLexQgw^egSakRmj^}~u@ux" +
                "_CwwMuwv@_vPg`sEb{@q|o@u{b@ybiAqaA{}iBgaEyoN_q|f@?d_a@|raA|hu@pmg@ti~@wsF|}y@{ci@|iE`lZvjQbcBjtNccPl" +
                "}Yg}@`pa@xnn@xwy@bpfCj~a@~qk@j_k@t_lE`vm@bd}@`sR{ma@h}Pth`@xbBdiWrux@rkl@lpuArutAjpdA`ep@|hxA}yVdn`@" +
                "oj`@|~Ki|c@fxKwbHh{`@htp@xh\\fd_AvbVdgZnhUvyDl_IrwQxe^rbFfkj@ptXjkJxs@nvNoyRjyHtsRtyBpuaBp_a@|e|@bb]" +
                "~q]x`w@rtZl``@hs`@~aEb{MwoMt_VyeAjw[byC|{Zj|P`nd@mpGbseAd{H~av@}kHhmlAdlFdhhB|ih@l_{@lZj_r@dhNbcm@fv" +
                "c@x{]duRhbE_aBrcO`_NbuB`jHty^sv^zapAunm@~fc@eg`@tiGwzF|nUa}PxnDqhVskO{wK_xTt^|iSj_NfuMw_WnxQoxm@drkA" +
                "epOiaC|uN`tTh{DjjdBfw^hoaAx@xrSu~Ltne@ysGp_yAj|Gj~o@zsJd~OsdBheKyylAwzb@o~y@mjCwbk@l_Pe~j@m~Mwir@xkN" +
                "vjC}ph@oiQ`oXztL~|oA_wg@|fFkrPuuk@i}IutGspRnqCeqQ_eKmsNqr[dcKzw^`kt@hmb@lwG|cj@_mEr|UogLbb@owvAexWkr" +
                "P`hC{{f@mfk@y|nBis{@qmKzoHwpNgvAcubAqqR_u[ucP{d`AazCyo{Apn[s}Pj_@gaHkyImi@pwPkrJp`GwdLsy@chTuvRkc@hw" +
                "R}|]pv@s~_@yie@gdArkWmuWewOukJ~_Ocg`@uBnaH|gj@ckLdKmrYcaTm_B~iUay^~xd@_oe@_dJoi^omz@jnBksg@mtNmq{@ai" +
                "G{xSgqRrxFwzFygEsjUifp@quL}zz@pgFgfSwmAqwPdk[ien@d}Fagf@_eE}h^_y@mg_DmxHarl@ffKkib@dq_@ie~E`Ecah@qmS" +
                "}hiCj{[_elB{dO}h`@f{XyncCwtUwkmBypWcs[metAm|X",
        ),
        locatorLine = "scmfGtspFnzU~kDz_Tbsk@p`q@~gw@|iAtko@vtp@z`lB`Mtg{@gzFfsVd|Ozw`AzbDj`mBt~NzhvAq}Nnxm@n`Azs" +
            "g@ibFzeKigCjvs@uxh@rhrA~p[dm_AnAraq@w`F|~u@gsI|pQ~_Ap`I{cFtqBiiEtbg@mn_@xbwAokAvrx@suXzuxAajA`yr@nzGtsr@",
    )

    private fun viaFrancigena() = WaySource(
        id = WayId.VIA_FRANCIGENA,
        lengthMeters = 1020500,
        stops = listOf(
            WayStop("gran_san_bernardo", 0, 45.86953, 7.16477, stage = true),
            WayStop("echevennoz", 15600, 45.80652, 7.25118, stage = true),
            WayStop("aosta", 28719, 45.73711, 7.32024, stage = true),
            WayStop("chatillon", 56538, 45.74885, 7.61236, stage = true),
            WayStop("verres", 74776, 45.66945, 7.68717, stage = true),
            WayStop("pont_saint_martin", 91182, 45.59943, 7.79902, stage = true),
            WayStop("ivrea", 113532, 45.46754, 7.88275, stage = true),
            WayStop("viverone", 132958, 45.42665, 8.04872, stage = true),
            WayStop("santhia", 149787, 45.36725, 8.17334, stage = true),
            WayStop("vercelli", 179382, 45.32544, 8.42309, stage = true),
            WayStop("robbio", 198026, 45.28773, 8.59480, stage = true),
            WayStop("mortara", 212121, 45.25045, 8.73209, stage = true),
            WayStop("garlasco", 232214, 45.19884, 8.91330, stage = true),
            WayStop("pavia", 257862, 45.18262, 9.15734, stage = true),
            WayStop("santa_cristina", 285429, 45.15571, 9.39857, stage = true),
            WayStop("orio_litta", 302070, 45.15651, 9.55721, stage = true),
            WayStop("piacenza", 325523, 45.05153, 9.69231, stage = true),
            WayStop("fiorenzuola", 357577, 44.92908, 9.91064, stage = true),
            WayStop("fidenza", 379407, 44.86784, 10.06236, stage = true),
            WayStop("medesano", 402617, 44.75540, 10.14036, stage = true),
            WayStop("cassio", 431637, 44.58851, 10.05975, stage = true),
            WayStop("berceto", 445219, 44.51420, 9.99323, stage = true),
            WayStop("passo_della_cisa", 454510, 44.47158, 9.92850, stage = false),
            WayStop("pontremoli", 474066, 44.37692, 9.88320, stage = true),
            WayStop("aulla", 505371, 44.21473, 9.96884, stage = true),
            WayStop("sarzana", 523736, 44.11295, 9.96012, stage = true),
            WayStop("massa", 552795, 44.03602, 10.14318, stage = true),
            WayStop("camaiore", 578345, 43.93903, 10.30097, stage = true),
            WayStop("lucca", 604865, 43.84269, 10.50285, stage = true),
            WayStop("altopascio", 623512, 43.81366, 10.67631, stage = true),
            WayStop("san_miniato", 651795, 43.67955, 10.85045, stage = true),
            WayStop("gambassi_terme", 676029, 43.53920, 10.95430, stage = true),
            WayStop("san_gimignano", 689690, 43.46767, 11.04342, stage = true),
            WayStop("monteriggioni", 720505, 43.38988, 11.22380, stage = true),
            WayStop("siena", 740980, 43.31914, 11.33125, stage = true),
            WayStop("ponte_d_arbia", 763485, 43.19095, 11.44877, stage = true),
            WayStop("san_quirico", 793907, 43.05844, 11.60562, stage = true),
            WayStop("radicofani", 827370, 42.89647, 11.76784, stage = true),
            WayStop("acquapendente", 850893, 42.74352, 11.86697, stage = true),
            WayStop("bolsena", 873886, 42.64475, 11.98705, stage = true),
            WayStop("montefiascone", 890747, 42.53742, 12.02971, stage = true),
            WayStop("viterbo", 908079, 42.42206, 12.10510, stage = true),
            WayStop("vetralla", 930534, 42.31992, 12.05546, stage = true),
            WayStop("sutri", 952861, 42.24077, 12.21515, stage = true),
            WayStop("campagnano", 978285, 42.13958, 12.38179, stage = true),
            WayStop("la_storta", 999802, 42.01112, 12.37760, stage = true),
            WayStop("roma_san_pietro", 1020500, 41.90263, 12.45818, stage = true),
        ),
        frame = GeoBox(41.58527, 6.71579, 46.18693, 12.89907),
        line = "q{}vGyjvj@?pJnKkRmJl]k[vVnIw]baAuf@}vAnXor@or@hxA{nA{oCrcAiDsoAlZf^yl@dCcgBk`B{WirCgfCjV_dAaaA|kA" +
            "g|@gxBvfAqfFwaFv_@wZsj@r[b[yh@{DcbAcv@x`@ks@_}@hZzDed@dIg|@wz@p]_b@o_A|kBwe@mbCznAjSsiBp]_b@qt@ofAmtGevF" +
            "kYo[gl@pIgg@ye@wJspBckBtHga@mb@fScH}WgAcy@sr@hh@qxEqgEwLi}AepApI{x@uw@y]wdAkgAuF{jAwgAnEgxCcdCmPw]qo@na@" +
            "ypAskBn@uiCasB{Q{pAgfAtCabDihCgJcdBwuAie@hJmz@kKs|DmhDdO_x@az@hoAqx@__Cjx@izAquBvKb^g_@tGuXyWty@vFqdAziA" +
            "eh@obBhs@~VkmAjQoZya@~w@x_@omAxb@eTwk@pOge@ae@vHpWwj@n\\m[sg@pX{y@cx@pp@tNi{@d_A_e@ctApCc_@kYyW{w@{{@bIo" +
            "^ua@vaA}w@weB``@po@s}@d^}aAq_AftBc_AmmCkAai@mb@do@wZa|@hQmxGedF|Ls_@i^|y@eGakAnc@oiAabBr[pPwg@lt@aI}}@pl" +
            "Ao{BcxCdj@|H}w@`Jam@ej@lw@s^ehAfJlXca@nZc~@c_A`x@gXscAdCy]oY~v@iB}jAvoAqn@slBxr@`K{{@fQop@ky@tZvIgg@`d@s" +
            "|@slAfGjSsQtjAfSgdBx@cz@ar@{W}`Ai|@cpAmr@ojBgNgk@{p@dOeoA_bAuOuXiZl{A}sA}mC~JypCmcCrb@ga@eu@f@hPuNdj@atA" +
            "ixAoIsp@up@jsAo}Cs}CrCmnBq|AvuBe_CinDfb@otB_dB{P}g@ms@xJwt@wo@|eAmRu{AnTwVo_@jMc~@g|@nPdH}SzOqT{Yc\\g{E_" +
            "dEzJuQyRhdA`@eoA|Mag@gk@oQcFuWfKdBeMfLekAm|@nsAaiAqyBhj@wIws@~Y_pBe_BsSgJcX_PshC{nBhYwIm]eCguAqdAps@oa@}" +
            "fAkBut@es@dSa`@oc@|UpHae@lWqq@mv@aFk`D}nC`x@k{DecDtr@|Tk`ArSupCw{Bpo@d@e{@Kc\\yUlYac@_o@nA_c@k\\edAvIylA" +
            "D}MsJeZjBm]oCqZiUq^o@cd@zNojCyoB~YnAe]~Ecj@ua@lNpBoPzEqbFw}D{SkzDa_DnIcXkVpn@qC_}@bx@ucEmfDl]aXwf@aDszAi" +
            "hAvVizAykAt]ik@a|@qSqk@uj@b[e`BedBd[mx@cz@bk@}TacA`Cob@k\\bn@w]k_A}a@}_A_aAwg@}\\au@yE}_@mZhj@wiFokEuSah" +
            "DukCzG{aAyt@uQkOq_@mGgyAglAt[}_@}m@`Dwx@am@xcC{`D_kEj_Aik@gvAuHge@sg@hd@ywAgvAmf@_Noo@BqWgRzk@{zDq|Cu@ab" +
            "B{mAh}@}r@wuAdm@\\ur@tg@agCosBzb@e]_o@oNcRc]pUeuAogAfe@qKqt@kRidAw{@lO_Wo[gTudD{nCxQ}CoTPcm@ec@tfAyk@{yA" +
            "zWmhB{vAcJsCqLrAycB{oApSmHsWrb@azAwwAsBur@{h@liAezCiaDik@otBgnBbp@geA{tAzJ{xAkpAqtAyhB_bCgSyo@uk@|Ief@kb" +
            "@}Ig}@ot@cgAwf@gyAgFyv@so@fy@aLefAdVinC}zBlu@}zBeuB?k~@av@_TwGoW`Eu{BucBfh@{zBymBkDel@uk@tZip@qu@|\\wDgb" +
            "@l_Ak{Bc{Bdf@opDwqCaDa}@yp@|UfAsXvHqZiW`HilA{}@_`@}eAqqAtNelAm_Aw}@w[qoApCuc@g\\~k@yeAyiApDoaAiu@tb@wCsi" +
            "@dTojA{~@qNE_TjBke@u]fYwUcl@oR}BqUbCui@_a@zl@cq@ggAoo@q|Aq`BkGxUaTyO}AuSwH_]}]i{Akb@}xB}@soA{_Am}@gfD_yC" +
            "zn@ssDkaDbl@qx@_uApHguAwgAeMsqEchD_u@eAg`Ao@yd@}\\zy@ep@y}AnDomCa{Bxz@WgbAdHyOqQhsAjjAowBhzBg`AiqCfpAsxA" +
            "{wBmEodBoqAzeArH_oArwBmmGieGdi@qCgp@nf@tw@}dApBcaCyeByr@gLw}@hs@{}EauEza@is@ix@xoAygFoiF|nDc{Fe`Hz\\hFuc" +
            "@vk@cuBknBf{FhdA_nHzNgdA_z@rg@rJmm@~h@{`A}oAfh@`Emx@rWoqBu}AcXeRqb@db@}lA{pA_hBwpD}rErHi}@er@fX~Le]tMocB" +
            "upAxb@ek@{~@`L}sBymBwO}y@}{@p`@m|CaeChYrIm]uTwlD_kCe^abAobAzQ{}AsnAa]mLic@lCos@qp@tWueAsdA|bA~c@gqA~f@wb" +
            "C{aCrPyrCswBn~CfD_yDh_@{~A}sApc@vx@}_ApUfE_\\jC|\\u\\|JiZea@fgBlZ{wB|w@a|@_`Bnj@|Ewt@nBnTiRhw@kRw`Ae[kqA" +
            "_aB`rCyDyiD`e@ox@y}@hStT{a@hz@r@ubApqAdlAe_CjWwlBgmBti@Yqv@mPibEyoD``@ac@or@dQmnAgfAbPsEySfcAl`Ae}AsBht@" +
            "er@p`@dp@aw@biAtKo`CjWeq@mp@rYtn@}x@~m@dYe|@lgAjmBiaCvh@_f@oaAtZk`AiiBpf@m_@}t@dl@rJuu@rEmj@od@tnAmt@acB" +
            "peBnw@_}Bz_@x}@u}@rlAxC{cBjMtk@wi@d]aGci@joAhbCi_DtxAvdA_lCdUbaCqdC~[uHof@mYbwAoyAxuCd_C}}Elf@jDum@nr@dw" +
            "@yrApc@hBei@|e@ly@{jAf]wIqf@`o@bb@y_A~o@eQq~@feBtwBu`Dvs@d^{cAbZsL}d@rn@pj@kcAtVbv@iv@wAbl@ye@eK`AgYjSxN" +
            "cZnQndA}iAWh~A_qArp@zYseAfNaZa^hr@|Ke|@jjAi`Be{BjFhOoOjUeY}b@`A~s@s`A|u@cg@ewArYrP_b@pA_iAm`Ax_@d\\mr@vO" +
            "fu@aq@nUmFmZ~{@taCmcD`mAvc@}pBdb@fkAimA_Adj@}o@fOpFmSjv@kXwdA|l@vF}s@oA{dAm`AzcAit@ubBvQq^ed@t@c~@_w@f[c" +
            "[uj@d`@\\ol@fLx{@ww@d]nJmf@f_@y}@emAeX{_@qe@hNan@ml@gHmHqTz]uTmm@{E}Zmc@hu@gCq_AnKyK}WkFuQwShwAcSahB|]}z" +
            "@scAmY{u@kiAxY{N}f@bLvPyTt[yUon@|`@|Qqj@~W{a@yx@l}@uM{jAteC~d@kcDm@|]o[xcA@yvAxf@lh@iz@rn@oe@qfAxxB`IsyC" +
            "fIkWyb@tq@gSqfAf_@jJil@fB}g@}h@vz@_DswAnGr_Ay|@hmAzh@mdCtOvcAm~@dh@fg@}_Ax`Aa_@mfBvkAjF{cBnEp`@e`@zWpG_" +
            "\\~a@{Met@hPax@ys@pc@ef@mv@xMxWs_@zTag@gg@kRgAmZe@ur@mp@rVyQi^cJsKc^`K_q@_o@pX}Qwa@gNoe@ce@jE_]uYpwAaSqj" +
            "BzCcc@e]di@{Ku|@vKi_Ay_A`e@lM{k@dE|_@o^f}ADinBoHcmCclChgB{fDirDw{@grAsnBbj@{m@ckARytBsfCyKcOgVnIgTmUsRdD" +
            "eVnKc^{h@aMkIuT|T}Iu]bQ}m@_w@cNcPaZn`@_uAy`Bf`@yYgl@znAkEckBbi@wd@_w@nj@gbAqjAcR_s@{t@xb@jZqtAxDid@ch@xc" +
            "@yc@st@kKoCoPx[siBg_Brx@}YoqAtQfRy]zWshAcdAoEkc@ya@zYic@_p@gGiIyM|tArY_nBf_@iP_h@njA}uBeaC~LktBmgBdnAmKy" +
            "eBxUo^yd@jMoe@cd@_w@_zD}zDdMsa@ia@nlA}iA{kBeFmUyXpe@as@ucA`n@ap@qrAli@gLex@lr@smA{qBnEic@kd@_K|IwS{Dgh@k" +
            "q@aSqByYfTuqDibDtg@eAcr@sJiG_PhXwx@}|@nl@oCgy@lcAyzCosC``Asa@yoAbR_y@ov@h`@_Xek@w[ahB{_Br\\q`C{lBr\\aA}e" +
            "@z[keAshA~C{bCalBeOq_Ae}@bg@mkGkmFym@cPydA|@{c@k]c_@mKkj@bGg`E{fDjw@}RocAleAorCuwCpk@yLmw@|\\ajD_xCtgAup" +
            "Ba{Bxh@tRkt@xu@ma@grAbz@unAq`Bke@ko@q`Avp@mPey@~mCwiC}lEld@y{AuwAna@qXkn@pQ{kAyiAmj@s|@yiAg@ubAav@~TiFiX" +
            "rVewAwlA|ToVg^ni@|Cut@fy@km@asAdTfJkY|]so@ix@rW}D}[|Scc@kg@g`@}s@mz@lKqa@a^zOrW{]dhAiScrA~{@k_A}_Bnb@cB}" +
            "s@qD}|@it@vc@oj@yy@jJwdC{oBrVkp@ap@|fBca@q`ChHd\\m[tc@xJ_q@la@oq@kfAnx@tO_gAlq@ouAajBtj@gG{p@pnAuoAiwBn}" +
            "@nBq{At^}i@maAfh@gKsq@fN{O_UkC_fAo}@l_AjU_uA~fBuc@uzBlSmZw_@f|@vSslAyJqSqWzJkn@gj@|mAcrBmeCpcAwh@{qBbn@e" +
            "fA}uAn|@_j@anA|yAdZ_yB|rAweFqaFvOsM_Vrc@rNcn@ds@st@{gApJwq@kj@~p@cSgoAvFhYk]hd@oOss@|Q_s@o_AlXnDoe@lHuRa" +
            "SmOso@gm@zg@Oy_AnXgbAsbAmUquEieEtTm`A_qBhr@{^_hAn}Bno@kdDnR{t@st@mRag@sl@xYiw@_y@}Zez@u`AtpAgo@mhBgIqv@u" +
            "p@tNal@il@eq@qTi}@sTu_@yg@hb@_dBs}AqXhEg]e_@qh@wq@`Qsd@on@|WiP{h@|Y|Qcj@bcBaeDmuDzo@hX{}@hd@mIqw@pK}Xu_@" +
            "zXfYcg@dl@wPcz@nKdt@uq@l|@dAkgAr[aiAafAob@orAyvAzh@}lAwuAa^sNid@~J_iAycAsf@kZut@eJ}aBi_Bh[_dA{`AfyAovAof" +
            "CzUilBmlB`UsZq`@b~Aqx@m|BvMue@yh@~ItPkTl_Bs\\krBxv@r]eeAdp@ot@esAtXpSig@oCilAicAxcAoSquAkCsr@gj@ju@kZw`A" +
            "|]lGiy@bcAkfAccB~W_Cq\\|n@yzAa_Bjj@i^afAzc@k`AigApl@dSgx@hdAyo@uvA~eAw}BgoCpRdNof@pa@}g@sx@WaUyRfaBaEk|B" +
            "[q`@k[`mE`o@y~FgMyi@ef@tbAybBwtBnf@oPet@ta@lTui@|Y}p@_u@eh@qi@eaAlj@qbB_eB{Mi`Auy@w^uJyd@lU{aAs}@aIuj@_k" +
            "@xYko@{s@`a@o@qh@gFePuPjVue@cs@bO`OiUxRkd@cg@vLfHkQ~h@q`@gx@eFmpByeBzGkJwLte@bl@q|@~~@i@cjAzz@ywB_lCp[~A" +
            "}u@@ix@ey@d_@fd@a`Ads@kSkaAjJb^eb@fsB_y@ytC~Eed@c`@f_@_`@_o@rS`F}X__@kw@iz@lWgx@k{@T}p@mh@eh@g|Aa|AfDak@" +
            "{i@njAk]ozAl{@my@asAxc@`Sgq@hq@uk@sfAf]xB_f@qAaRsR`jBcc@meCfxAclC_vD{DwbAwy@xY__Ac~@p|@_WsjAh`@hHif@xSoY" +
            "}f@nDiw@et@ht@af@_dA|rAyQ{dBt]nMsh@vk@ik@maAtc@cA_i@d^cg@mlAf{@v`@crAz|@~bAu}Ath@|Csr@tD_v@_n@|d@odAigAn" +
            "vBosAgzC~lBonCirDhaAejCokCvp@}Cox@n|BudAodDlG{{AsoA`\\mjAkgAxy@~l@uqAroApO_|Adm@sd@a`AxfBbJiuBeb@ai@uu@j" +
            "Dql@cn@ddAk]gqAaFssAmtAnRaH_\\~Hp\\g\\vWqbA_hA~RvBcWt[cmCmaCxVxB_ZvT_x@}gAuUqPu`@pZ}kAkiAdx@e`AcwAp}@__@" +
            "u~Ab@ck@{h@jKdNsSnxAg}@w|BvYtLc_@l{@wd@u_BpXiDu^jKzUa\\jr@oj@giA|o@sJky@rw@r_@olAdb@cDih@jm@ey@ujApv@w]q" +
            "gAh]b]sm@xz@ysBkdC~|@rlAonBvf@u~@ifAjiDa}Bk}EnzAf`AiyBz|AyGchBdIcp@gi@tj@c~@_lAhsABc}Api@kwBepBtc@}Uul@~" +
            "Pep@in@vo@_We~@tQ{a@}c@~_@Egm@f{@qgAibBbq@_dBugBnk@kU_z@ri@bSux@jQmVi\\zj@j@_r@mAzWoWbq@jTgbAmHj[kZb~@nM" +
            "{~AhCrcAa_AroAeZ}nBlgAliAmpBbLzzBcoBur@bXwdAUdyAitAnYxVyc@xe@uTyp@h^hx@c{@p\\tC{d@tf@gtB{lBeTit@st@dCcz@" +
            "_z@~y@iv@cqAhr@cFibAfQynBw`B~LkDiOxQv_@qa@jYwNyo@vj@eaAckAaQk^u`@hoBe{@qlCgBuk@if@~b@alAmnA|RkdCw}BtR}Qi" +
            "_@`l@pz@{kAhJyGuNdUuoBqfBeB{xD_gDrJcTsW~\\~Bkd@bCyr@}m@n]k@_c@p\\in@or@t}@seDk_D`}@idBcqBhNirAkjAt`@_m@a" +
            "v@eF}^k]d_@cEyf@y_@_uAurAqNizFqyEr|@|E{eAx|@imAogBzBm|@ar@z_ArHalAdq@|a@kbAf}AiXkpBrj@li@ufAncAci@gxAxcA" +
            "dc@sbBfdAunB}`Cxb@~Z{q@vv@mSadApa@jKmj@fb@_[ap@b~ByPy`D~Gon@gl@~wBuMosCqCla@c]~e@aQmq@nMb`@sh@iIbk@ku@de" +
            "@fE}}@\\~^uZrXn]wt@fP{RkYzO|_Asy@b^fR{f@`n@mUcw@n|@udAgyA`n@c`AgjApp@kxBkwBxSaSm[vN|RmX~iAglBy|Bjj@frA{v" +
            "AxuAzNkjB|_@yx@gcAoF{W}VtRm{@ggA|g@kb@wtAnFnVkUrTaF{^mMkh@uhBrGcNeXl|BvAqpC",
        land = listOf(
            "oam_HehlwAvcdh@?ykg\\?clGljZwMvcBp}@|pBtoIdvFtnZbuFtnC~pC{q@tyD~uAubBp|AtLv_DprDqm@te@jtE?se@nxAv{Fk" +
                "jCdbGp{Aje@vfAiQ`pFryC|iEmeFq|AerBzq@etAdcCiyBhO{DvgAviF}Wjq@kiDf{@}X|hEhbEa^~{@jxCmZnz@lZkFhkAx{Aq`" +
                "@`n@vl@?`jHzzBc~B?ti@ltAui@|~Bb~Bb_C?tHwgBfjAcaArFx`Fcu@lhEnm@ti@}bBde@uZnqDti@vj@ny@gcCvrB_@b_CmsAr" +
                "c@p{Aa}Fte@}sA`jHetAwi@?ltA}i@ui@ym@ti@eKjeDorBnqD{e@ym@dtAc{Csb@owAi{Amt@v[zgDmfAd`C}~BmsAkmHrsEy_R" +
                "~bU_iA~iFe_CmtAyvC`wCakAgaD_[icPmv@piGde@veO{q@~[w`DkTeYb_A_iAa`@_y@vjAecBgkAqmFqC_wApzB}dA}u@aRmrB}" +
                "e@?}bCjiDotActE{e@piHszBd_CkaApC}Y_yAef@?ev@vhAivJbyDobCgm@ieDddBgnDwNdoCgbOavDeg@y_@jkBebBp}@rTgbCy" +
                "iBy{^a{Fj`Gi{B}qBsFifN_cCx`EotAnkFsc@}qBikB|WqcEjjDimLh_RiiBxtIqPlnCz_AhhBhhC`_A`yB}XzSieDhlAjcFb`Ab" +
                "aAfn@`pFv_Dz`Grb@hcDio@b{C{q@}iEe`B{iCqjB|u@kd@z~FazAvkA~YzlBmaBx|QemCduFz}@z~GpjBpzBu~Bv|D~tAtdAdbC" +
                "c{A~z@ngG~uAtcAhhBaa@vn@weB_zAujJdxElbHjhD|oBjrA|pZ~sMhz^tpUxvdAnJlrA{pFe~C_x@n]w@geB_vA}X`lAc_Co]gi" +
                "@mtAltAgM{hEbt@_y@?ltApm@?eK{iCacDuf@anAi_GwcCawBpiBvtGgpChfD_xAlWb{CpkHloBxfBdrBqz@yAffBeeAhjBba@nw" +
                "A_cCvi@ldBzmAnw@ef@nz@aqEze@?fh@f~DsRjoAo{@yNqA~jEtbBh~Fd}CjeFxeIjeDtcBkoAjtEltAnk@feCtrAks@`wCdbB`|" +
                "@`sDa|@rxChPzs@~cCp`@tzDazBtXiiAofB}sBm{CdKbc@c{BviGgn@br@|tAxkA}tAhyAzT~iA_x@vl@ghB`AavB}e@hm@emDcm" +
                "Hr~A~x@`lG_oCx|Lgm@wi@fcCc_C?twFbaAp}@a}@kGigCmtAfm@vjAqzBnhGg|Eni@?`n@vbCltAotAulD{mB{fDzmBdmCuuGza" +
                "AhRzzIayM_l@kpA?zpAqm@?w@gfBvdCgbEhiHdcCjDntA~pJdhA|cG`jGktEt_CmnCc~A_rCrDeWdfAntAb|B|iEr~A`o@uzC`|A" +
                "|r@hPtfAti@?le@kiDpjBxo@ddAh|F{{HdeMaAraAvfBfaDle@??mtAngT`pEbmGee@tyK_nEdnUfL~cYohFfvCubClaG{q@|wKe" +
                "wF|bT{rV`tDujKzyIadJtuFkwJftBirKh^cjHxcEsjJ`yBa`L|pB_rBb~d@mwz@beL_r[vrCykMu`Cw`EjEghAvnJegKplAkdFbr" +
                "A}v@dbBhn@nqx@y{^vtGs`AbtKerGtlVg~Dlyg@knN`oRo`J`kMqbKnaDyjAbcXkj[p~Quq_@d_ImcGlcGsbJly`I?tgBjnKlfE`" +
                "}KjpAjqAouAznA}aCtJyuBa|@imAguHoqHebJ}w@_hEcwE~Lu}CxcEzXldCoaAzfDoaNlqRfm@~wLl{Db}Bz@zcCu{AvfBoPx|Dk" +
                "~AltFxN|rAtw@tf@xpFuf@}d@txEaj@|g@}_GmdAomOf`EcqM~|IkiD~fHa_Gvl@wcOjoJ{lJt}JyaH~kLcXjrAxb@hyGuv@di@l" +
                "g@rcKr}Af_EzyDwhAdHxcEeoCrwDpp@b{AykBnxB}zI`m]qD`pFrmBnhRrhDddM`wC`uC~\\hjCac@nrC}~GvaCyeJdsG_jLbxOg" +
                "vB~cIi`@hdQ}dG`nQjpB~sB}zQnoPm|Ox`RyvNhrVszCzePcfE~sCaqJ|v@oeIh`FitC|lCq`K~eTmmDlrBuh@pmFqmFlwKjVnmP" +
                "chEzoBy_KhqJa_GlvAmqThfNkqLrgVs`AfvHaqEzdQim@?ug@`yB_AhhCti@gm@g@ptDs}BjmMdKpiHxgIjjD?lmD{nBxdCgk@lm" +
                "DkhDb{BcxCilA|QsuKw{FsvCm|F|HamGnpDjd@dyDepHhbEkc@ffBayBhR_~EraMwgGdaBokE|`HuaCphIi|Fld^a{AquCucBoz@" +
                "mdGsCcmBgjAgrCnwAg_Ed`O_z@tpHsFvrHbaAdsGvxAym@fz@~mDc~A~uBwtHhhCqrEevF{yIihCqnEhTsvEccAymR|qBiuZtxPy" +
                "rKvlK_sC~dHmaB|w@qyMjkCg`n@f_EwsTvoI_zE`wDmqCfsGwbHx}G{uEx|Rj}Af`DcmHlrMf_@tdA}`CjgEtGlqBfm@ui@vi@lt" +
                "Ab_CmmDt~B~wAbc@{pA|W|vAwbCxlAecBbkHadJllPghAp_K{mGpkH}{DjmMqhCnzAdZphHakB`yA{|A`jHklCti@oqJpwYr}Bvh" +
                "BvnDzQgpCfoKufAeKwpC|rBkaA~mDcrAduR{vCtcN}JhhNq|A|qB}UzrKzSt|CbtEdmJ?nqCrfEn~Jza@`tDpiI|gRl~BxeC`yBq" +
                "_@ptCnxArrA~qCppE|UtdAltAxgCpyNtgE`cJzyC~pCtkJfhB`pF~eHnqCveB`fDs~AlWnpCrzCbwDxo@vaD~oCfeCdx@zaFtwE`" +
                "_M~_E|}`@hsCvrH~j@zbGYp_Wvi@lmDio@ldGho@v`D`{B?~m@|hCtsFrwHw\\`pF~j@pmA|uDplCu_@zhM`lBvrD`bAsSlvBbnD" +
                "omAlk@lLrxG|sA`}A|{Eb`AxbIynA`f@xrAygBpmAyXdxCpiEd_IugA`h@zD|vIbzB~|Dl{A|YdlAyrA|iDruDlsCl\\xcAhiCx_" +
                "AhYrHnnC}qAtq@xqCrPpSdsAyT|lDlm@t~EyvAfaDz\\daAz}@|~A``DmI|}A~|AxdBKjYlmGhuCzqAnnFloKl}Atf@x[{`CmiAi" +
                "zJdSibC|m@a\\zkBzmAbt@niB`qBnQjzB_yAznD`tL{H``AsnAte@pa@nlIdfCnqA~z@lbCy^vdD~w@fcNzbAroC~kBzlAvlDay@" +
                "N|mE}rApfBoyAfzGyLbgDtjAtwJ`dBd|D|_C~{@btCnAtOakEnz@l`@tEd{PenBeoG_tBrQ_pAlxBfe@pcOs`Cp`AeSthJkfAnxC" +
                "u~Bwi@|sAp_Kh^ihBziCwxArqAy}Ftw@hdAfL|tKvtCbtB_u@fjFi_DxfFy{BiaFun@jh@gp@hnDidBnl@yFnzEs{AlvGimEzjC{" +
                "l@dwFnfDdgCou@dwFwnGniHpj@x`Cwh@lgT~Z`{Cgq@~pCusIqiCa}@xhAepIjrBkcClvGljDh|I~JrjTsvQ?}e@{wGeeA_vBy}F" +
                "apE_sCzTfeC`eJqSv~Cmy@fdA}|}U?",
            "kh_oGykdwAx`Ek{FnyE?mpFtiHwi@?vi@omDg{ErnGcc@~rBvvAhlByo@~qC}e@ui@in@~^ecBknBodInnE__K~sAxaEq`KlqCfk" +
                "@~bImtAftGmbG",
            "_godGavv~@xlBhkAnqCsa@hhBvh@nuCj`G|e@qvB~eBijBvsBsa@rqAr}Auw@n[w[bxDkiDxiB{|AxcD?joApgCteAwgBlx@z}At" +
                "sFknAb|BpgCbaBuJfbOkc@zjCgxA|oBieDp`@{jBa_AsaAidCui@}aHnxAgwG?kbGym@vi@ui@}pAut@?zEwtIxyAn\\rc@u|Cae" +
                "DssEsbF}rBg[ylAtv@osBxuBilA",
            "u{ioGehlwA?~oAyaFvxG}}HpoEcrGyOme@ltAlWnw@_l@rf@ivIfh@eoBjeEauJbaB{{Ar{BmtAwl@soBlw@kRmw@fj@asCdmDcv" +
                "EgAmlDs|Bq|@sbEfj@|bA}tAwi@yl@u}DtwEqlLh_Fa{GrlIkgD`|@utGy_FkT}pBdh@awCvgAkp@hoKrEvsIcyCr_GczDfxAumH" +
                "xkAgm@|qHveC~i@wl@xkB~x@neHgKz~GozA|d@nzAxpEebCf|Eti@rlFe{B",
            "ym{qGehlwAuyAj`DmyEdzEylAgfBsFwbCeoCmZuY_y@c@c{@",
            "{suaG_boaArfAcmBruGkcDpiAteBehHj_K_r@{yAwmBkh@ba@ioA",
            "iqhcGm~ux@tiDw~CuiDv~C",
            "idzeGs{`{@paC}zAvwBfnAbfBzvBbC`eC_`CrhBilFsjCkr@wtBbz@oxA",
            "cgctGkokjAonD}fFrnB}cG}i@xtIzpMhuIqvCeg@onEavC",
            "o{~wFo{{pAsc@kpAjaAp^`^hkAy{@oY",
            "m|tzFkpyx@xnKlZouApoEw_JmnClf@q{A",
            "_vrzFg~px@po@mZdg@fyF_PlqBqfBjWsbAotB{~Ace@}f@wdBbs@kqAbvD{T",
            "onmaGqcz}@uh@oy@jbAoz@hhBxOuXntBihBiO",
            "qn~bGw_r|@fiAef@lfAxjAgz@v|E{fEcuDlpBgkA",
            "ayqeG_x`e@gSwi@ds@_x@tzAqFpkAh~EhSnvAimAxaFgy@}v@bE}lDkn@c}Dui@iI",
            "_}qoG}`}uA}oBifCdKqzAdbBdf@`^fhB`zBbC`xCqyAksA`pFg|EegA",
            "qtmtGodgjA?kkBfx@wfB|fAtIbbAbzCgNvfBsqAlXmaB{qA",
            "aplwFeqbtAaQrzCr_AbxD_cCj_G_pEgbCotAxl@?e~B|iDwcOpzB?ltAfcC",
            "__ryFedoq@lsAnrChxHn\\oLzdFa~G_wBgnDocHi_FuLxBqvCubCquCtoDuaBhsC`Cfz@|v@~l@bgJ",
            "}gpvFqpwz@ziDstEh_BbT?jpbHenKpqBakBb_CbG`vCnqC|}Hqm@d~BktEe~Ba`@lnCdcAvgBnjGr{A{vDnyA{fEth@oeBonEguH" +
                "orC{b@nrCqtD~mDaQfjAcx\\s|NomE`b@wtAx_EajBkTmzDc{B?ym@~hAiQrDweBpo@wk@fvGzQfvGgvGh{AmiEfiA{xTxmA{|Ia" +
                "DqiGoaDweNyqDi_Fa|Auh@avCgiLvi@kxIqpEcjJymL}wKim@vi@{pA}bGqwC{kBcaFi{HixCq{A{lB{}ReaC}lD~m@ef@acEweC" +
                "gnJyn@izBisJduAyn@aDayBjpAc_AtwE`Cnj@ccAskBjToy@c`AbfD?}e@{hDltAe_CquCwLh`EajIwi@?vi@stEt~BltAziDstE" +
                "zlBbe@dqCce@itE{hDaxAlsAkc@kmAjc@srFoy@ebBny@{r@hm@xm@fjAwdCo_@}rAli@wi@ziC|XhxBfeBixAvi@hxMzhD?e~B_" +
                "xAxm@eg@}qBnMedAvz@kTj`Bp]mi@wi@li@mtAeeAc|AzEkkD`iB_dH|fAdfA}fAndHti@fgBjrElu@jrAxlA~tAo\\pBhqJfm@x" +
                "n@fhAio@aa@khD~wAstEqkBgsHpRayBjiD|mDjkBkcGjnBym@_l@c{Bb_BudB~^sxCr}ApkGvuB}u@qRr~AvvAvfBnz@ccAmdAcE" +
                "teGstEjlNi|FhtOgjAjqAu}Cl{Cs_A",
            "ozr`Ga_hs@_fA{r@{oA`sDwy@mYyE{dF}wDgyRaq@cEitCdpIoxA`{@lu@`{BwfAba@iiBgyEksAjhCjsAlzJom@ym@__Er`A_{@" +
                "yQv]_rB}dAsaBp`@ilA{fEc|Bk_Ak~FqhCuJu_Cc_Bin@bzBkxDc`A}eA{oAi{@y`F{mHfm@ltAoxAui@gfBfxAibEuWeaBmoCc_" +
                "CqyAs`@ui@hm@eI_jFqwCukKkmB{yTijA{dEixByQazHktK{R_gHzmAs~LltA}lDjtE}jDsoMyyHqgCnz@yvByp@ilBpa@{dEbyD" +
                "emD{iDsbFhPu{CezDc_C?ytCvgBo~DiSyo@geBsc@wqJziDmcG`cDp~@neCedBftBn[lxPauBd{DdIzfQliEjxI?rpAxm@je@mtA" +
                "~mD?jiDe~BltAuyEoeHjjCvqHsoFr}Sa`@|bCimAx~JltArmN{iDthWvl@nrCwl@~hGnvA~tBxgD~xXfpUboSlv@nsZwl@zkCrvD" +
                "p{@n_@?mtAbnBhPneBnxAy@~qBv`CeHwi@vsIfnD|sAdi@}sAkoAqiIvw@_x@vwAjUr|BptCxo@zgDb|BjmBfNhkBtmD?feAoyAz" +
                "_BnyAfm@se@d_CzvJvaC{mAb|BzmAe_CwvFrxIzhDdh@veBu}B~iFikBdeM_`DsbAq`@_wAkiDhuI}~B}qA|~Bz_Gwi@fi@gm@gi" +
                "@fm@t~BoxAhkBke@|vKepB`sDeWlpCgkA`}@qm@btEkpAmtAqkBn_KywB_\\edAlqBogH_sCbg@yjBerBumIyzBkqAqsC}eF{nBt" +
                "cYq|@jnAs|B}u@rpAlmPspAgm@gm@`jH{r@k`GouAwcCyyBwOcoAbdAa`@qlGizA}jE}bBxmAa_@heC}sA{~FmtAltAktE{iDqgC" +
                "`uCia@fiBhpEli\\cpAvj@qgBefA}sAlYszC~nDw{@ylLcmB}tA_h@hnAmgA{s@mxD{kNylAsH{_BfeCugFpvCbWpnFofBjqAiq@" +
                "lpBkTrmGspAym@qm@rtEspAstEqm@??|mDa|BecBwvAdcB",
            "i~pvFifxuA|g@ajG`n@vk@bt@nbHaShlAkkBiOuKeaC",
            "mhywFypqtAnk@_vAvkAhgCj_AkUg{@deAhQn]}pBiRw\\ikB",
            "ifnxFcyjz@~]{lBddAbaAk`Bb}ByAkqA",
            "{tuxFojmz@hgCvxFx@nuC}vEshJxlAse@",
            "aezxFanenAvLs~AttA|oCndBxn@p~@qa@|fAnyAeqB`}@cpBeg@clB}mD",
            "m|yxFezlmAecBwi@xwBmZf\\deA{p@?",
            "mj`yFkysnAst@gkAh_ArFuIrcA",
            "gvuyFweqy@aRc`AbbAlVao@th@",
            "kknzFaalx@_]gNtj@_y@r~An{@i}@|rA_n@efA",
            "_mvzF_ezv@lI{p@~jAvgA{bA~x@{a@}XhO}u@",
            "kaxzF{x~w@lZs}A`zBtbA_z@hmAozAkr@",
            "qn|zFcc`x@{e@|sAao@ayB|uAbd@",
            "s{_{Fibfx@dZp`Aew@tg@ecA}rBd`BtH",
            "wib{Fwj`x@hiA{r@eIhjBy~@de@Is|A",
            "usi{Fapnw@raAwMse@p{@_[yl@",
            "{no{Fcppw@f[q_@vi@hm@g\\fkAsb@cFcE{qA",
            "yp}`Ge{wbAh`Ayo@{G`~@ffBmXovAr}AegAmrA",
            "yxweG}mrf@oPyjAv{@mYtJt`BzzC~rCp{@ppEslBuIya@e`C}nBkkB_NwgB",
            "gtdhGydn{@zUin@dcBfl@ab@~wAecAiTyRs`A",
            "mvshG{y~i@tp@{rDcCnbFud@xY{FmiA",
            "q_tnG__kvA`iAfhBw`DvdBtvA_nE",
            "mocqGseasAznA{VkEvfBlbB~tAu~CiPmbApzAdu@coF",
            "gypqGehlwAm@b@Ac@",
            "uxntGgkujAct@ufAdZ_ZxjA`{@dcAlqCsq@r~@mbAmjD",
        ),
        lakes = listOf(
            "_~pzG_`}h@zgBizGvtBwtBvtBheC~Ix_Hw_Cfh`@luAhse@|}B|}BdrClzLpkBtwCerCroDuM~yJlkY`zTltE|uHsdDa|BomLkpC" +
                "eo^}z]qhAaoOytG_}Pm\\u}OjlKelt@",
            "ukxxGaw~t@~zArZjaK|tQlqDvXtaHwfAnnCr~A`tHhnPvsF`fGhpCzKr}EuiB`|B?~oAnr@fzBdnFt~Al\\xmIqyHfSht@gzB|nE" +
                "grHrzDcjDaqBwpE_m@eoBtp@}kDhzGgyFroDc`@acAbcAg`JonC{xIoiOscR}gGvqA_wDk_AuoI_oOm\\i}H",
            "o~bwGocgaAhbBcnAbfGf^~s_@h{ZfgMxmDheCtMi^mcCzfK_~B|qKhhDpZdSkmBvvLcyAzrBonC`UhpCxc@`x@lxBwM~sCu{@|}B" +
                "ii@yn@_m@|yEse@?iaFq|Ikt@se@ogE`qByc@aqB{rBzgBwMxcEmtEybNaePcvWabJmtEabJcxJw~FgoBacAwqA",
            "sbgcG{fbhAhzBulCxpJl\\xgBt{@jt@heCaJtlCgdGpxLssA`cAa|B{KyxDkiEccAi}HrsAogE",
        ),
        rivers = listOf(
            "ckz|Gkslx@gqDibPkwCy_FqmGc_CmqGvkAwbIfwG}dHt}BuxEkcFgdC`CgdHxfDqqEgNiiHavD",
            "u~p{G{edt@}mDkWosBs~A}qBanRciDesFixBwtHoqC_~WmmDarP?_fHg}D}wVmrBgtT",
            "mnz~GoqkqA`eJ_`V``@kcGm[_cHybDkeQh|F}nCz`AwcOe|CalRqzBqtDqPyfC|sA}eGwi@cqGbCglKu|BynLuv@ajSylAgaD}wF" +
                "gzFcjBchG",
            "{i_yGe|ld@crG}cGqwNcqGc~GwtHixBojE}tAexQy{F_sOeu@ioKdHq_LhpF{~j@`{A}lD",
            "olh{Gemcr@laIbkItbYtwi@x`EfiLpwCf_EvvBxfOamA`cy@dYjkCdqBjbFnrBdzP`uD|cHhm@pnFfgBtxD||Ibn_@drHzeQdWd|" +
                "DkwDtyDogGjt@k~S|fQkfDlw@utAzcFafD?omDnmD",
            "{i_yGe|ld@cs@z_Gbs@zaGjtDtqH~fHneH?h~FdyEnfGsmBd_DlaBt`Ctu^c_B|wE|t@~wRplGlZbjIr}Ab_Bz}BxlA`cJo]vrIb" +
                "aMvKfbC_iA~wBynKdmIouGjpLqsDzjDk_Ib|Ba~E~|JviAf}E`hN`{MrD~hFkzEvwP",
            "g{bjGa|phAzs@nwAlpBdg@ljWwyEtiDrzBvgBoyKb`BieDdnCqwCzxCmt@vnDyxHd|D{nBtqAbEim@ti@~wMe_Ct~Bo_KveCnZ`n" +
                "EshI|}UqyM`~@ayB~dH|rAnvAu~BbrGj_Gb|Aq`@jpAfkAti@}tAlnCzkB|dA}UltAt~Bvi@wi@|~BntAdsBa_@~cBviA|qBwl@`" +
                "sDveC``AwcCjlBmsAvi@dxErbGexEf{@`oEvjErnHplAdnHrtEh_G?dxEzoBa_@xaEmtBfuAqvBzmI_]j{BmtA_BylAb{I}t@|~B" +
                "u~Bkq@}qBbe@_tCzvDk{HfbCatCrpA?pm@cuElmDd_Ch_@uaBi_@mqB|`CvgApwBsFbmBwgAh}@c{Bti@ntA||B_sBv\\m|IbnCm" +
                "tAc_CmtA?ym@~tBiQa`@ylBx`FmkDvvBpA{_BjqBj~G`^xjBmpCtpB}s@taH~uBvpD~gF`lA`pFblBcbAzG|nC~fAr~An|EvO|mD" +
                "rzBx`EpC~y@r`A`B~qCdbBkpAjmBre@lx@o|@jyIb_BvYlgGziDvi@g\\xtJvjAjhCgl@fhB``@pxAhgC`vCdbBee@vtBneH",
            "m`ltGg~f`AtlDghAp{Fn@p|AcbBveHb_CbfDkoBb`HnlFdrMkqAli@aoRd}HmqMtcAcdKn~Dk|H",
            "}|avGkurs@ojAnnD}iDnrCihDbd@unH{fEqgCcE}cG|pByiB_|@_hNciUa}E_pDu_IlW{jCwfAexEcnHsiDadJ",
            "wfxzG{khr@fl@smH{`Hm{Usp@utGlGsbKbf@qqEhrJemVz{HguHjvJ{fOtiWquO~fGnhF~x@heD`lB|oZ",
            "{bfzGsonz@ieCbI}sAsdAidJczN}wLwhLskZugd@uaGrc@m_Cu_BscAayCoLkvJm~CcjTstEiaQepHwmLmuLenIq{RieZakBgk@u" +
                "hFjgCahC~~Ks{BvLubBmqByxGelUijBkvWwdCstD",
            "{|x|Gm~j`AylBn{KvfBpnFpzAdeL|wRlw@`xGcmH|dBkeF|_BoyK~k@{a_@wl@cxOgbCofHtf@yfCgyE}kO}KcuEriJsiJlzJ{eD" +
                "jr@mqBfpI{~HxfCeuExsDzRldBkq@jb^r_MvaChhChoFbaMpoKhpKpdEo]|{CwcCdnI_vAzwJnw@p{G~qC|bAv~E|~H|_IxxBhl@" +
                "v~KqtC`xB~z@zsKx_QjfE~pDhm@wm@vhMxxIdfApvBt|C`CzuD|oBpdEuaA~bCacKsTuhLpeCibDlcBi`FbpAxm@{e@stE`zB|Xr" +
                "~AeeA`zBcvEmtA?ryCioVlnCqeJtxEwl@?}sAxpEr~BvwA}lDhhBzTpbKwsIpvCo`I|yDg|E|_C}vLyiBm_IkDkiDjaAoyLbbAg~" +
                "CgNkzIngAwzEkxDoeHs`AcsFmt@oan@p`@csEflDknMha@stFixBcgIajBcd@ayBcwE",
            "izu{Goepd@apFlWu_NygZg`Eo@y|FchIakBsFasC_mEuiFvdBueFgOp`@eaBcVklBoqOqfU?ajHiyBahHpC_vB_iAc|CmkD{nAio" +
                "@knBq^knLgiBtGwk@uzDcaG}xKedGskHcsEugLimA`L",
            "oam_H{`bd@`iB|jCwZbqF|sAouAlxExcO?otA|e@?deAzbEYzsAkdAjjBti@bf@hxAmtArjDbyCzq@|hFo}EvM_LdpHrvDr~L{~@" +
                "noEpiBlcSz~FbnH|h@~_IfuA}Ur~BpnFj}AbEhzBdcBle@ym@n]z{HpzA`yAxsDa|@x~F~lDiq@r}Bhq@r|BugAxfCqPlkEje@nl" +
                "Er}AhhC}sAte@gj@nxAdf@d~B{pAltAtHv{C",
            "}|avGkurs@p]ihCjpGcaAr_ByfDleGrc@d_CoqChwN{lCxlFwkJzwVsyOfyWgz^z_CevFbqEcoSzaBapE`fCmqB",
            "cstpGsstm@b`BroEfgA|wHbaBl`AncJl_SncEyTnuHn`Af{BlsBfc@lsBmh@vmIelGzmNkIrcJskB~wM?|gF",
            "cstpGustm@wfC{UumI}fEqvCdbA_rCihBfA{p@i|GjeDw{KtJe|Cs}Ag`EceL{uDc_Asq@_rDo`E}dFkkCcrG`BwzEjaBozL_xAu" +
                "|Oxm@yeNmcAyqKdh@mv@qRmtM~qCieDbb@e|CvaDixHhmAceKfLwzEyk@weC|sAukJrtE_kFj`LamFneBoqCwg@{qAvg@g_EiP}{" +
                "J_mEkiOs_BaiTsmAeeAlt@i|Fmg@gi@cEmmD{oBwfB_z@epHkwCsbL{FsrFxjAczNziDykNeKysUxiBk`Gs{GaDqSq}@b|Bu`CfM" +
                "ihBubBqnFdg@koAtnD~[fsBgvGhRi~Fa|@u{DgaDpAui@{lAbrAq`AxnEgmJsa@eh@kkCp}@nZ}xK_gGzoA}YgbCjs@qwBxhChl@" +
                "e`C_xLtWufApzAorCddMkyHnMomEueAijNjs@gzFfqI}vWil@eoHlg@a|AzkHswDd_CgeNef@mrNqjGscKopDihCszCq_@ofBd_C" +
                "gxA_Zi~@gdDnwAmyUm~B_gHpm@w}DclBc_CuYu}Bnk@}hFok@ucAvsC}{IxP}nCucBkvKbaAgbCyBo_Wl_D^rwJiuU~h@w{DhuDy" +
                "nAkc@_aJlUkbFfwGy_R{R}oBavC}gFucBujJupBehA_l@{`FmtAmtAus@erSts@oqDca@_hFrRkjO_fAw_Fui@?kpA|lDim@?qR}" +
                "wK}u@u`Bjb@qkG`{BshJj_G_dIze@g_ElJisVgxAidP",
            "inf|Ggi`jAcbB_l\\|NshEumFizh@upDehKo~CcjB",
            "ka{|Goo}lAjvMocc@~xAugL~YujUw{Dkxb@_yAidDw|Ekq@c`AefA_@mjEzt@meF~oCy}FbmI_wXvnJuyQ~yKct\\bf@_|K`tCuv" +
                "RfzFwgMx{@wwF_hAy|SsC_aUinCaxW",
        ),
        borders = listOf(
            "{whwG_ozi@tvGuhLzW_kKseF__Y|a@qtMcp@ggEs{DopJybAe|HkdCe`Cyd@sgBbnB}{Rz|FijKc\\y_DpkAkkH|Uw~Hu\\emAc_" +
                "Cwc@cCs_CkpE{sAoq@cyAuqAgvNq_BuyBevNsgDcz@ubGucDgpGoiEsfCidFlPmvFvwDkoB|fDupBcxA}tAayBqrCovO_xGorH_c" +
                "BuwFukBobBqnBzbAyoDmxDyrBaeOxTqrD|tA{tAblC{XtoJbQrcNtyBz{F_|AxjD{aMrrOi{P|gD{wMzBylByxAesDh}AipCj\\i" +
                "aK~pC}}CrgOj~Kl[yiEtcEexL|lKc`GfcJrjAus@mvFdwAwgKejDqfEy|HsrDsfB`fAodAx~FwjFf|DqrD}yEuxE`nBafAcZokCq" +
                "cJifCwdAq|E_JowBsrBctEaeMseEapBqhD}nGgqRsyHemHj{AweFeBk{BjnCqnHs|CqkAovByXgoHvU_{BjlAoCbvBwmEokCwaD}" +
                "y@{tC``Wu{@lrB_nFl`Fu{BfiC{rExc@ipCxDkkU}_@qtBwzAs~Ao~DeDct@ybAtkAujHcpD{`PeY_iKb}A{{GliJssAtlFoqIjv" +
                "FmcA|AwmEmdAofGgkAmmDovB_qAmnB`oAytDv`GqrDbmAkpCymAkzBioDggCen@odAzl@{sB`zPssAdaBo`ComB}hBnbBqqHa\\i" +
                "cEioF_yF_gBekCwjS]{_Ddw@mbBviGyD`|@w`GfyAmxBnrA{_\\u}F}gCwxGri@sjAnaCuRbiG}pEhdDspDq|CaxE}_@s|BqtD_m" +
                "GvfAmwCclDm`Gqv@",
            "__{}Gq{d{@wuAdOihGldg@",
            "a_f~G}e|y@vZnfI",
            "ice~Gm~qy@cT|sB",
            "av||Gy{y|@y}@dnKktEl}JwrCp{SkpA~yCyfCxxA}hIod@",
            "ca{}Gibf{@bAve@",
            "ejy}Gsdk~@kRzbA",
            "q}y}Gw`i~@zjAvvEtzBr|ClnCblBvsBfB~CtzC",
            "ue`}Giwx~@kdCzMksEqlAmhBr`@e`D`kGc_E`bE",
            "ejy}Ggek~@?R",
            "ylk}Gi_u}@yTlxB",
            "sbl}G{eq}@|KjdBrlB~}AjrFrrBr}B`qL",
            "mxe~Goiny@ktCokDmaDgj@m~Ch~@mlCpsC}iA~xDy_EybAacExkCavA_i@o|AhcC",
            "kdhjGihxl@ciMrwCajNcmNatHomMm_HekCykDucFekBgKeoJrwHcjE}tAgXd`EbxB``GbkFjrf@oCfzFkr@zuBq`BzkAmmAjiJ{e" +
                "HtwSwmEdiRnN~vHsgAbmCmmDnwAazCtlFyzJ``Iu`I{l@}gC{|FgpFh`JanDdkCmaEjR}rAoaAwmDo}HswHslHwcCjeA}}Bqk@ad" +
                "B}qBgw@mnCpl@ecMopIbaF_vIn_CytEug@{uBfiCwzAhxHdOxuOqoHrzRyaCdlBapOvZssAbcDqu@x{Ga{A|iAouCjRetDprEaaF" +
                "asK_IsxEycB{tEdY}yE~nCceMkdAmjEmdB|s@_t@}_@mY}zFwvF_xG_rBwzLvyA{_DwvDy_DwcB{hDusKxaBoqJujJalD_}@cxCd" +
                "nKkwE`zCw_GllPe|IjpAoiDhhBkdEkfB_|Abe@}hAtvGmnCl`Fel@vuFewArgDadC||BwqJfvAeuEce@a{AmnAckA_iGlhAwbC}n" +
                "Bkw@qBudEylAoqGsiA_}BubGanDevAszC",
            "mxmtGgsgrACR",
            "ajmkGo|dkAlbD}~@buFbwAbgClnB~Rx`E",
            "kt{jGaszjAwdAtyDedCdvAgtCs}@qtB{_D}~AyzJ",
            "sik~G}_jiApa@irCvcDzBdzBbdCjoCnyJnlBz`AhuKq}Ddx@Th}@tzAp{@}yGjvBknCzZe{Itm@yaBrgCox@vgJ~h@nqC}jMhpIc" +
                "lDnbCkwEjoB_pQxaCecK",
            "k}t}G}}rfAomBegG_^qzGkvEg`Ng`AyrGqMw|Lm`F_xRcu@mqK",
            "ga|}G_r_eA`tBwgI",
            "q|t}GyvsdAucFezJ",
            "wwz}G_}weAzk@u`I",
            "elx}GwzieAqjAgaM",
            "{jy}G_hefAlGyuB`dCc~H",
            "ify}GyxcfAqCen@",
            "{jy}G}abfApC{u@",
            "{jy}Gu~afA?gB",
            "kex}Giv`dAxgBo_R",
            "kim|Gu``bAqGcxA{bFkbFmy@ayBcwBaHkhNcjForGksKamCq_Paq@}tL",
            "ue`}Giwx~@zoByiEvRabG",
            "oa`}Ggo~_AxtEg}Pd~@w{@lvCheEvu@md@r@ebA",
            "aa||Geeg_Am_CaiV",
            "gyq|Gkps`AhwAgxH",
            "u|p|Gqlo`Aq[ybC",
            "exo|Go`aaAvdBuaH",
            "}`o|Gsi}`AgV{uB",
            "mpn|Ga}uaA`f@sbI",
            "mrl|GecjaA_}@{xJ",
            "_rw{Ge{_lArTwsHl~AgfF",
            "aqv{GootkA}_@ujJ",
            "u}t{GegwlAloE{tPngAavl@vpAg_O|kEapOtG}zF",
            "}|s{GewplAw_@_oE",
            "e{e{Gg~rpAb`@gpG",
            "k}b{Gka_pAy|A{{R",
            "ime{GslgqA~fBqrDxEohGhoDuqY",
            "azd{Goo{pAgRc|J",
            "en|zGk|orAgLq`B",
            "}pbjGqtel@||Bo}D",
            "arziG}r}k@koCej@omBmuE",
            "m{|zG}}rrA|cIbmA~`BncAnj@|sB",
            "_inzGkvjrAwBjyC",
            "wlnzG_|erAfRzrElrIpuLlvEnvQxeIjjGleAxaDnaOkwG",
            "w_dyGus|pAjzAy`PtyDqpHlP{}C",
            "{~_yGgdzpAmQoiDmmB`zA",
            "cf{xGa~arAtRsqCrsByn@hdF|qDxoJtvTlcCvmCnwBmo@xvBjoDnrFyhH",
            "gxzxG}e|qA{LcwD",
            "yotwGuk`rAzuB}hB~wFbzApbKnrFxtEtSvbCs~ApaAkmD~g@w~H~eDerH|gCwoLxjQaqNnlBwaFzeHhdHhTdfH",
            "m_qwG_qmqAkoBuyQ",
            "yqeuGilfsAu|AvuF",
            "oohuGqu~rA|Q`sH",
            "o|d~G_ijy@{fAriOiy@`FoxE_cFkdCfBsdH|fDkqE{M}jHexD",
            "mxe~Goiny@|Zn_C",
            "gnfyGw}~c@s_@wlDsh@eZimH}h@aiJ{}EcdAjGcbD~fDgnCbpIswAirAoiFhTevNs|NqsBbvCkqAjRs|Qk{[ahDs~LylIkyPg|Ci" +
                "TcdBz_BezIkxDuzCtHkdDdlBgzEa|AewB}mHuoCm_TexE}_L_lCwmC}rB|iAibB_sAk_Da_J{iBvFqk@izDkaGoxKcdGkkHasEmg" +
                "LynA~K",
            "o~gxGmrxh@qiDe`Cg_Ap~AgkAjpN}gBhu@_uLaeDwiHq|EgzMdbN{lEieEe~E_^i}AlwCoeDdb\\eHr_L",
            "qupzG{u}f@zu@noKp{FzsOrtAvwQpxBziE~}G~tHftAr`@bhHsqC`q@wzA",
            "wdkyGglge@h|CgkAhmHjpPhbG`~HjgAxiE",
            "ocjyGscde@g`@sgB",
            "c}fyGq{{c@zMeaB",
            "mzpxGwyjc@g{FouCytDtnDgjAgVkdEwbP",
            "mmrxGg}gd@{`ApsE",
            "iotxGuhad@vFz{GblB`qL",
            "k~_xGss|h@{a@hqBkbFqA",
            "sdhxG{cyh@bElP",
            "{whwG_ozi@agL`vE{yIndMsj@`mC",
            "mfbxGkdai@`gAvoC",
            "spzzGkybsAyiAlzN",
            "gfuzGgcmtAaxE~}Y",
            "i_|zGgdrsAtm@ziN",
            "golzGmbtvAcYxmh@i_FdmLwu@pnH",
            "m`vzG{ustAdYrqE",
            "e~gzG_vhwA_hAxhH_gBdvC",
            "eomzG_uzvA|^pqE",
            "_qhzGehlwAxQdqB",
            "ojw~Fmf_kAhFU",
            "ecw~Fcg_kAiFT",
            "qxmtGsrgrAqS|sBcbDbwE",
            "c_`uGehlwAdhDliBliHvwQjQn~GejCrbTxaCjhMnMvgIysEnlNcf@|eGxbCf`AlnBmcCdlAboAnvArcHf}CnsEew@boL{}DpyJjV" +
                "hvU",
        ),
        locatorFrame = GeoBox(36.30000, 6.30000, 47.40000, 18.80000),
        locatorLand = listOf(
            "uwoxFegxy@luiAwy`@tcl@ju^`bp@qmKzeeDnd[ldD`{MyaNpkj@|zBvlUufG`dQnxt@|oPt|HxsOmtA`nl@uou@z~k@g{t@~uBq" +
                "{m@idIcdDo{BdfB_qLs_Tcl@akJ`cIszBpePoihAwkKcrg@|`Veo\\n{^wbr@guEtaLcdZcWwvg@cnReuo@{~z@epnAjyIetI|`I" +
                "as`@l}X}g^dsOb`KbxHohN",
            "{lgdGiszx@tt[pbDduSy`MbrqAexC~vf@fg\\hio@reDzkx@pvc@uvf@h}hA{|TsnNuzJh~_@g~^kkCwa@~cVqe_@mmNwvKlbUgi" +
                "JzeCuvK_jTqkMrmTgod@sx[mjJ}zR_oIauk@g|L_lQhzByga@glz@gvHhbFspRlha@yiB",
            "}{ghFoha~Az`tA`yaAzu~@njYdeWglBzsP_cUvzE|}Ina]{vVndi@fcb@jq\\bS_lCzv`AwfPfpt@oko@jln@sdJttU|Qjkm@k{E" +
                "nnSiabAtdzBayPf_o@}sChmv@}tMddUaj\\`yPepl@u{TilX_nc@f}[e{_@srHiq[ucH{o@krJocSaFurXbah@_f`ByqJa_r@~rC" +
                "slm@crDcsi@gvValv@bxA{g_Ak~Y{eiAppCspYlfHdjJ",
            "cimwFgiatAoRfxLwjI}TbkCgwPbrE|sC",
            "mbj_FmwphA{pCprT{fKmm@fiCa{MnnKahD",
            "swleGwasdBjhEqouAvfHmnQcbAbdh@thEzwWsmFhc]ahKt|G",
            "c_ffGwe}gBnOvpcBmuPbcz@w_Byh[v_BahYrqFeaGhrHy_`B",
            "qhbgGyjmeBa`Bfrx@caEzbLksLc`DlaFahjAbaFybJ~qGzuS",
            "mvqdGohm~@`i[kvCujHbjOhvBl|f@siLdVajAoel@__F{`F",
            "akmmFe`wr@~hR|eJstLjyJyaNsc@lmHu{T",
            "_rnyFwjqq@r|GdoEwSdeHshW}jUt}BcrC`aKtgJ",
            "k||kGcy}{Ah{Es`Bc}K~jWgqKj}I`sQwg_@",
            "qqoqGaskyA|dCfaWksLrmM_oIfw^wl[kqVdko@wum@",
            "k~dpGowoyArrGo|C}vIbza@ehN}kAvS}lKvwOwaN",
            "kirmG_ou{A~dDv`Dcoa@hxo@_ih@`k`@vxbAwg`BjyAr`I",
            "wqakGypu{AxxCqoAqz@jzKi|q@n{s@`~n@if~@",
            "mskkGefy|AnoMkzK_~JzbXewH`pFteFqxR",
            "ktqoGqulwArqFfo@uqHf{J_}k@p|SkjVwkDcjWvqIg~ByzGh`e@yqYnq{@m`C",
            "oi`dGy_njBjlLusYwqPrcmAjdC}nr@",
            "_yh`H_{vqB~}vbA??~khkAwupC}lDcwFy~]|cOomPniO{tcAwqHkv{@eeWrtEzmEwpk@~rJsfa@xiVg|b@ntCyeV{qZyiqDkne@i" +
                "e}@}m[osiBfcEqk\\t`RrsInzMi`Hi`Hg|KedM~`C~Pyjh@xzGehTxq`@rn@d|_@ek[hkOb~FhuH_gV_sJstSoePakIu|Hgae@ie" +
                "Xgdc@uqA{_Sfwe@ueM`rXtc^zxo@p_`@hjMnl]tjVthX?yqqq@_arc@?_aOhs_@_sKepAh|@raXcefAhnfCmwF|sm@yua@dkhBuc" +
                "Aaaa@~ea@ykaBykeA~`sBclb@dek@in\\jmbBjrClwnAkvYhrG}fp@`juAylr@xf|@epO`hKegEio^hhB_nc@os_Ahs~A{fShyO_" +
                "vr@weAclTtcIiii@rkz@qyFdmm@fxa@h|Mdh~@tys@_JvoSo{s@nel@}}gAt{Tcl[e~r@ca[rg]p@fuLrzJrdQ}~Jlpq@xcYnka@" +
                "|ia@l`gBaf@|wKg`N_iSqG`tGpqRfni@j}f@~nHrkf@oq_@|_MoqXd~VduJ~cHjmNyrEvrSvlT`~Dlk`Bu{[dwk@sqx@rjModi@l" +
                "|l@wyjAllUios@fjkAi~m@rz~A_eg@lwb@us`@zswAendCtcVobz@{`@uizCjmGudf@r`OexC|yIxkFh{Yjkm@|fT~qAb~Mu{T`v" +
                "f@kihBtd`@gvjBzgj@olgAvec@w{|A`pv@w{gAhg\\szXhuUo|Cnjv@`wZiqUj|r@c`bApqh@ivJvszAwnJ~}YegSzdN{aAp`\\j" +
                "yI|bSht}@doq@reu@xgZt{Trq@~eTeyMvyJagk@rre@}tw@vuiAkvJfkNnzMy~Bdv[`xH|ge@tnPhbZltOvgJvuz@rrA~c^zkr@d" +
                "b{@z`k@bP`|_AoqQ|jNgqZ`Pe~OadJg}FozVggb@cbOcnXt`DihJgkHm~FyzGmbHsyj@wob@kqA_dOz_Scl_AtjOsi{Bzr_AofKp" +
                "_TmjBlww@e_`@xbbA_xLbgCogLmcJa}PloF_k^tbTeoFllMzqLbdrAwjXypVskOzr\\lAltr@yiJwS}uq@huc@ksSxtWrTj{a@ia" +
                "Jjc{@jxGx{]qe_@pwm@{{Jvsi@}_{AhokBgqZrks@ocg@xc`@koYhraAvoEfh]}eDllF}xFu|NajNfiBgwf@j|k@{xKthYexX~nQ" +
                "_bEvxd@wcm@gd@cu_@vhM{uZ`yWczsArzX{cMtlZozN~z|@}qi@jfuAecSbgeB`{Mtwh@rtzApyiBdhb@repCt~}@vliBtaa@zq[" +
                "|cKzws@ws_Y?",
        ),
        locatorLine = "q{}vGyjvj@zkHuzAjvCgdRvwJ{eGsiBqm_Av{v@srj@}vBseI|pVgqo@ddIsa`@mmAkpS`eIa}VcmAc`U`~Tue|@og" +
            "DgtRfnL_|u@coF}aKz_@a~P~oT}uQhqJiu^~fKco@z`D}rq@zqYw|A~tB_kLvuItyHpdM}`Bp_]toc@nrH}hCpcGlqJd|NwaQh{`@dxD" +
            "bmKccLvoBswWnxTinW~pNqxb@lRsf_@pbTa`d@|~{@ipr@`|HcpSweAwgIvjKsnBr_C{gVfhf@o`V`{GcnW|vMyvEyi@{kHnaSg}P`fK" +
            "xNdgPs}Ul`H`c@pqHadTtk`@owHviNsnPpaMjyNtnZ_n`A~lZ_oCrgDtaFvhTuwN",
    )
}
